const fs = require('fs');
const done = [];
const q = [
// Biology: Cell Biology (15)
["A student adds a respiratory inhibitor that blocks the electron transport chain. Which process is most directly affected?","Diffusion of oxygen","ATP synthesis by oxidative phosphorylation","Osmosis of water","Transcription of DNA",1,"The electron transport chain drives ATP synthesis via oxidative phosphorylation. Blocking it stops the majority of ATP production (approximately 32 ATP per glucose), severely affecting all energy-requiring cellular processes."],
["A student compares the rate of enzyme activity at pH 2 and pH 8 for pepsin (optimum pH 2) and trypsin (optimum pH 8). Which of the following correctly predicts the results?","Both enzymes are most active at pH 5","Pepsin is most active at pH 2; trypsin is most active at pH 8 — each enzyme has evolved to function in its specific physiological environment","Both enzymes are equally active at all pH values","Trypsin is most active at pH 2",1,"Enzyme optimum pH reflects the environment where they function: pepsin works in the acidic stomach (pH 2); trypsin works in the alkaline small intestine (pH 8). At non-optimum pH, ionic and hydrogen bonds maintaining active site shape are disrupted."],
["A student investigates the effect of inhibitor concentration on enzyme activity. A competitive inhibitor reduces activity but adding more substrate restores it. Which of the following correctly explains this?","Competitive inhibitors permanently block the active site","Competitive inhibitors bind reversibly to the active site; increasing substrate concentration outcompetes the inhibitor for active site binding","Competitive inhibitors change the shape of the active site permanently","Competitive inhibitors bind to an allosteric site",1,"Competitive inhibitors have a similar shape to the substrate and compete for the active site. The inhibition is reversible — increasing substrate concentration increases the probability of substrate (rather than inhibitor) binding to the active site, restoring activity."],
["A student measures the oxygen consumption of germinating seeds at different temperatures. Consumption increases with temperature up to 35°C then falls. Which of the following correctly explains the fall above 35°C?","Seeds run out of oxygen above 35°C","Respiratory enzymes denature above their optimum temperature, reducing the rate of aerobic respiration","Seeds stop germinating above 35°C","Oxygen becomes less soluble above 35°C",1,"Aerobic respiration is enzyme-controlled. Above the optimum temperature (~35°C for most plant enzymes), the tertiary structure of respiratory enzymes is disrupted (denaturation), reducing their catalytic activity and therefore oxygen consumption."],
["A student compares the number of mitochondria in cardiac muscle cells and skin cells. Cardiac muscle has far more mitochondria. Which of the following correctly explains this?","Cardiac muscle cells are larger","Cardiac muscle contracts continuously and requires large amounts of ATP; skin cells have low energy demands and require fewer mitochondria","Cardiac muscle cells divide more rapidly","Skin cells do not respire",1,"The number of mitochondria in a cell reflects its energy demands. Cardiac muscle contracts continuously (approximately 100 000 times per day) and requires a constant, large supply of ATP. Skin cells have relatively low metabolic activity and fewer mitochondria."],
["A student investigates the effect of light wavelength on the rate of photosynthesis. Which of the following correctly explains why green light produces the lowest rate?","Green light has the highest energy","Chlorophyll reflects green light rather than absorbing it, so green light cannot drive the light-dependent reactions","Green light is absorbed by carotenoids only","Green light has the longest wavelength",1,"Chlorophyll absorbs red and blue light most strongly for photosynthesis. Green light (~550 nm) is mostly reflected — which is why plants appear green. Reflected light is not absorbed and cannot drive photosynthesis, resulting in the lowest photosynthesis rate."],
["A student investigates the effect of CO2 concentration on the rate of photosynthesis at two different light intensities. At high light intensity, increasing CO2 produces a higher plateau. Which of the following correctly explains this?","High light intensity increases CO2 production","At high light intensity, the light-dependent reactions produce more ATP and NADPH, allowing the Calvin cycle to fix more CO2 before another factor becomes limiting","High light intensity reduces the need for CO2","CO2 concentration is unrelated to light intensity",1,"At high light intensity, more ATP and NADPH are produced by the light-dependent reactions. These drive the Calvin cycle faster, allowing more CO2 to be fixed before enzyme concentration or temperature becomes limiting — hence a higher plateau rate."],
// Biology: Genetics extended (15)
["A student analyses a family pedigree for a condition that appears in every generation and affects both males and females equally. Which pattern of inheritance is most consistent?","Autosomal recessive","X-linked recessive","Autosomal dominant","Mitochondrial",2,"Autosomal dominant inheritance: one copy of the dominant allele is sufficient to cause the condition. It appears in every generation (no skipping), affects males and females equally (autosomal, not sex-linked), and affected individuals typically have at least one affected parent."],
["A student investigates the effect of UV radiation on the mutation rate in bacteria. UV exposure increases the frequency of mutations. Which of the following correctly explains the mechanism?","UV radiation increases temperature","UV radiation causes thymine dimers — covalent bonds between adjacent thymine bases — that distort the DNA helix and cause errors during replication","UV radiation destroys ribosomes","UV radiation increases transcription rate",1,"UV radiation causes pyrimidine dimers (most commonly thymine dimers) by forming covalent bonds between adjacent thymine bases. These distort the DNA double helix, causing DNA polymerase to insert incorrect bases during replication, resulting in mutations."],
["A student compares the genome sizes of different organisms. Humans have approximately 3 billion base pairs; a simple bacterium has approximately 4 million. Which of the following correctly explains why genome size does not directly correlate with organism complexity?","Bacteria have more genes than humans","Much of the human genome consists of non-coding sequences (introns, regulatory regions, repetitive sequences); the number of protein-coding genes is a better indicator of complexity","Humans have fewer chromosomes than bacteria","Genome size determines intelligence",1,"The C-value paradox: genome size does not correlate with organism complexity. Much eukaryotic DNA is non-coding (introns, regulatory sequences, transposable elements, repetitive DNA). Humans have ~20 000 protein-coding genes — similar to many simpler organisms."],
["A student investigates gene expression in differentiated cells. All cells in an organism contain the same DNA, yet liver cells and muscle cells have different proteins. Which of the following correctly explains this?","Different cells have different DNA","Gene expression is regulated — different genes are switched on or off in different cell types through epigenetic mechanisms and transcription factors","Differentiation changes the DNA sequence","Muscle cells have more chromosomes",1,"Cell differentiation involves differential gene expression, not changes to DNA sequence. Transcription factors, epigenetic modifications (DNA methylation, histone modification) and regulatory RNA molecules control which genes are expressed in each cell type."],
["A student investigates the inheritance of two traits in pea plants: seed colour (yellow Y dominant over green y) and seed shape (round R dominant over wrinkled r). A YyRr plant is crossed with a yyrr plant. What phenotypic ratio is expected?","9:3:3:1","1:1:1:1","3:1","All yellow round",1,"YyRr × yyrr (test cross for two genes): gametes from YyRr are YR, Yr, yR, yr (equal frequency). Each combines with yr from yyrr. Offspring: YyRr (yellow round), Yyrr (yellow wrinkled), yyRr (green round), yyrr (green wrinkled) — ratio 1:1:1:1."],
// Chemistry: Organic extended (15)
["A student investigates the reaction of chlorine with methane in UV light. Which type of reaction occurs and what is the mechanism?","Addition reaction; ionic mechanism","Free radical substitution; UV light generates chlorine radicals that substitute hydrogen atoms in methane","Elimination reaction; acid-base mechanism","Nucleophilic substitution; polar mechanism",1,"Alkanes undergo free radical substitution with halogens in UV light. UV photons split Cl₂ into chlorine radicals (Cl•). These abstract H from CH₄, producing CH₃• which reacts with Cl₂ to give CH₃Cl and another Cl•, propagating the chain reaction."],
["A student compares the reactivity of primary, secondary and tertiary alcohols with acidified potassium dichromate. Primary alcohols oxidise to aldehydes then carboxylic acids; secondary to ketones; tertiary do not oxidise. Which of the following correctly explains why tertiary alcohols resist oxidation?","Tertiary alcohols have no O-H bond","Tertiary alcohols have no hydrogen on the carbon bearing the -OH group; oxidation requires removal of this hydrogen","Tertiary alcohols are less soluble","Tertiary alcohols have higher boiling points",1,"Oxidation of alcohols involves removal of hydrogen from the carbon bearing the -OH group (C-H bond). Tertiary alcohols have no H on this carbon (three carbon groups attached instead), so oxidation cannot occur under normal conditions."],
["A student investigates the polymerisation of propene (CH₃CH=CH₂). Which of the following correctly describes the product and type of polymerisation?","Condensation polymerisation producing polypropene and water","Addition polymerisation producing polypropene — the C=C double bond opens and monomers link into a long chain","Substitution polymerisation producing polypropene","Elimination polymerisation producing polypropene and HCl",1,"Propene undergoes addition polymerisation. The C=C double bond opens, allowing monomers to link together. No atoms are lost — all atoms in the monomer are incorporated into the polymer chain. Product: polypropene (used in packaging, fibres, automotive parts)."],
// Physics: Waves extended (15)
["A student investigates the interference pattern produced by two coherent light sources. Bright fringes appear where path difference equals nλ. Which of the following correctly explains why dark fringes form?","Dark fringes form where light is absorbed","Dark fringes form where path difference = (n + ½)λ — waves arrive exactly out of phase and destructively interfere, cancelling each other","Dark fringes form where light is reflected","Dark fringes form at the centre of the pattern",1,"Destructive interference occurs when waves from two coherent sources arrive exactly out of phase (path difference = half-integer multiples of wavelength). The crests of one wave coincide with the troughs of the other, resulting in zero amplitude — a dark fringe."],
["A student measures the speed of light in glass using a semicircular block. The refractive index is 1.5. What is the speed of light in the glass? (c = 3 × 10⁸ m/s)","4.5 × 10⁸ m/s","2 × 10⁸ m/s","1.5 × 10⁸ m/s","3 × 10⁸ m/s",1,"n = c/v → v = c/n = 3×10⁸/1.5 = 2×10⁸ m/s. The refractive index is the ratio of the speed of light in vacuum to the speed in the medium."],
["A student investigates resonance in a closed pipe. The fundamental frequency has a quarter wavelength fitting the pipe length (L = λ/4). For a pipe 0.85 m long, what is the fundamental frequency? (speed of sound = 340 m/s)","100 Hz","200 Hz","400 Hz","50 Hz",0,"λ = 4L = 4 × 0.85 = 3.4 m. f = v/λ = 340/3.4 = 100 Hz."],
["A student investigates the Doppler effect. An ambulance siren emits 800 Hz. The ambulance moves toward a stationary observer at 34 m/s. What frequency does the observer hear? (speed of sound = 340 m/s)","880 Hz","727 Hz","800 Hz","760 Hz",0,"f_observed = f_source × v/(v - v_source) = 800 × 340/(340-34) = 800 × 340/306 = 800 × 1.111 = 888.9 ≈ 880 Hz (approaching source increases observed frequency)."],
// Earth Science: Climate extended (15)
["A student analyses data showing that Arctic sea ice extent has declined by 13% per decade since 1979. Which of the following correctly identifies this as a positive or negative feedback?","Negative feedback — less ice stabilises temperature","Positive feedback — less ice reduces albedo, increasing heat absorption, causing further warming and more ice loss","Neutral — ice loss has no effect on temperature","Negative feedback — more water absorbs more CO2",1,"The ice-albedo feedback is a positive feedback: warming → ice melts → darker ocean exposed → lower albedo → more solar energy absorbed → further warming → more ice melts. Positive feedbacks amplify the initial change, accelerating Arctic warming."],
["A student investigates the effect of ocean warming on hurricane intensity. Warmer oceans provide more energy to developing hurricanes. Which of the following correctly explains the mechanism?","Warm water cools hurricanes","Warm ocean water increases evaporation, adding more water vapour to the atmosphere; condensation of this vapour releases latent heat that powers the hurricane","Warm water reduces wind speed","Hurricanes form only over cold water",1,"Hurricanes are heat engines powered by the latent heat released when water vapour condenses. Warmer oceans increase evaporation rates, providing more water vapour. As this vapour rises and condenses, it releases more latent heat, intensifying the hurricane's circulation."],
["A student compares the carbon stored in permafrost with annual global CO2 emissions. Permafrost stores approximately 1500 Gt of carbon — twice the current atmospheric carbon. Which of the following correctly explains why permafrost thawing is a major climate concern?","Permafrost thawing reduces methane emissions","Thawing permafrost releases stored carbon as CO2 and methane as frozen organic matter decomposes, creating a powerful positive feedback that could significantly accelerate climate change","Permafrost thawing increases albedo","Permafrost stores no significant carbon",1,"Permafrost contains vast amounts of frozen organic matter. As it thaws due to warming, microorganisms decompose this material, releasing CO2 and methane (a potent greenhouse gas). This creates a positive feedback — warming causes thawing, which releases greenhouse gases, causing further warming."],
// Scientific Method extended (15)
["A student investigates the effect of exercise on heart rate recovery. They measure heart rate at 1, 3, 5 and 10 minutes after exercise. Which of the following correctly describes the type of data collected?","Categoric data","Continuous quantitative data","Discrete qualitative data","Ordinal data",1,"Heart rate (beats per minute) is continuous quantitative data — it can take any numerical value within a range and is measured on a scale. Time is also continuous. This type of data is best displayed on a line graph."],
["A student reports that their experiment supports their hypothesis. A peer reviewer points out that the sample size was only 5. Which of the following correctly describes the concern?","Sample size does not affect conclusions","A sample size of 5 is too small to draw reliable conclusions — results may not be representative of the population and could be due to chance variation","The hypothesis must be wrong","Peer review is not necessary",1,"Small sample sizes increase the risk that results are due to random variation rather than a real effect. With only 5 data points, one anomalous result significantly affects the mean. Larger samples reduce the influence of random variation and increase statistical power."],
["A student measures the length of a metal rod at different temperatures. They plot temperature (x-axis) against length (y-axis) and find a linear relationship. The gradient is 0.002 cm/°C. Which of the following correctly describes what the gradient represents?","The y-intercept","The rate of thermal expansion — the increase in length per degree Celsius","The initial length of the rod","The maximum length",1,"The gradient of a length vs temperature graph represents the rate of change of length with temperature — the coefficient of linear thermal expansion (in cm/°C). It tells us how much the rod expands for each 1°C increase in temperature."],
["A student investigates whether caffeine affects reaction time. They test 10 participants before and after caffeine. Which of the following correctly identifies this as a paired or unpaired design and explains why?","Unpaired — different participants are used for each condition","Paired — the same participants are tested under both conditions, controlling for individual differences in baseline reaction time","Paired — participants are matched by age","Unpaired — caffeine affects everyone differently",1,"A paired (within-subjects) design uses the same participants in both conditions. This controls for individual differences (e.g. some people naturally have faster reaction times). Comparing each person's before/after scores reduces variability and increases the sensitivity of the experiment."],
["A student calculates the mean, median and mode of a data set: 2, 3, 3, 4, 5, 5, 5, 20. Which measure of central tendency is most affected by the outlier (20)?","Median","Mode","Mean","All are equally affected",2,"The mean is calculated using all values, so it is most sensitive to outliers. Mean = (2+3+3+4+5+5+5+20)/8 = 47/8 = 5.875. The median (4.5) and mode (5) are unaffected by the outlier value of 20."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const domains=['Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Chemistry','Chemistry','Chemistry','Physics','Physics','Physics','Physics','Earth Science','Earth Science','Earth Science','Scientific Method','Scientific Method','Scientific Method','Scientific Method','Scientific Method'];
  const topics=['Cell Biology','Cell Biology','Cell Biology','Cell Biology','Cell Biology','Cell Biology','Cell Biology','Genetics','Genetics','Genetics','Genetics','Genetics','Organic Chemistry','Organic Chemistry','Organic Chemistry','Organic Chemistry','Organic Chemistry','Organic Chemistry','Energy and Waves','Energy and Waves','Energy and Waves','Energy and Waves','Earth and Climate','Earth and Climate','Earth and Climate','Scientific Method','Scientific Method','Scientific Method','Scientific Method','Scientific Method'];
  done.push({id:`MCQ-DONE-Y910-${String(i+1).padStart(3,'0')}`,domain:domains[i]||'Science',topic:topics[i]||'Science',difficulty:i%2===0?'Medium':'Hard',question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./done-bank.json', JSON.stringify(done,null,2));
console.log(`Done batch: ${done.length}`);
