const fs = require('fs');
const chem = [];

const chemQ = [
// ── Atomic Structure & Periodic Table ────────────────────────────────────
["An atom of carbon-14 has 6 protons. How many neutrons does it contain?","6","8","14","12",1,"Mass number = protons + neutrons. 14 - 6 = 8 neutrons."],
["Two atoms are isotopes of the same element. Which of the following must be true?","They have the same mass number","They have the same number of neutrons","They have the same number of protons","They have the same atomic mass",2,"Isotopes are atoms of the same element with the same number of protons but different numbers of neutrons, giving different mass numbers."],
["An element has atomic number 17 and mass number 35. How many electrons are in its outer shell?","7","1","2","5",0,"Chlorine (Z=17) has electron configuration 2,8,7 — 7 electrons in its outer shell, explaining its reactivity as a halogen."],
["Which of the following correctly explains why elements in the same group of the periodic table have similar chemical properties?","They have the same atomic mass","They have the same number of electron shells","They have the same number of valence electrons","They are all metals",2,"Elements in the same group have the same number of valence (outer shell) electrons, which determines how they react chemically."],
["A student compares the first ionisation energies across Period 3. Which element would have the highest first ionisation energy?","Sodium","Magnesium","Chlorine","Argon",3,"First ionisation energy generally increases across a period due to increasing nuclear charge with the same shielding. Noble gases (argon) have the highest values as their full outer shells are very stable."],
["Which of the following correctly explains why atomic radius decreases across a period from left to right?","The number of electron shells increases","Nuclear charge increases while shielding remains approximately constant, pulling electrons closer","The number of neutrons decreases","Electrons are lost across the period",1,"Across a period, proton number increases but electrons are added to the same shell. Greater nuclear charge attracts the outer electrons more strongly, reducing atomic radius."],
["An ion has 18 electrons and a charge of 2+. How many protons does it have?","16","18","20","22",2,"A 2+ ion has lost 2 electrons. If it has 18 electrons, it originally had 20 electrons = 20 protons. This is calcium (Ca²⁺)."],
["Which of the following correctly describes the trend in metallic character down Group 1?","Metallic character decreases","Metallic character stays the same","Metallic character increases","Metallic character is unrelated to group position",2,"Down Group 1, the outer electron is further from the nucleus and more easily lost, so metallic character (ease of losing electrons) increases."],
["A student tests the reactivity of Group 1 metals with water. Which observation would be expected for potassium compared to sodium?","Potassium reacts more slowly","Potassium reacts more vigorously and may ignite","Potassium does not react with water","Potassium produces a different gas",1,"Potassium is below sodium in Group 1. Its outer electron is further from the nucleus and more easily lost, making it more reactive. The reaction is vigorous enough to ignite the hydrogen produced."],
["Which of the following correctly explains why noble gases are unreactive?","They have no electrons","They have a full outer electron shell","They are all gases at room temperature","They have very high atomic masses",1,"Noble gases have a complete outer electron shell (2 for helium, 8 for others), giving them maximum stability and no tendency to gain, lose or share electrons."],
// ── Chemical Bonding & Structure ─────────────────────────────────────────
["A student compares the melting points of sodium chloride and iodine. NaCl melts at 801°C; iodine melts at 114°C. Which of the following best explains this difference?","NaCl has covalent bonds; iodine has ionic bonds","NaCl has a giant ionic lattice requiring much energy to break; iodine has weak van der Waals forces between molecules","NaCl is a gas at room temperature","Iodine has stronger bonds than NaCl",1,"NaCl forms a giant ionic lattice with strong electrostatic forces between ions, requiring high energy to break. Iodine consists of I₂ molecules held together by weak van der Waals forces."],
["Which of the following substances would conduct electricity when dissolved in water but not in the solid state?","Iodine","Glucose","Sodium chloride","Diamond",2,"Ionic compounds like NaCl have ions fixed in a lattice in the solid state. When dissolved, the ions are free to move and carry charge, allowing electrical conduction."],
["A student draws a dot-and-cross diagram for a water molecule. How many bonding pairs and lone pairs of electrons does the oxygen atom have?","2 bonding pairs, 3 lone pairs","2 bonding pairs, 2 lone pairs","3 bonding pairs, 1 lone pair","1 bonding pair, 3 lone pairs",1,"Oxygen has 6 valence electrons. In water, it forms 2 covalent bonds (2 bonding pairs) and has 2 remaining lone pairs, giving a bent molecular shape."],
["Which of the following correctly explains why graphite conducts electricity but diamond does not?","Graphite has ionic bonds; diamond has covalent bonds","In graphite, each carbon forms 3 bonds leaving one delocalised electron per atom free to move; in diamond all 4 electrons are in bonds","Graphite is softer than diamond","Diamond has a higher melting point",1,"In graphite, each carbon atom forms 3 covalent bonds in layers, leaving one electron per atom delocalised between layers. These mobile electrons allow electrical conduction. Diamond has no free electrons."],
["A student compares the boiling points of HF, HCl, HBr and HI. HF has an unexpectedly high boiling point. Which of the following best explains this?","HF has a higher molar mass","HF molecules form strong hydrogen bonds due to the high electronegativity of fluorine","HF has weaker van der Waals forces","HF is ionic",1,"Fluorine is the most electronegative element. The large partial charges on H and F allow strong hydrogen bonding between HF molecules, requiring more energy to separate them."],
["Which of the following correctly describes metallic bonding?","Positive ions surrounded by a sea of delocalised electrons","Negative ions held together by shared electrons","Atoms sharing electrons in pairs","Ions held in a lattice by electrostatic attraction",0,"In metallic bonding, metal atoms lose their outer electrons to form positive ions (cations) surrounded by a 'sea' of delocalised electrons that hold the structure together and allow conductivity."],
["A student investigates the electrical conductivity of several substances. Which of the following would conduct electricity in both solid and liquid states?","Sodium chloride","Silicon dioxide","Copper","Glucose",2,"Metals like copper have delocalised electrons that can move freely regardless of state, allowing electrical conduction in both solid and liquid forms."],
["Which of the following correctly explains why silicon dioxide has a very high melting point?","It has weak intermolecular forces","It is a simple molecular substance","It has a giant covalent structure with many strong Si-O covalent bonds throughout","It is an ionic compound",2,"Silicon dioxide (SiO₂) has a giant covalent (macromolecular) structure where every Si atom is bonded to 4 oxygen atoms. Breaking this network requires enormous energy."],
["A student compares the properties of a giant ionic lattice and a simple molecular substance. Which of the following is a correct comparison?","Both have high melting points","The ionic lattice has a high melting point; the molecular substance has a low melting point","Both conduct electricity when solid","The molecular substance has a higher melting point",1,"Giant ionic lattices have high melting points due to strong electrostatic forces. Simple molecular substances have low melting points because only weak intermolecular forces need to be overcome."],
["Which of the following molecules has a non-polar covalent bond?","HCl","H₂O","NH₃","Cl₂",3,"Cl₂ consists of two identical atoms with equal electronegativity, so electrons are shared equally — a non-polar covalent bond. The other molecules have polar bonds due to electronegativity differences."],
// ── Chemical Reactions & Energy ───────────────────────────────────────────
["A student mixes hydrochloric acid with sodium hydroxide solution. The temperature of the mixture rises. Which of the following correctly describes this reaction?","Endothermic; energy is absorbed from surroundings","Exothermic; energy is released to surroundings","Endothermic; the products have more energy than the reactants","Exothermic; the activation energy is negative",1,"Neutralisation reactions are exothermic — energy is released as bonds form in the products. The temperature rise confirms energy is transferred to the surroundings."],
["A student investigates the rate of reaction between marble chips and hydrochloric acid. Which of the following changes would increase the rate of reaction?","Using larger marble chips","Decreasing the concentration of acid","Increasing the temperature","Removing the catalyst",2,"Increasing temperature increases the kinetic energy of particles, leading to more frequent collisions and a higher proportion of collisions with energy exceeding the activation energy."],
["Which of the following correctly explains why a catalyst increases reaction rate without being consumed?","It increases the temperature of the reaction","It provides an alternative reaction pathway with lower activation energy","It increases the concentration of reactants","It changes the products of the reaction",1,"A catalyst provides an alternative reaction pathway with a lower activation energy. More collisions have sufficient energy to react, increasing rate. The catalyst is regenerated and not consumed."],
["A student plots an energy profile diagram for an exothermic reaction. Which of the following correctly describes the diagram?","Products are at a higher energy level than reactants","The activation energy is the energy difference between reactants and products","Reactants are at a higher energy level than products; the activation energy is the peak above the reactants","The diagram shows a flat line",2,"In an exothermic reaction, products have less energy than reactants (energy is released). The activation energy is the energy needed to reach the transition state (peak) above the reactant energy level."],
["A student investigates the effect of surface area on reaction rate using calcium carbonate and hydrochloric acid. Powdered calcium carbonate reacts faster than lumps. Which of the following best explains this?","Powder has a lower mass","Powder has greater surface area, increasing the frequency of collisions between reactant particles","Powder has a higher concentration","Powder changes the activation energy",1,"Smaller particles have a greater surface area exposed to the acid. More reactant particles are available for collisions, increasing the frequency of successful collisions and the reaction rate."],
["Which of the following correctly describes a reversible reaction at dynamic equilibrium?","The reaction has stopped","The forward and reverse reactions occur at equal rates, so concentrations remain constant","Only the forward reaction occurs","The concentrations of reactants and products are equal",1,"At dynamic equilibrium, the forward and reverse reactions continue at equal rates. Macroscopically, concentrations appear constant, but at the molecular level both reactions are still occurring."],
["A student adds more reactant to a system at equilibrium. According to Le Chatelier's principle, what will happen?","The equilibrium will shift to produce more reactants","The equilibrium will shift to produce more products to reduce the added reactant","The equilibrium position will not change","The reaction will stop",1,"Le Chatelier's principle states that a system at equilibrium will respond to a stress by shifting to oppose it. Adding reactant shifts equilibrium toward products to reduce the excess reactant."],
["The Haber process produces ammonia: N₂ + 3H₂ ⇌ 2NH₃. The reaction is exothermic. Which conditions would maximise the yield of ammonia?","High temperature and low pressure","Low temperature and high pressure","High temperature and high pressure","Low temperature and low pressure",1,"Low temperature favours the exothermic forward reaction (more product). High pressure favours the side with fewer moles of gas (2 moles products vs 4 moles reactants). In practice, a compromise temperature (~450°C) is used for acceptable rate."],
["A student measures the pH of a weak acid and a strong acid of the same concentration. The weak acid has a higher pH. Which of the following best explains this?","The weak acid has fewer hydrogen atoms","The weak acid only partially dissociates in water, producing fewer H⁺ ions","The weak acid has a higher molar mass","The weak acid reacts faster",1,"Strong acids fully dissociate in water; weak acids only partially dissociate. At the same concentration, a weak acid produces fewer H⁺ ions, giving a higher pH (less acidic)."],
["Which of the following correctly describes oxidation in terms of electron transfer?","Gain of electrons","Loss of protons","Loss of electrons","Gain of protons",2,"Oxidation is the loss of electrons (OIL — Oxidation Is Loss). Reduction is the gain of electrons (RIG — Reduction Is Gain). Together: REDOX reactions."],
// ── Electrochemistry & Quantitative Chemistry ─────────────────────────────
["In the electrolysis of copper sulfate solution using copper electrodes, what happens at the anode?","Copper is deposited","Copper dissolves into solution","Oxygen gas is produced","Hydrogen gas is produced",1,"At the anode (positive electrode), copper atoms lose electrons (oxidation) and dissolve as Cu²⁺ ions into solution. This maintains the concentration of copper sulfate."],
["A student electrolyses dilute sulfuric acid. Which gases are produced at the cathode and anode respectively?","Oxygen at cathode; hydrogen at anode","Hydrogen at cathode; oxygen at anode","Chlorine at cathode; hydrogen at anode","Sulfur dioxide at cathode; oxygen at anode",1,"At the cathode (negative electrode), H⁺ ions are reduced to H₂ gas. At the anode (positive electrode), OH⁻ ions are oxidised to produce O₂ gas."],
["A student calculates the number of moles of 4g of calcium (Ar = 40). What is the answer?","0.01 mol","0.1 mol","1 mol","4 mol",1,"Moles = mass ÷ molar mass = 4 ÷ 40 = 0.1 mol."],
["Which of the following correctly describes the mole concept?","One mole is 6.02 × 10²³ particles of any substance","One mole is 1 gram of any substance","One mole is the mass in grams equal to the atomic number","One mole only applies to gases",0,"One mole of any substance contains 6.02 × 10²³ (Avogadro's number) particles — atoms, molecules or ions."],
["A student reacts 2 mol of hydrogen with 1 mol of oxygen to produce water: 2H₂ + O₂ → 2H₂O. How many moles of water are produced?","1 mol","2 mol","3 mol","4 mol",1,"The balanced equation shows 2 mol H₂ reacts with 1 mol O₂ to produce 2 mol H₂O. Using 2 mol H₂ and 1 mol O₂ produces 2 mol H₂O."],
["A student titrates 25.0 cm³ of NaOH solution with 0.1 mol/L HCl. The endpoint is reached after adding 20.0 cm³ of HCl. What is the concentration of the NaOH solution?","0.08 mol/L","0.125 mol/L","0.1 mol/L","0.2 mol/L",0,"Moles HCl = 0.1 × 0.020 = 0.002 mol. NaOH + HCl → NaCl + H₂O (1:1 ratio), so moles NaOH = 0.002 mol. Concentration NaOH = 0.002 ÷ 0.025 = 0.08 mol/L."],
["Which of the following correctly describes the difference between an atom and an ion?","An atom has no protons; an ion does","An ion has a different number of protons to electrons; an atom has equal numbers","An atom is larger than an ion","Ions only form from non-metals",1,"An atom is electrically neutral (equal protons and electrons). An ion has gained or lost electrons, giving it a net positive or negative charge."],
["A student investigates the electrolysis of brine (sodium chloride solution). Which product is formed at the cathode?","Chlorine","Sodium","Hydrogen","Oxygen",2,"At the cathode, H⁺ ions from water are preferentially discharged (reduced) to form H₂ gas. Sodium ions remain in solution as they are harder to discharge than H⁺."],
["Which of the following correctly explains why the percentage yield of a reaction is often less than 100%?","The law of conservation of mass is violated","Reactions are always incomplete, products may be lost during separation, or side reactions occur","The molar mass calculations are always wrong","Catalysts reduce the yield",1,"Percentage yield is less than 100% due to incomplete reactions, loss of product during separation/purification, or competing side reactions that produce unwanted products."],
["A student calculates the empirical formula of a compound containing 40% carbon, 6.7% hydrogen and 53.3% oxygen by mass. What is the empirical formula?","CH₂O","C₂H₄O","CH₄O","C₂H₂O",0,"Divide by atomic masses: C = 40/12 = 3.33, H = 6.7/1 = 6.7, O = 53.3/16 = 3.33. Ratio C:H:O = 1:2:1. Empirical formula = CH₂O."],
// ── Organic Chemistry ─────────────────────────────────────────────────────
["A student burns a hydrocarbon in excess oxygen and collects the products. Which of the following correctly identifies the products of complete combustion?","Carbon monoxide and water","Carbon dioxide and water","Carbon and hydrogen","Carbon dioxide and hydrogen",1,"Complete combustion of a hydrocarbon in excess oxygen produces carbon dioxide (CO₂) and water (H₂O) only."],
["Which of the following correctly describes the difference between alkanes and alkenes?","Alkanes have a double bond; alkenes do not","Alkenes have at least one C=C double bond; alkanes have only single bonds","Alkanes are more reactive than alkenes","Alkenes cannot undergo combustion",1,"Alkenes contain at least one carbon-carbon double bond (C=C), making them unsaturated. Alkanes contain only single bonds and are saturated hydrocarbons."],
["A student adds bromine water to an unknown hydrocarbon. The bromine water is decolourised. What does this indicate?","The hydrocarbon is an alkane","The hydrocarbon is saturated","The hydrocarbon is an alkene (unsaturated)","The hydrocarbon is an alcohol",2,"Alkenes decolourise bromine water through an addition reaction across the C=C double bond. Alkanes do not react with bromine water under normal conditions."],
["Which of the following correctly describes addition polymerisation?","Small molecules (monomers) with double bonds join together to form a long chain polymer","Monomers join together releasing water","Polymers break down into monomers","Only natural polymers are formed by addition polymerisation",0,"In addition polymerisation, unsaturated monomers (containing C=C double bonds) react together. The double bond opens and monomers link to form a long chain with no by-products."],
["A student compares the viscosity and boiling points of different alkane fractions from crude oil. Which of the following correctly describes the trend?","Shorter chain alkanes have higher boiling points and greater viscosity","Longer chain alkanes have higher boiling points and greater viscosity","All alkanes have the same boiling point","Chain length has no effect on boiling point",1,"Longer alkane chains have greater van der Waals forces between molecules (more electrons, larger surface area), requiring more energy to separate — higher boiling points and greater viscosity."],
["Which of the following correctly describes fermentation?","Glucose is oxidised completely to CO₂ and water","Glucose is converted to ethanol and CO₂ by yeast in anaerobic conditions","Ethanol is converted to ethanoic acid","Glucose is polymerised to form starch",1,"Fermentation is the anaerobic conversion of glucose to ethanol and carbon dioxide by yeast enzymes. It is used in brewing and bread-making."],
["A student investigates cracking of a long-chain hydrocarbon. Which of the following correctly describes the products?","Only shorter alkanes are produced","Shorter alkanes and alkenes are produced","Only alkenes are produced","The hydrocarbon is converted to carbon and hydrogen",1,"Cracking breaks long-chain hydrocarbons into shorter, more useful molecules. The products include shorter alkanes and alkenes (which contain C=C double bonds)."],
["Which of the following correctly identifies the functional group of carboxylic acids?","–OH","–COOH","–CHO","–NH₂",1,"Carboxylic acids contain the –COOH (carboxyl) functional group. This group is responsible for their acidic properties as it can donate a proton (H⁺)."],
["A student reacts ethanol with ethanoic acid in the presence of a sulfuric acid catalyst. Which type of reaction is this and what is the organic product?","Addition reaction; ethane","Esterification; ethyl ethanoate","Fermentation; ethanol","Hydrolysis; ethanoic acid",1,"Esterification is the reaction between an alcohol and a carboxylic acid (with an acid catalyst) to produce an ester and water. Ethanol + ethanoic acid → ethyl ethanoate + water."],
["Which of the following correctly explains why plastics are difficult to dispose of?","Plastics are highly reactive","Most plastics are non-biodegradable — microorganisms cannot break down the long polymer chains","Plastics dissolve in water","Plastics are too heavy to landfill",1,"Most synthetic polymers have very long, stable carbon chains that microorganisms cannot break down. This makes them persist in the environment for hundreds of years."],
];

chemQ.forEach(([q,a,b,c,d,ai,exp],i)=>{
  chem.push({id:`MCQ-CHEM-Y910-${String(i+1).padStart(3,'0')}`,domain:"Chemistry",topic:["Atomic Structure","Chemical Bonding","Reactions and Energy","Electrochemistry","Organic Chemistry"][Math.floor(i/10)%5],difficulty:["Medium","Hard","Medium","Hard"][i%4],question:q,options:[a,b,c,d],answerIndex:ai,explanation:exp});
});

fs.writeFileSync('./chem-bank.json', JSON.stringify(chem, null, 2));
console.log(`Chemistry questions: ${chem.length}`);
