const fs = require('fs');
const more = [];
const q = [
// Biology: Human Body (20)
["A student measures the effect of increasing CO2 on breathing rate. Which receptor detects the change?","Stretch receptors in lungs","Chemoreceptors in the medulla and aortic arch detecting blood pH","Pressure receptors in the heart","Temperature receptors in the skin",1,"Chemoreceptors in the medulla oblongata and aortic/carotid bodies detect rising CO2 (falling blood pH). They signal the respiratory centre to increase breathing rate and depth to expel excess CO2."],
["Which of the following correctly explains why the left ventricle has a thicker wall than the right ventricle?","The left ventricle pumps blood to the lungs only","The left ventricle pumps blood around the entire body at high pressure; the right ventricle only pumps to the nearby lungs at lower pressure","The left ventricle is larger","The right ventricle pumps more blood",1,"The left ventricle must generate sufficient pressure to drive blood through the systemic circulation (entire body). The right ventricle only pumps blood to the lungs (pulmonary circulation), a much shorter distance requiring less pressure — hence thinner walls."],
["A student investigates the effect of smoking on lung function. Smokers have reduced FEV1 (forced expiratory volume). Which of the following correctly explains this?","Smoking increases lung capacity","Smoking damages alveoli (emphysema) and causes airway inflammation, reducing elastic recoil and increasing airway resistance","Smoking increases oxygen absorption","Smoking reduces mucus production",1,"Smoking causes emphysema (destruction of alveolar walls, reducing surface area and elastic recoil) and chronic bronchitis (airway inflammation and excess mucus). Both reduce the ability to expel air forcefully, lowering FEV1."],
["A student compares the concentration of urea in the renal artery, renal vein and urine. Which of the following correctly ranks them from highest to lowest urea concentration?","Renal artery > renal vein > urine","Urine > renal artery > renal vein","Renal vein > urine > renal artery","Renal artery > urine > renal vein",1,"Urea is concentrated in urine (highest). The renal artery carries blood with normal urea levels. The renal vein carries blood after urea has been filtered out — lowest urea concentration. So: urine > renal artery > renal vein."],
["Which of the following correctly describes the role of the hypothalamus in thermoregulation?","It produces sweat directly","It acts as the thermostat — detecting blood temperature and coordinating responses (sweating, shivering, vasodilation/vasoconstriction) to restore normal temperature","It stores glycogen for energy","It produces insulin",1,"The hypothalamus contains thermoreceptors that monitor blood temperature. When temperature deviates from the set point (37°C), it coordinates corrective responses via the nervous and endocrine systems — sweating and vasodilation to cool, shivering and vasoconstriction to warm."],
["A student investigates the effect of adrenaline on heart rate. Heart rate increases. Which of the following correctly explains the mechanism?","Adrenaline directly stimulates heart muscle fibres","Adrenaline binds to receptors on the sinoatrial node, increasing the rate of depolarisation and therefore heart rate","Adrenaline reduces blood viscosity","Adrenaline increases blood volume",1,"Adrenaline (epinephrine) binds to beta-adrenergic receptors on the sinoatrial node (the heart's pacemaker). This increases the rate of spontaneous depolarisation, increasing heart rate. It also increases force of contraction."],
["A student compares the structure of a motor neuron and a sensory neuron. Which of the following correctly describes a key difference?","Motor neurons are shorter than sensory neurons","Sensory neurons carry impulses from receptors to the CNS; motor neurons carry impulses from the CNS to effectors (muscles/glands)","Both carry impulses in the same direction","Sensory neurons have myelin; motor neurons do not",1,"Sensory (afferent) neurons transmit impulses from sensory receptors toward the CNS. Motor (efferent) neurons transmit impulses from the CNS to effectors. This directional difference reflects their distinct roles in the reflex arc and voluntary movement."],
["A student investigates the effect of insulin on blood glucose in a healthy person after a meal. Which of the following correctly describes the sequence of events?","Blood glucose falls → insulin released → glucose absorbed by cells","Blood glucose rises → pancreas releases insulin → cells absorb glucose → blood glucose returns to normal","Blood glucose rises → glucagon released → glycogen broken down","Blood glucose falls → glucagon released → cells absorb glucose",1,"After a meal, blood glucose rises. The pancreatic beta cells detect this and release insulin. Insulin stimulates cells to absorb glucose and the liver to convert glucose to glycogen (glycogenesis), returning blood glucose to normal — negative feedback."],
["Which of the following correctly explains why the small intestine is the primary site of nutrient absorption rather than the stomach?","The stomach is too acidic for absorption","The small intestine has villi and microvilli greatly increasing surface area, a rich blood supply, and appropriate pH for enzyme activity — all optimised for absorption","The stomach absorbs fats only","The small intestine produces more acid",1,"The small intestine is specialised for absorption: villi and microvilli increase surface area ~600-fold; each villus has capillaries (for glucose/amino acids) and lacteals (for fats); thin epithelium minimises diffusion distance; appropriate pH for digestive enzymes."],
["A student investigates the effect of exercise on lactic acid concentration in blood. Lactic acid rises sharply above the lactate threshold. Which of the following correctly explains what happens to lactic acid during recovery?","Lactic acid is excreted in urine","Lactic acid is transported to the liver where it is converted back to glucose (Cori cycle) or oxidised in aerobic respiration","Lactic acid evaporates from the lungs","Lactic acid is stored in muscle",1,"During recovery, lactic acid diffuses from muscles into blood and is transported to the liver. The liver converts lactic acid back to pyruvate and then to glucose (gluconeogenesis/Cori cycle), or it is oxidised in aerobic respiration. This is the 'oxygen debt' repayment."],
// Biology: Evolution (10)
["A student investigates the fossil record of horses over 55 million years. Early horses were small with multiple toes; modern horses are large with a single hoof. Which of the following correctly interprets this evidence?","Horses were created in their current form","The fossil record shows gradual morphological change over time consistent with evolution by natural selection in response to changing environments","Horses evolved randomly with no pattern","The fossil record is unreliable",1,"The horse fossil record is one of the best-documented examples of macroevolution. Progressive changes in size, leg structure and tooth morphology over 55 million years are consistent with natural selection adapting horses to changing grassland environments."],
["A student compares the embryos of fish, reptiles, birds and mammals. All show gill slits and tails at early stages. Which of the following correctly interprets this observation?","All these animals breathe through gills as adults","Shared embryonic features reflect common ancestry — early developmental pathways are conserved across vertebrates","Embryos are identical to adults","The observation is coincidental",1,"Comparative embryology reveals that vertebrate embryos share similar early developmental stages (pharyngeal arches, post-anal tail), reflecting their common ancestry. These conserved developmental pathways are evidence for evolution from a common vertebrate ancestor."],
["A student investigates genetic variation in a population of 500 beetles. A flood kills 490 beetles randomly, leaving 10 survivors. The survivors happen to be mostly one colour. Which evolutionary process does this illustrate?","Natural selection","Genetic drift (bottleneck effect) — random survival of a small sample causes allele frequencies to change by chance","Mutation","Gene flow",1,"The bottleneck effect is a form of genetic drift. When a population is drastically reduced by a random event, the survivors may not represent the original allele frequencies. The small surviving population has reduced genetic diversity and different allele frequencies by chance."],
["Which of the following correctly describes the concept of fitness in evolutionary biology?","The physical strength of an organism","Reproductive success — the ability to survive and produce viable offspring that carry the organism's genes","The speed of an organism","The size of an organism",1,"In evolutionary biology, fitness is defined as reproductive success — the relative ability of an organism to survive and pass its genes to the next generation. A 'fit' organism is not necessarily the strongest or fastest, but the one that leaves the most offspring."],
["A student investigates convergent evolution by comparing the wings of bats, birds and insects. All have wings for flight but different underlying structures. Which of the following correctly explains convergent evolution?","All winged animals share a recent common ancestor","Similar selection pressures (need for flight) independently produced similar functional structures in unrelated lineages","Wings are homologous structures","Convergent evolution only occurs in birds",1,"Convergent evolution occurs when unrelated organisms independently evolve similar traits in response to similar environmental pressures. Bat, bird and insect wings are analogous structures — similar function, different underlying anatomy — reflecting independent evolutionary solutions to the same challenge."],
// Chemistry: Physical Chemistry (20)
["A student investigates the effect of pressure on the solubility of CO2 in water. Solubility increases with pressure. Which law describes this relationship?","Boyle's law","Henry's law — the solubility of a gas in a liquid is proportional to the partial pressure of the gas above the liquid","Charles's law","Raoult's law",1,"Henry's law: at constant temperature, the amount of gas dissolved in a liquid is proportional to the partial pressure of that gas above the liquid. This explains why carbonated drinks release CO2 when opened (pressure drops)."],
["A student compares the pH of 0.1 mol/L hydrochloric acid and 0.1 mol/L ethanoic acid. HCl has pH ≈ 1; ethanoic acid has pH ≈ 3. Which of the following correctly explains this difference?","HCl has a higher molar mass","HCl is a strong acid that fully dissociates; ethanoic acid is a weak acid that only partially dissociates, producing fewer H⁺ ions at the same concentration","Ethanoic acid is more concentrated","HCl reacts with water differently",1,"Strong acids (HCl) fully dissociate: [H⁺] = 0.1 mol/L → pH = 1. Weak acids (CH₃COOH) partially dissociate: [H⁺] << 0.1 mol/L → pH > 1. At the same concentration, weak acids have higher pH (less acidic) than strong acids."],
["A student investigates the Born-Haber cycle for sodium chloride. Which of the following correctly describes the lattice enthalpy?","Energy released when gaseous ions form a solid ionic lattice","Energy required to atomise sodium metal","Energy released when sodium loses an electron","Energy required to dissociate chlorine gas",0,"Lattice enthalpy is the energy released when gaseous ions come together to form one mole of solid ionic lattice. It reflects the strength of ionic bonding — higher lattice enthalpy means stronger ionic bonds and higher melting point."],
["A student measures the enthalpy of combustion of methane: CH₄ + 2O₂ → CO₂ + 2H₂O. ΔH = −890 kJ/mol. Which of the following correctly describes this value?","890 kJ is absorbed per mole of methane burned","890 kJ is released per mole of methane burned — the reaction is exothermic","The reaction is endothermic","890 kJ is the activation energy",1,"A negative ΔH indicates an exothermic reaction — energy is released to the surroundings. Combustion of methane releases 890 kJ per mole. The products (CO₂ and H₂O) have lower energy than the reactants."],
["A student investigates Hess's law. The enthalpy change for a reaction is the same regardless of the route taken. Which of the following correctly explains the basis of Hess's law?","Enthalpy depends on the pathway","Enthalpy is a state function — it depends only on the initial and final states, not the route taken","Hess's law only applies to combustion reactions","Enthalpy changes are always positive",1,"Hess's law is a consequence of enthalpy being a state function. The total enthalpy change depends only on the energies of reactants and products, not on the intermediate steps. This allows calculation of enthalpy changes for reactions that cannot be measured directly."],
["A student compares bond energies: C-H (413 kJ/mol), C=C (614 kJ/mol), C-C (347 kJ/mol), H-H (436 kJ/mol). For the hydrogenation of ethene: C₂H₄ + H₂ → C₂H₆, which of the following correctly calculates the enthalpy change?","Bonds broken: C=C + H-H = 614 + 436 = 1050 kJ; Bonds formed: C-C + 2(C-H) = 347 + 826 = 1173 kJ; ΔH = 1050 − 1173 = −123 kJ/mol","Bonds broken: C-C + H-H = 347 + 436 = 783 kJ; Bonds formed: C=C + 2(C-H) = 614 + 826 = 1440 kJ; ΔH = +657 kJ/mol","ΔH = +123 kJ/mol","ΔH = 0 kJ/mol",0,"ΔH = energy in (bonds broken) − energy out (bonds formed). Breaking C=C (614) + H-H (436) = 1050 kJ. Forming C-C (347) + 2×C-H (2×413=826) = 1173 kJ. ΔH = 1050 − 1173 = −123 kJ/mol (exothermic)."],
// Physics: Mechanics extended (20)
["A student launches a projectile horizontally from a cliff 20 m high. Using g = 10 m/s², how long does it take to reach the ground?","1 s","2 s","4 s","0.5 s",1,"Vertical motion: h = ½gt². 20 = ½ × 10 × t². t² = 4. t = 2 s. Horizontal velocity does not affect the time to fall."],
["A student investigates circular motion. A ball on a string moves in a horizontal circle. Which of the following correctly describes the direction of the centripetal force?","Tangential to the circle","Away from the centre (centrifugal)","Toward the centre of the circle","Vertically downward",2,"Centripetal force always acts toward the centre of the circular path. It is provided by the tension in the string. Without this inward force, the ball would travel in a straight line (Newton's first law)."],
["A student measures the power output of a student climbing stairs. The student (mass 60 kg) climbs 3 m in 6 seconds. What is the power output? (g = 10 m/s²)","30 W","100 W","300 W","600 W",2,"Work done = mgh = 60 × 10 × 3 = 1800 J. Power = work/time = 1800/6 = 300 W."],
["A student investigates the conservation of energy on a roller coaster. At the top of a loop (height 10 m), the speed is 5 m/s. What is the speed at the bottom? (g = 10 m/s², ignore friction)","10 m/s","15 m/s","5 m/s","20 m/s",1,"Energy conservation: ½mv²_bottom = ½mv²_top + mgh. v²_bottom = v²_top + 2gh = 25 + 2×10×10 = 225. v_bottom = 15 m/s."],
["A student investigates the relationship between pressure and volume of a gas at constant temperature. Doubling the pressure halves the volume. Which law describes this?","Charles's law","Boyle's law — at constant temperature, pressure and volume are inversely proportional (PV = constant)","Gay-Lussac's law","Avogadro's law",1,"Boyle's law: P₁V₁ = P₂V₂ at constant temperature. Pressure and volume are inversely proportional. Doubling pressure halves volume. This reflects the increased frequency of molecular collisions with the container walls at smaller volume."],
// Physics: Electricity extended (10)
["A student investigates the charging of a capacitor through a resistor. The time constant τ = RC. With R = 10 kΩ and C = 100 μF, what is the time constant?","1 s","0.1 s","10 s","0.01 s",0,"τ = RC = 10×10³ × 100×10⁻⁶ = 10⁴ × 10⁻⁴ = 1 s. After one time constant, the capacitor has charged to approximately 63% of the supply voltage."],
["A student measures the resistance of a wire at different temperatures. Resistance increases with temperature. Which of the following correctly explains this for a metallic conductor?","More electrons are available at higher temperatures","Higher temperature increases lattice ion vibration, increasing the frequency of collisions between electrons and ions, impeding electron flow","Resistance decreases with temperature in metals","Higher temperature reduces electron density",1,"In metallic conductors, resistance increases with temperature because thermal energy causes lattice ions to vibrate more vigorously. This increases the frequency of collisions between conduction electrons and lattice ions, impeding electron flow and increasing resistance."],
["A student builds a potential divider circuit with two resistors (R1 = 4 kΩ, R2 = 6 kΩ) connected to a 10 V supply. What is the voltage across R2?","4 V","6 V","10 V","2 V",1,"Voltage divider: V_R2 = V_supply × R2/(R1+R2) = 10 × 6/(4+6) = 10 × 0.6 = 6 V."],
// Earth Science: Geology extended (10)
["A student analyses the composition of Earth's layers using seismic wave data. S-waves do not pass through the outer core. Which of the following correctly explains this?","The outer core is solid","S-waves (transverse waves) cannot travel through liquids — the outer core is liquid iron and nickel","The outer core absorbs all waves","S-waves travel faster in liquids",1,"S-waves are transverse waves that require a rigid medium to propagate — they cannot travel through liquids. The fact that S-waves do not pass through the outer core is evidence that it is liquid (molten iron-nickel alloy)."],
["A student investigates the rate of weathering of limestone in different environments. Weathering is fastest in warm, wet, acidic conditions. Which of the following correctly explains this?","Limestone is softer in warm conditions","Warm temperatures increase reaction rates; water provides the medium for chemical reactions; acid (carbonic acid from dissolved CO2) reacts with calcium carbonate, dissolving the limestone","Limestone absorbs more water in warm conditions","Cold conditions accelerate chemical weathering",1,"Chemical weathering of limestone (CaCO₃) by carbonic acid (H₂CO₃): CaCO₃ + H₂CO₃ → Ca(HCO₃)₂. Higher temperature increases reaction rate; more rainfall provides more water and carbonic acid; acidic conditions (lower pH) increase the concentration of H⁺ ions attacking the carbonate."],
["A student compares the age of rocks at a mid-ocean ridge and 500 km away. Rocks at the ridge are youngest; rocks 500 km away are oldest. Which of the following correctly explains this pattern?","Older rocks sink to the ridge","New oceanic crust is continuously created at the ridge by seafloor spreading; older crust moves away from the ridge over time","Rocks at the ridge are heated and rejuvenated","The pattern is random",1,"Seafloor spreading: magma erupts at mid-ocean ridges, solidifies and forms new oceanic crust. As new material is added, older crust is pushed away from the ridge. Radiometric dating confirms that oceanic crust age increases with distance from the ridge."],
// Scientific Method extended (10)
["A student investigates whether a new fertiliser increases crop yield. They grow 20 plants with the fertiliser and 20 without. The mean yield with fertiliser is 15% higher. Which of the following is the most appropriate next step before concluding the fertiliser is effective?","Immediately recommend the fertiliser","Apply a statistical test (e.g. t-test) to determine whether the difference is statistically significant or could be due to chance","Repeat with only 5 plants","Conclude the fertiliser is ineffective",1,"Statistical analysis determines whether an observed difference is likely to be real or due to random variation. A t-test compares means and calculates a p-value. If p < 0.05, the difference is statistically significant and unlikely to be due to chance alone."],
["A student measures the extension of a spring 10 times and gets a mean of 4.5 cm with a standard deviation of 0.2 cm. Which of the following correctly describes what the standard deviation tells us?","The range of all measurements","The spread of measurements around the mean — smaller standard deviation indicates greater precision","The accuracy of the measurements","The systematic error",1,"Standard deviation measures the spread of data around the mean. A small standard deviation indicates measurements are clustered closely (precise). A large standard deviation indicates high variability. It does not indicate accuracy (closeness to the true value)."],
["A student investigates the effect of light intensity on plant growth. They use artificial lights at 5 different intensities and measure stem height after 4 weeks. Which of the following correctly identifies a limitation of this experiment?","The experiment has too many variables","Using artificial light may not replicate the full spectrum of natural sunlight, potentially affecting results; also, 4 weeks may not be sufficient to observe long-term effects","The experiment has no independent variable","Stem height is not a valid measure of growth",1,"Limitations are factors that reduce the validity or generalisability of results. Artificial light differs from natural sunlight in spectral composition. Short duration may miss long-term effects. Identifying limitations is essential for evaluating experimental design."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const domains=['Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Biology','Chemistry','Chemistry','Chemistry','Chemistry','Chemistry','Chemistry','Physics','Physics','Physics','Physics','Physics','Physics','Physics','Physics','Physics','Physics','Physics','Earth Science','Earth Science','Earth Science','Earth Science','Earth Science','Earth Science','Earth Science'];
  const topics=['Human Body','Human Body','Human Body','Human Body','Human Body','Human Body','Human Body','Human Body','Human Body','Human Body','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Forces and Motion','Forces and Motion','Forces and Motion','Forces and Motion','Forces and Motion','Electricity and Magnetism','Electricity and Magnetism','Electricity and Magnetism','Geology and Climate','Geology and Climate','Geology and Climate','Scientific Method','Scientific Method','Scientific Method'];
  more.push({id:`MCQ-MORE-Y910-${String(i+1).padStart(3,'0')}`,domain:domains[i]||'Science',topic:topics[i]||'Science',difficulty:i%2===0?'Medium':'Hard',question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./more-bank.json', JSON.stringify(more,null,2));
console.log(`More batch: ${more.length}`);
