const fs = require('fs');
const bio2 = [];

const q = [
// ── Evolution & Classification ────────────────────────────────────────────
["A population of beetles lives on dark soil. Most are dark-coloured; a few are light-coloured. Birds preferentially eat light beetles. After 20 generations, nearly all beetles are dark. Which process explains this?","Lamarckian inheritance — beetles darkened their colour in response to predation","Natural selection — dark beetles had higher survival and reproductive rates, increasing the frequency of dark alleles","Genetic drift — random chance eliminated light beetles","Mutation — all light beetles mutated to dark",1,"Natural selection: pre-existing variation (dark/light colour) interacted with selection pressure (bird predation). Dark beetles survived and reproduced more, passing dark alleles to offspring. Over generations, dark allele frequency increased."],
["Two populations of a bird species are separated by a mountain range for 50 000 years. When the range disappears, the two populations can no longer interbreed. Which of the following has occurred?","Sympatric speciation","Allopatric speciation — geographic isolation led to reproductive isolation","Genetic drift only","Convergent evolution",1,"Allopatric speciation: geographic isolation (mountain range) prevented gene flow. Each population accumulated different mutations and adaptations. After sufficient divergence, reproductive isolation was complete — they became separate species."],
["A student compares the forelimb bones of a human arm, a whale flipper and a bat wing. All contain the same bones (humerus, radius, ulna) arranged differently. What does this indicate?","Convergent evolution — similar environments produced similar structures","Analogous structures with no common ancestry","Homologous structures indicating common ancestry","The structures have identical functions",2,"Homologous structures share the same underlying anatomy due to common ancestry, even if they serve different functions. This is evidence for divergent evolution from a common ancestor."],
["A student analyses the amino acid sequence of cytochrome c (a protein) in five species. Species A and B differ by 1 amino acid; A and C differ by 12. What can be concluded?","A and C are more closely related than A and B","A and B share a more recent common ancestor than A and C","All species are equally related","Amino acid sequences are unrelated to evolution",1,"Fewer differences in protein sequences indicate more recent divergence. A and B (1 difference) share a more recent common ancestor than A and C (12 differences). Molecular evidence supports phylogenetic relationships."],
["Which of the following correctly describes the role of mutations in evolution?","Mutations are always harmful and reduce fitness","Mutations provide the heritable variation upon which natural selection acts","Mutations are directed toward beneficial outcomes","Mutations only occur in somatic cells",1,"Mutations are random changes in DNA sequence. Most are neutral or harmful, but occasionally a mutation increases fitness. Natural selection then acts on this heritable variation, potentially increasing the frequency of beneficial alleles."],
["A student studies a population of moths over 50 years. The frequency of a melanic (dark) allele increased from 5% to 85% during industrialisation, then decreased to 30% after clean air legislation. Which of the following best explains this pattern?","Genetic drift caused random allele frequency changes","Natural selection: dark moths were camouflaged on soot-covered trees during industrialisation; clean air restored lichen, favouring pale moths","Mutation rates increased during industrialisation","Lamarckian inheritance caused moths to change colour",1,"Industrial melanism: soot killed lichens, darkening tree bark. Dark moths were better camouflaged from predators, increasing their survival. After clean air legislation, lichens returned, pale moths became better camouflaged again — selection reversed."],
["Which of the following correctly distinguishes a species from a genus in the Linnaean classification system?","A genus contains only one species","A genus is a group of closely related species; a species is a group of organisms that can interbreed and produce fertile offspring","Species is a broader category than genus","Genus and species are the same level",1,"In Linnaean taxonomy, a genus groups closely related species. A species is defined as a group of organisms that can interbreed naturally and produce fertile offspring. The binomial name uses genus + species (e.g. Homo sapiens)."],
["A student investigates the Hardy-Weinberg principle. In a population of 1000 individuals, 360 show the recessive phenotype (aa). What is the frequency of the recessive allele (q)?","0.36","0.6","0.4","0.16",1,"Frequency of aa = q² = 360/1000 = 0.36. Therefore q = √0.36 = 0.6."],
["Which of the following is NOT a condition required for Hardy-Weinberg equilibrium?","Large population size","Random mating","Natural selection acting on the trait","No migration into or out of the population",2,"Hardy-Weinberg equilibrium requires: large population, random mating, no mutation, no migration, and NO natural selection. If selection acts on the trait, allele frequencies will change and equilibrium is not maintained."],
["A student compares the DNA of a chimpanzee and a human. They share approximately 98.7% of their DNA sequence. Which of the following is the most appropriate interpretation?","Humans evolved from chimpanzees","Humans and chimpanzees share a recent common ancestor and diverged relatively recently in evolutionary time","The 1.3% difference is insignificant","Chimpanzees and humans are the same species",1,"High DNA similarity indicates recent common ancestry. Humans and chimpanzees diverged from a common ancestor approximately 6-7 million years ago. The 1.3% difference, while small, accounts for significant phenotypic differences due to regulatory gene changes."],
// ── Plants & Photosynthesis ───────────────────────────────────────────────
["A student investigates the rate of photosynthesis in pondweed at different light intensities. At low light intensity, doubling the light doubles the rate. At high light intensity, doubling the light has no effect. Which of the following correctly explains the plateau?","The plant runs out of chlorophyll","Light is no longer the limiting factor — CO2 concentration or temperature is now limiting","The plant is producing too much oxygen","The water becomes too warm",1,"At low light intensity, light is the limiting factor. At the plateau, another factor (CO2 concentration or temperature) becomes limiting. Increasing light further cannot increase the rate until the new limiting factor is addressed."],
["A student compares the rate of transpiration in a plant on a humid day versus a dry day. Transpiration is faster on the dry day. Which of the following correctly explains this?","Stomata open wider on dry days","The concentration gradient for water vapour between the leaf and air is steeper on a dry day, increasing the rate of diffusion","Plants produce more water on dry days","Temperature is always higher on dry days",1,"Transpiration rate depends on the water vapour concentration gradient between the leaf air spaces (saturated) and the surrounding air. On a dry day, the air has lower humidity, creating a steeper gradient and faster diffusion of water vapour out of the leaf."],
["A student investigates the effect of CO2 concentration on photosynthesis rate. Results show rate increases then plateaus. A second experiment at higher temperature shows a higher plateau. Which of the following correctly explains why temperature affects the plateau?","Higher temperature increases CO2 concentration","Higher temperature increases the activity of Calvin cycle enzymes, so they can process more CO2 before becoming saturated","Higher temperature increases chlorophyll production","Higher temperature reduces the limiting effect of light",1,"The Calvin cycle (light-independent reactions) is enzyme-controlled. Higher temperature (up to the optimum) increases enzyme activity, allowing faster processing of CO2. This raises the plateau because the enzyme limitation is reduced."],
["Which of the following correctly describes the role of the xylem in a plant?","Transports sugars from leaves to roots","Transports water and dissolved minerals from roots to leaves","Stores starch in the stem","Produces new cells at the shoot tip",1,"Xylem is a vascular tissue that transports water and dissolved mineral ions from the roots upward through the stem to the leaves. Water movement is driven by transpiration pull (cohesion-tension mechanism)."],
["A student investigates the effect of removing leaves from a plant on the rate of water uptake. Water uptake decreases significantly. Which of the following best explains this?","Roots absorb less water without leaves","Leaves are the main site of transpiration; removing them eliminates the transpiration pull that drives water uptake","The stem cannot transport water without leaves","Photosynthesis drives water uptake directly",1,"Transpiration from leaves creates a tension (negative pressure) that pulls water up through the xylem — the cohesion-tension mechanism. Removing leaves eliminates transpiration, removing the driving force for water uptake."],
["A student tests a variegated leaf (green and white sections) for starch using iodine solution. Only the green sections turn blue-black. Which of the following correctly explains this result?","White sections contain more starch","Green sections contain chlorophyll and can photosynthesise, producing starch; white sections lack chlorophyll","Iodine only reacts with green pigments","White sections are dead",1,"Starch is produced by photosynthesis. Green sections contain chlorophyll and can photosynthesise, producing glucose that is converted to starch. White sections lack chlorophyll and cannot photosynthesise, so no starch is produced."],
["Which of the following correctly describes the process of translocation in plants?","Movement of water from roots to leaves through xylem","Movement of sugars (sucrose) from leaves to other parts of the plant through phloem","Movement of minerals from soil into root hair cells","Movement of oxygen from leaves to roots",1,"Translocation is the transport of dissolved organic compounds (mainly sucrose) through the phloem. It is bidirectional — from source (leaves where photosynthesis occurs) to sink (roots, fruits, growing tips)."],
["A student investigates the effect of light colour on the rate of photosynthesis. Red and blue light produce the highest rates; green light produces the lowest. Which of the following correctly explains this?","Chlorophyll absorbs red and blue light most strongly; it reflects green light","Green light is more energetic than red light","Chlorophyll absorbs all wavelengths equally","Red light has the longest wavelength and most energy",0,"Chlorophyll absorbs red (~680 nm) and blue (~430 nm) light most strongly for use in photosynthesis. Green light (~550 nm) is mostly reflected, which is why plants appear green. Reflected light cannot drive photosynthesis."],
["A student investigates stomatal density on the upper and lower surfaces of a leaf. The lower surface has significantly more stomata. Which of the following correctly explains this adaptation?","Upper surface needs more stomata for light absorption","Lower surface stomata reduce water loss by avoiding direct sunlight while still allowing gas exchange","Upper surface has more chloroplasts","Lower surface is thicker",1,"Stomata on the lower (abaxial) surface are shaded from direct sunlight, reducing the temperature and water vapour gradient, which helps minimise water loss. Gas exchange can still occur effectively through the lower surface."],
["Which of the following correctly describes the role of guard cells in regulating gas exchange?","Guard cells produce glucose by photosynthesis only","Guard cells change shape by gaining or losing water, opening or closing the stomatal pore","Guard cells are dead cells that provide structural support","Guard cells produce oxygen directly",1,"Guard cells are kidney-shaped cells surrounding each stoma. When they absorb water by osmosis, they become turgid and bow outward, opening the pore. When they lose water, they become flaccid and the pore closes, reducing water loss."],
// ── Microbiology & Disease ────────────────────────────────────────────────
["A student investigates the effect of temperature on bacterial growth rate. Growth rate increases up to 37°C then falls sharply above 45°C. Which of the following correctly explains the sharp decline above 45°C?","Bacteria run out of nutrients above 45°C","Enzymes essential for bacterial metabolism denature above their optimum temperature","Bacteria reproduce faster above 45°C","The growth medium becomes toxic above 45°C",1,"Bacterial enzymes have an optimum temperature (~37°C for human pathogens). Above this, the enzyme's tertiary structure is disrupted (denaturation), preventing metabolic reactions essential for growth and reproduction."],
["A student cultures bacteria on an agar plate and places antibiotic-soaked discs on the surface. After incubation, clear zones (zones of inhibition) appear around some discs. Which of the following correctly interprets a large zone of inhibition?","The bacterium is resistant to that antibiotic","The bacterium is highly sensitive to that antibiotic — it cannot grow in the presence of that concentration","The antibiotic promotes bacterial growth","The zone indicates the antibiotic has been absorbed",1,"A large zone of inhibition indicates the antibiotic diffuses outward and kills or inhibits bacteria over a wide area — the bacterium is sensitive (susceptible) to that antibiotic. No zone indicates resistance."],
["Which of the following correctly describes how viruses differ from bacteria?","Viruses are larger than bacteria","Viruses are non-living particles that require a host cell to replicate; bacteria are living cells that can reproduce independently","Bacteria require a host cell to replicate","Viruses can be treated with antibiotics",1,"Viruses are acellular (non-living) particles consisting of nucleic acid (DNA or RNA) enclosed in a protein coat. They cannot reproduce independently — they must hijack host cell machinery. Bacteria are living prokaryotic cells that reproduce by binary fission."],
["A student investigates the spread of a respiratory infection in a school. Cases cluster in classrooms with poor ventilation. Which of the following correctly identifies the mode of transmission?","Vector-borne transmission","Airborne/droplet transmission — infectious particles spread through the air","Direct contact transmission","Foodborne transmission",1,"Respiratory infections spread via droplets or aerosols expelled when infected individuals breathe, cough or sneeze. Poor ventilation allows infectious particles to accumulate, increasing transmission risk."],
["Which of the following correctly explains why completing a full course of antibiotics is important?","To ensure the patient feels better","To eliminate all bacteria, including slower-growing ones that survive initial treatment, preventing resistance developing from survivors","To prevent the antibiotic from being wasted","To increase the patient's immunity",1,"Stopping antibiotics early leaves slower-growing or partially resistant bacteria alive. These survivors can reproduce and pass on resistance genes. Completing the full course ensures all bacteria are eliminated, reducing the risk of resistance developing."],
["A student investigates the effectiveness of different hand-washing techniques in removing bacteria. Which of the following would be the most appropriate control?","Washing hands with hot water only","Not washing hands at all — to compare bacterial counts before and after washing","Using the most effective technique as the control","Using distilled water as the control",1,"A control group (no washing) establishes the baseline bacterial count. Comparing washed hands to unwashed hands allows the student to determine whether washing actually reduces bacterial counts and by how much."],
["Which of the following correctly describes the mechanism by which vaccines provide immunity?","Vaccines directly kill pathogens in the body","Vaccines introduce antigens that stimulate the immune system to produce memory cells, enabling a faster response on future exposure","Vaccines provide antibodies directly to the patient","Vaccines work by increasing body temperature",1,"Vaccines contain antigens (weakened/killed pathogens or their components). The immune system responds by producing antibodies and memory B and T cells. On future exposure to the real pathogen, memory cells enable a rapid, strong secondary immune response."],
["A student investigates the growth of bacteria using a serial dilution technique. A 10⁻⁴ dilution produces 150 colonies on an agar plate. What is the original bacterial concentration?","150 bacteria/mL","1.5 × 10⁶ bacteria/mL","1.5 × 10⁴ bacteria/mL","150 × 10⁴ bacteria/mL",1,"Colony count × dilution factor = original concentration. 150 × 10⁴ = 1.5 × 10⁶ bacteria/mL. Each colony on the plate represents one bacterium (colony forming unit) from the diluted sample."],
["Which of the following correctly describes the difference between a bacteriostatic and a bactericidal antibiotic?","Both kill bacteria","Bacteriostatic antibiotics inhibit bacterial growth; bactericidal antibiotics kill bacteria","Bactericidal antibiotics inhibit growth; bacteriostatic antibiotics kill bacteria","Both only inhibit growth",1,"Bacteriostatic antibiotics (e.g. tetracycline) inhibit bacterial reproduction without killing them, relying on the immune system to clear the infection. Bactericidal antibiotics (e.g. penicillin) directly kill bacteria by disrupting cell wall synthesis or other vital processes."],
["A student investigates the transmission of malaria. Which of the following correctly identifies the vector and causative agent?","Vector: mosquito; causative agent: Plasmodium (a protozoan)","Vector: Plasmodium; causative agent: mosquito","Vector: mosquito; causative agent: a virus","Vector: rat; causative agent: Plasmodium",0,"Malaria is caused by Plasmodium (a protozoan parasite). The Anopheles mosquito is the vector — it transmits Plasmodium to humans during a blood meal. The mosquito itself does not cause the disease."],
["Which of the following correctly explains why HIV is difficult to treat with a single antiviral drug?","HIV is a bacterium","HIV mutates rapidly, producing variants that may be resistant to a single drug; combination therapy (HAART) targets multiple stages of the viral life cycle","HIV cannot be detected by the immune system","HIV only infects red blood cells",1,"HIV has a high mutation rate due to error-prone reverse transcriptase. Single-drug therapy quickly selects for resistant mutants. HAART (Highly Active Antiretroviral Therapy) uses multiple drugs targeting different viral proteins, making it much harder for resistance to develop."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const topics = ['Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Evolution and Classification','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease','Microbiology and Disease'];
  bio2.push({id:`MCQ-BIO2-Y910-${String(i+1).padStart(3,'0')}`,domain:"Biology",topic:topics[i],difficulty:i%2===0?"Medium":"Hard",question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./bio2-bank.json', JSON.stringify(bio2,null,2));
console.log(`Bio2 questions: ${bio2.length}`);
