const fs = require('fs');
const last = [];

const q = [
// ── Biology: Cell Biology (20q) ───────────────────────────────────────────
["A student places a plant cell in distilled water. The cell becomes turgid but does not burst. Which structure prevents the cell from bursting?","Cell membrane","Cell wall","Vacuole","Nucleus",1,"The rigid cellulose cell wall exerts a wall pressure (turgor pressure) that counteracts the osmotic pressure driving water in. This prevents the cell from bursting, unlike animal cells which lack a cell wall."],
["A student compares the rate of active transport and diffusion when a cell is treated with a metabolic poison that blocks ATP production. Which process is most affected?","Diffusion","Active transport","Osmosis","Facilitated diffusion",1,"Active transport requires ATP to move substances against their concentration gradient. Blocking ATP production stops active transport. Diffusion, osmosis and facilitated diffusion are passive processes that do not require ATP."],
["During which stage of the cell cycle is the DNA content of a cell doubled?","G1 phase","S phase","G2 phase","M phase",1,"DNA replication occurs during the S (synthesis) phase of interphase. Each chromosome is copied, doubling the DNA content from 2n to 4n before mitosis begins."],
["A student investigates the effect of cyanide (which blocks mitochondrial function) on a cell. Which process would be most immediately affected?","Diffusion of oxygen","Active transport of glucose","Osmosis of water","Passive diffusion of CO2",1,"Cyanide blocks the electron transport chain in mitochondria, stopping ATP synthesis. Active transport depends entirely on ATP, so it would be most immediately and severely affected."],
["A student examines a cell under an electron microscope and observes many ribosomes attached to a membrane network. Which organelle is this?","Smooth endoplasmic reticulum","Golgi apparatus","Rough endoplasmic reticulum","Lysosome",2,"Rough endoplasmic reticulum (rough ER) is characterised by ribosomes studded on its membrane surface. These ribosomes synthesise proteins that are threaded into the ER lumen for processing and transport."],
["A student measures the rate of photosynthesis and respiration in a leaf at different light intensities. At the light compensation point, which of the following is true?","Only photosynthesis occurs","Only respiration occurs","The rate of photosynthesis equals the rate of respiration — net gas exchange is zero","Photosynthesis rate is double respiration rate",2,"The light compensation point is the light intensity at which CO2 fixed by photosynthesis exactly equals CO2 released by respiration. Net gas exchange is zero — the plant neither gains nor loses carbon."],
["A student investigates the effect of increasing substrate concentration on enzyme activity. The rate increases then plateaus. Which of the following correctly explains the plateau?","The substrate denatures at high concentration","All enzyme active sites are occupied (enzyme is saturated) — adding more substrate cannot increase rate until more enzyme is added","The temperature increases at high substrate concentration","The pH changes at high substrate concentration",1,"At the plateau, all enzyme active sites are occupied with substrate molecules. The enzyme is working at maximum rate (Vmax). Adding more substrate has no effect because there are no free active sites available."],
["A student compares prokaryotic and eukaryotic cells. Which of the following is found in eukaryotic cells but NOT in prokaryotic cells?","Ribosomes","Cell membrane","Membrane-bound nucleus","DNA",2,"Eukaryotic cells have a membrane-bound nucleus containing their DNA. Prokaryotic cells lack a nuclear membrane — their DNA floats freely in the cytoplasm as a circular chromosome."],
["A student investigates osmosis using dialysis tubing filled with concentrated sucrose solution, placed in distilled water. The tubing swells. Which of the following correctly explains this?","Sucrose moves out of the tubing","Water moves into the tubing by osmosis down its concentration gradient (from high water potential to low water potential)","The tubing produces water","Sucrose breaks down into water",1,"Osmosis: water moves from high water potential (dilute solution/distilled water) to low water potential (concentrated sucrose) across the semi-permeable dialysis membrane. Water enters the tubing, causing it to swell."],
["A student investigates the effect of temperature on membrane permeability using beetroot cells. At higher temperatures, more red pigment leaks out. Which of the following correctly explains this?","Red pigment is produced faster at high temperatures","Higher temperatures increase the fluidity of the phospholipid bilayer and can denature membrane proteins, increasing permeability","Red pigment dissolves in water at high temperatures","The cell wall breaks down at high temperatures",1,"The phospholipid bilayer becomes more fluid at higher temperatures, and membrane proteins may denature. Both effects increase membrane permeability, allowing the red pigment (betalain) to leak out of the vacuole and cell more readily."],
// ── Biology: Genetics extended (20q) ─────────────────────────────────────
["A student investigates the inheritance of eye colour. Brown (B) is dominant over blue (b). Two brown-eyed parents have a blue-eyed child. What is the probability their next child will have brown eyes?","25%","50%","75%","100%",2,"Both parents must be Bb (carriers of blue). Bb × Bb gives 1BB:2Bb:1bb. Probability of brown eyes (BB or Bb) = 3/4 = 75%."],
["A student analyses a DNA sequence and finds a mutation where one base is substituted for another, resulting in a different amino acid. What type of mutation is this?","Silent mutation","Missense mutation","Nonsense mutation","Frameshift mutation",1,"A missense mutation is a base substitution that changes one amino acid to a different amino acid. This may alter protein function depending on the location and chemical properties of the substituted amino acid."],
["A student investigates sex-linked inheritance. A colour-blind father (X^b Y) and a carrier mother (X^B X^b) have children. What proportion of their daughters will be colour blind?","0%","25%","50%","100%",2,"Daughters receive X from father (X^b) and X from mother (X^B or X^b). Possible daughter genotypes: X^B X^b (carrier) or X^b X^b (colour blind) — 50% of daughters will be colour blind."],
["A student compares the DNA sequences of a gene in two populations of the same species that have been geographically isolated for 10 000 years. The sequences differ by 3%. Which of the following correctly interprets this finding?","The populations are different species","Mutations have accumulated independently in each population since isolation; the 3% difference reflects genetic divergence but does not necessarily indicate speciation","The populations cannot interbreed","3% difference means the populations are identical",1,"Geographic isolation prevents gene flow. Mutations accumulate independently in each population. The 3% sequence difference reflects genetic divergence over 10 000 years. Whether they have speciated depends on whether reproductive isolation has developed — sequence difference alone is insufficient to determine this."],
["A student investigates the effect of UV radiation on bacterial DNA. UV causes thymine dimers (adjacent thymine bases bonding together). Which of the following correctly explains why this is harmful?","Thymine dimers increase mutation rate beneficially","Thymine dimers distort the DNA double helix, blocking replication and transcription, potentially causing cell death or cancer if repair mechanisms fail","UV radiation only affects RNA","Thymine dimers strengthen DNA",1,"UV radiation causes covalent bonds to form between adjacent thymine bases (thymine dimers). These distort the DNA helix, blocking DNA polymerase during replication and RNA polymerase during transcription. If repair mechanisms (e.g. nucleotide excision repair) fail, mutations accumulate, potentially causing cancer."],
// ── Chemistry: Quantitative & Organic extended (20q) ─────────────────────
["A student burns 0.46 g of ethanol (C₂H₅OH, Mr=46) completely in oxygen. How many moles of CO₂ are produced? (C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O)","0.01 mol","0.02 mol","0.03 mol","0.04 mol",1,"Moles ethanol = 0.46/46 = 0.01 mol. From equation, 1 mol ethanol produces 2 mol CO₂. So 0.01 × 2 = 0.02 mol CO₂."],
["A student investigates the reaction of alcohols with sodium. Ethanol reacts slowly; water reacts vigorously. Which of the following correctly explains why ethanol is less reactive than water with sodium?","Ethanol has a higher boiling point","The O-H bond in ethanol is less polar than in water due to the electron-donating ethyl group, making the hydrogen less easily removed as H⁺","Ethanol is a larger molecule","Sodium does not react with ethanol",1,"In water, the O-H bond is highly polar (oxygen is bonded to two H atoms). In ethanol, the ethyl group (C₂H₅-) donates electron density to oxygen, reducing the polarity of the O-H bond and making the hydrogen less acidic — sodium reacts more slowly."],
["A student compares the structures of glucose and fructose. Both have the molecular formula C₆H₁₂O₆ but different structures. What term describes this relationship?","Isotopes","Isomers","Allotropes","Polymers",1,"Glucose and fructose are structural isomers — they have the same molecular formula (C₆H₁₂O₆) but different structural arrangements of atoms. Glucose is an aldose (aldehyde group); fructose is a ketose (ketone group)."],
["A student investigates the hydration of ethene: C₂H₄ + H₂O → C₂H₅OH. This reaction requires a phosphoric acid catalyst and high temperature and pressure. Which type of reaction is this?","Elimination","Substitution","Addition","Condensation",2,"Hydration of ethene is an addition reaction — water (H₂O) adds across the C=C double bond of ethene to produce ethanol. The double bond opens and both atoms of water are incorporated into the product."],
["A student analyses the mass spectrum of an organic compound. The molecular ion peak appears at m/z = 46. The compound contains C, H and O only. Which of the following could be the molecular formula?","CH₂O₂","C₂H₆O","C₂H₄O","CH₄O₂",1,"Mr = 46. C₂H₆O: 2(12) + 6(1) + 16 = 24 + 6 + 16 = 46. ✓ This is ethanol (C₂H₅OH). CH₂O₂ = 12+2+32 = 46 also works (formic acid), but C₂H₆O is the more common answer for Mr=46."],
// ── Physics: Energy, Waves & Space extended (20q) ────────────────────────
["A student investigates the efficiency of a motor lifting a 2 kg mass 3 m in 5 seconds using 80 J of electrical energy. What is the efficiency? (g = 10 m/s²)","75%","60%","80%","50%",0,"Useful output = mgh = 2 × 10 × 3 = 60 J. Efficiency = (60/80) × 100 = 75%."],
["A student measures the frequency of a standing wave on a string of length 0.5 m. The fundamental frequency has one half-wavelength fitting the string length. What is the wavelength of the fundamental?","0.25 m","0.5 m","1.0 m","2.0 m",2,"For the fundamental mode, the string length = λ/2. Therefore λ = 2L = 2 × 0.5 = 1.0 m."],
["A student investigates the relationship between the temperature of a black body and the wavelength of peak emission. As temperature increases, peak wavelength decreases. Which law describes this?","Boyle's law","Wien's displacement law","Hubble's law","Faraday's law",1,"Wien's displacement law states that the peak wavelength of black body radiation is inversely proportional to temperature: λ_max = b/T (where b = 2.898 × 10⁻³ m·K). Hotter objects emit at shorter wavelengths (e.g. blue stars are hotter than red stars)."],
["A student calculates the gravitational force between two objects. Doubling the distance between them reduces the force to what fraction of its original value?","1/2","1/4","1/8","1/16",1,"Newton's law of gravitation: F ∝ 1/r². Doubling r gives F ∝ 1/(2r)² = 1/4r². The force is reduced to 1/4 of its original value — the inverse square law."],
["A student investigates nuclear fusion in stars. Which of the following correctly describes the conditions required for fusion to occur?","Low temperature and low pressure","Extremely high temperature (~10⁷ K) and pressure to overcome electrostatic repulsion between nuclei","Room temperature and atmospheric pressure","High temperature and low pressure",1,"Nuclear fusion requires extremely high temperatures (~10⁷ K for hydrogen fusion) to give nuclei sufficient kinetic energy to overcome the electrostatic repulsion between their positive charges. High pressure (density) increases collision frequency. These conditions exist in stellar cores."],
["A student analyses the spectrum of light from a distant star and finds absorption lines shifted toward longer wavelengths compared to a laboratory source. Which of the following correctly interprets this observation?","The star is moving toward Earth","The star is moving away from Earth — the Doppler effect stretches wavelengths (red shift)","The star is hotter than the Sun","The star is cooler than the Sun",1,"Red shift (wavelengths shifted toward longer/red end of spectrum) indicates the source is moving away from the observer. The Doppler effect stretches the wavelength of light from receding sources. This is the basis of Hubble's discovery that distant galaxies are receding."],
// ── Earth Science: Ecology extended (20q) ────────────────────────────────
["A student investigates the effect of temperature on the rate of decomposition of leaf litter in soil. Rate increases with temperature up to 35°C. Which of the following correctly explains why decomposition is slower in cold climates?","Cold climates have fewer leaves","Lower temperatures reduce the metabolic activity of decomposer microorganisms, slowing enzyme-controlled breakdown of organic matter","Cold climates have more oxygen","Decomposers migrate to warmer regions",1,"Decomposition is carried out by bacteria and fungi using enzyme-controlled reactions. Lower temperatures reduce enzyme activity (less kinetic energy, fewer successful collisions), slowing the breakdown of organic matter. This is why organic matter accumulates in cold climates (e.g. peat bogs)."],
["A student compares the net primary productivity (NPP) of a tropical rainforest and a desert. The rainforest has much higher NPP. Which of the following correctly explains this?","Deserts have more sunlight","Tropical rainforests have high temperature, rainfall and sunlight year-round, maximising photosynthesis; deserts are limited by water availability","Deserts have more nutrients","Rainforests have fewer plants",1,"Net primary productivity is the rate of biomass production by plants. Tropical rainforests have optimal conditions (warmth, water, light) for photosynthesis year-round. Deserts are severely limited by water — the primary limiting factor for photosynthesis and plant growth."],
["A student investigates the effect of introducing a new plant species to an ecosystem. The new species spreads rapidly and reduces native plant diversity by 60%. Which of the following correctly explains this?","The new species improves soil quality","The invasive species outcompetes native plants for resources (light, water, nutrients) and may lack natural predators or pathogens that would control its population in its native range","Native plants are less adapted to the environment","The new species increases biodiversity",1,"Invasive species often lack the natural predators, parasites and pathogens that control their populations in their native range. Without these controls, they can outcompete native species for resources, rapidly dominating the ecosystem and reducing native biodiversity."],
["A student analyses data on the population of a species of fish in a lake over 20 years. The population grew rapidly initially, then levelled off at approximately 5000 individuals. Which of the following correctly describes this growth pattern?","Exponential growth","Logistic growth — the population approached the carrying capacity of the lake","Linear growth","Random fluctuation",1,"Logistic growth: rapid initial growth when resources are abundant, followed by slowing growth as the population approaches the carrying capacity (K). At K, birth rate equals death rate and population stabilises. The S-shaped (sigmoidal) curve is characteristic of logistic growth."],
["A student investigates the effect of eutrophication on dissolved oxygen in a lake. Oxygen levels fall sharply after an algal bloom dies. Which of the following correctly explains the sequence of events?","Algae produce oxygen when they die","Bacteria decomposing dead algae consume large amounts of dissolved oxygen through aerobic respiration, creating hypoxic conditions that kill fish","Algae absorb oxygen from water","Fish consume all the oxygen",1,"Eutrophication sequence: excess nutrients → algal bloom → algae die → bacteria decompose dead algae using aerobic respiration → dissolved oxygen depleted (hypoxia/anoxia) → fish and other aerobic organisms suffocate. This is called biological oxygen demand (BOD)."],
// ── Scientific Method extended (20q) ─────────────────────────────────────
["A student investigates whether a new drug reduces blood pressure. They use a randomised controlled trial with 200 participants. Which of the following correctly explains why randomisation is important?","It reduces the number of participants needed","Random allocation to treatment and control groups minimises systematic differences between groups, reducing confounding bias","It eliminates the need for a control group","It ensures all participants receive the drug",1,"Randomisation ensures that known and unknown confounding variables are distributed equally between treatment and control groups by chance. This means any difference in outcomes can be attributed to the treatment rather than pre-existing differences between groups."],
["A student measures the boiling point of water at different altitudes and finds it decreases with altitude. Which of the following correctly explains this?","Water is less pure at high altitude","Atmospheric pressure decreases with altitude; lower pressure means water molecules need less energy to escape the liquid phase, so boiling occurs at lower temperatures","Temperature is always lower at high altitude","Water evaporates faster at high altitude",1,"Boiling occurs when vapour pressure equals atmospheric pressure. At higher altitudes, atmospheric pressure is lower, so water reaches its boiling point at a lower temperature. This is why cooking times are longer at altitude — water boils below 100°C."],
["A student plots a calibration curve for a colorimeter by measuring absorbance of known concentrations of a dye. The curve is linear between 0 and 0.5 mol/L. An unknown sample gives absorbance of 0.35. Which of the following correctly describes how to find the concentration?","Extrapolate beyond the linear range","Read the concentration corresponding to absorbance 0.35 from the linear portion of the calibration curve (interpolation)","Use the highest concentration on the curve","Divide absorbance by the gradient",1,"Interpolation: reading a value within the range of measured data from a calibration curve. The unknown absorbance (0.35) falls within the linear range, so the corresponding concentration can be read directly from the curve with confidence."],
["A student investigates the effect of exercise on heart rate. They measure heart rate before exercise, immediately after, and at 1, 3, 5 and 10 minutes after stopping. Which of the following correctly identifies the dependent variable?","Exercise intensity","Time after exercise","Heart rate","The student's age",2,"The dependent variable is what is measured — the variable that responds to changes in the independent variable. Here, heart rate is measured at different times (independent variable) to see how it changes with recovery time."],
["A student reports a result as 45.6 ± 0.5 cm. Which of the following correctly describes what the ± 0.5 cm represents?","The range of all measurements","The uncertainty — the range within which the true value is likely to lie","The systematic error","The percentage error",1,"The ± value represents the measurement uncertainty — the range within which the true value is expected to lie. It reflects the precision of the measurement and the limitations of the measuring instrument."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const domains = [...Array(10).fill('Biology'),...Array(5).fill('Biology'),...Array(5).fill('Chemistry'),...Array(5).fill('Chemistry'),...Array(6).fill('Physics'),...Array(5).fill('Earth Science'),...Array(5).fill('Earth Science'),...Array(5).fill('Earth Science')];
  const topics = [...Array(10).fill('Cell Biology'),...Array(5).fill('Genetics'),...Array(5).fill('Quantitative Chemistry'),...Array(5).fill('Organic Chemistry'),...Array(6).fill('Energy and Waves'),...Array(5).fill('Ecology and Environment'),...Array(5).fill('Ecology and Environment'),...Array(5).fill('Scientific Method')];
  last.push({id:`MCQ-LAST-Y910-${String(i+1).padStart(3,'0')}`,domain:domains[i]||'Science',topic:topics[i]||'Science',difficulty:i%2===0?'Medium':'Hard',question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./last-bank.json', JSON.stringify(last,null,2));
console.log(`Last batch: ${last.length}`);
