const fs = require('fs');
const extra = [];

const q = [
// ── Physics: Thermodynamics & Optics ─────────────────────────────────────
["A student heats 200 g of water from 20°C to 80°C. Using Q = mcΔT (c = 4200 J/kg°C), how much energy is required?","50 400 J","8 400 J","504 000 J","84 000 J",0,"Q = mcΔT = 0.2 kg × 4200 J/kg°C × 60°C = 50 400 J."],
["A student investigates the specific heat capacity of a metal block. They supply 2000 J of energy to a 500 g block and measure a temperature rise of 8°C. What is the specific heat capacity?","500 J/kg°C","250 J/kg°C","4000 J/kg°C","1000 J/kg°C",0,"c = Q/(mΔT) = 2000/(0.5 × 8) = 2000/4 = 500 J/kg°C."],
["A student investigates the cooling of two identical containers — one painted black, one shiny silver. The black container cools faster. Which of the following correctly explains this?","Black surfaces are better conductors","Black surfaces are better emitters of infrared radiation than shiny surfaces","Shiny surfaces absorb more radiation","Black surfaces have lower specific heat capacity",1,"Black (matt) surfaces are good absorbers and emitters of infrared radiation. Shiny surfaces reflect infrared and are poor emitters. The black container loses heat faster by radiation."],
["A ray of light travels from glass (n=1.5) into air (n=1.0) at an angle of incidence of 30°. Using Snell's law (n₁sinθ₁ = n₂sinθ₂), what is the angle of refraction?","20°","48.6°","30°","90°",1,"n₁sinθ₁ = n₂sinθ₂ → 1.5 × sin30° = 1.0 × sinθ₂ → 1.5 × 0.5 = sinθ₂ → sinθ₂ = 0.75 → θ₂ = 48.6°."],
["A student investigates total internal reflection. The critical angle for glass-air is 42°. A ray hits the glass-air boundary at 50°. Which of the following correctly describes what happens?","The ray refracts into the air","Total internal reflection occurs — the ray reflects back into the glass","The ray is absorbed","The ray passes straight through",1,"When the angle of incidence exceeds the critical angle (50° > 42°), total internal reflection occurs. The ray cannot pass into the less dense medium and is completely reflected back into the glass."],
["A student uses a converging lens of focal length 10 cm to form an image of an object placed 30 cm from the lens. Using 1/f = 1/v - 1/u (with sign convention), where is the image formed?","10 cm from the lens","15 cm from the lens","20 cm from the lens","30 cm from the lens",1,"Using 1/f = 1/v + 1/u (real is positive): 1/10 = 1/v + 1/30 → 1/v = 1/10 - 1/30 = 3/30 - 1/30 = 2/30 → v = 15 cm."],
["A student investigates the photoelectric effect. Increasing the frequency of light above the threshold frequency increases the maximum kinetic energy of emitted electrons. Which of the following correctly explains this?","Higher frequency means more photons","Higher frequency photons have more energy (E=hf); after overcoming the work function, more energy remains as kinetic energy of the electron","Higher frequency increases the intensity","Higher frequency reduces the work function",1,"Photon energy E = hf. Above the threshold frequency, the photon has enough energy to eject an electron. Any energy above the work function (φ) becomes kinetic energy: KE_max = hf - φ. Higher frequency → more energy → greater KE_max."],
["A student measures the half-life of a radioactive isotope by counting decay events. After 40 minutes, the count rate has fallen to 1/8 of its original value. What is the half-life?","5 minutes","10 minutes","13.3 minutes","20 minutes",2,"(1/2)ⁿ = 1/8 → n = 3 half-lives. Time = 40 minutes ÷ 3 = 13.3 minutes per half-life."],
["A student compares the ionising ability of alpha, beta and gamma radiation. Which of the following correctly ranks them from most to least ionising?","Gamma > beta > alpha","Alpha > beta > gamma","Beta > alpha > gamma","All three ionise equally",1,"Alpha particles are large (helium nuclei), slow-moving and highly charged — they ionise strongly but are stopped quickly. Beta particles are faster and less ionising. Gamma rays are highly penetrating but weakly ionising."],
["A student investigates the relationship between the distance of a planet from the Sun and its orbital period (Kepler's third law: T² ∝ r³). Earth's orbital period is 1 year at 1 AU. A planet at 4 AU has what orbital period?","4 years","8 years","2 years","16 years",1,"T² ∝ r³ → T² = r³ = 4³ = 64 → T = √64 = 8 years."],
// ── Earth Science: Ecology & Geology ─────────────────────────────────────
["A student investigates the effect of removing wolves from Yellowstone National Park. Elk populations increased, overgrazing reduced vegetation, and stream banks eroded. Reintroducing wolves reversed these effects. Which ecological concept does this illustrate?","Competitive exclusion","Trophic cascade — changes at one trophic level affect multiple levels below","Primary succession","Eutrophication",1,"A trophic cascade occurs when a top predator's presence or absence affects multiple lower trophic levels. Wolves controlled elk numbers, allowing vegetation recovery, which stabilised stream banks — demonstrating the far-reaching effects of keystone predators."],
["A student analyses data showing that species diversity in a forest increases with distance from a road. Which of the following correctly explains this pattern?","Roads increase biodiversity by creating new habitats","Roads create edge effects — noise, pollution, light and human disturbance reduce diversity near roads; interior forest has more stable conditions","Species prefer to live near roads","Roads have no effect on biodiversity",1,"Roads create edge effects: noise, light pollution, vehicle emissions, invasive species and human disturbance reduce habitat quality near roads. Interior forest provides more stable, undisturbed conditions supporting greater species diversity."],
["A student investigates primary succession on a volcanic island. Which of the following correctly describes the sequence of events?","Climax community appears first, then pioneer species","Pioneer species (lichens, mosses) colonise bare rock, modify the environment, enabling more complex communities to establish, eventually reaching a climax community","All species colonise simultaneously","Succession only occurs in aquatic environments",1,"Primary succession on bare rock: pioneer species (lichens, mosses) weather rock and add organic matter, creating thin soil. This enables grasses, then shrubs, then trees to establish. Each stage modifies conditions for the next, eventually reaching a stable climax community."],
["A student compares the carbon stored in a tropical rainforest and a temperate grassland per hectare. The rainforest stores significantly more carbon. Which of the following correctly explains this?","Grasslands photosynthesise more efficiently","Rainforests have greater biomass due to year-round growing conditions, storing more carbon in wood and organic matter","Grasslands have more decomposers","Rainforests have less biodiversity",1,"Tropical rainforests have high temperatures and rainfall year-round, supporting continuous rapid growth and enormous biomass. The large woody biomass (trees) stores vast amounts of carbon. Grasslands have lower biomass and store more carbon in soil than above ground."],
["A student investigates the effect of acid rain on a freshwater ecosystem. pH decreases from 7 to 4.5 over 10 years. Which of the following correctly predicts the ecological impact?","Biodiversity increases as pH decreases","Most aquatic organisms cannot tolerate pH below 5; fish, invertebrates and amphibians decline, reducing biodiversity","Acid rain has no effect on aquatic organisms","Only plants are affected by pH changes",1,"Most freshwater organisms are adapted to near-neutral pH. As pH falls below 5, aluminium ions (toxic to fish) are mobilised from soils, and many invertebrates and fish cannot survive. Reduced prey availability further impacts predators, causing cascading biodiversity loss."],
["A student analyses seismic wave data from an earthquake. P-waves arrive at a seismograph before S-waves. Which of the following correctly explains this?","P-waves travel through solids only","P-waves are longitudinal and travel faster than S-waves (transverse) through rock","S-waves travel faster than P-waves","P-waves travel through liquids; S-waves do not",1,"P-waves (primary/compressional waves) are longitudinal and travel faster than S-waves (secondary/shear waves) through rock. P-waves arrive first at seismographs. S-waves cannot travel through liquid — this is how scientists determined Earth has a liquid outer core."],
["A student investigates the distribution of magnetic anomalies on the seafloor. Symmetric stripes of normal and reversed magnetism are found on either side of a mid-ocean ridge. Which of the following correctly interprets this data?","The seafloor is stationary","New seafloor is continuously created at the ridge; as it cools, it records the current magnetic field orientation. Periodic reversals of Earth's magnetic field create the symmetric striped pattern","The stripes are caused by different rock types","Magnetic anomalies are unrelated to plate tectonics",1,"Seafloor spreading: magma erupts at mid-ocean ridges and cools, recording Earth's magnetic field direction. Periodic geomagnetic reversals create alternating normal/reversed stripes. The symmetric pattern on both sides of the ridge is strong evidence for seafloor spreading and plate tectonics."],
["A student compares the greenhouse warming potential of CO₂ and methane. Methane has a global warming potential (GWP) approximately 25 times greater than CO₂ over 100 years. Which of the following correctly explains why reducing methane emissions is a high priority?","Methane is more abundant than CO₂","Despite lower atmospheric concentration, methane's high GWP means each molecule causes significantly more warming than CO₂; reducing methane has rapid climate benefits","Methane lasts longer in the atmosphere than CO₂","Methane is easier to measure than CO₂",1,"Methane's GWP of ~25 means it traps 25 times more heat per molecule than CO₂ over 100 years. Although less abundant, reducing methane emissions (from agriculture, landfill, fossil fuels) provides rapid climate benefits because methane has a shorter atmospheric lifetime (~12 years) than CO₂."],
["A student investigates the effect of urbanisation on local temperature. Urban areas are consistently warmer than surrounding rural areas. Which of the following correctly explains the urban heat island effect?","Urban areas receive more solar radiation","Dark surfaces (roads, buildings) absorb more solar energy; reduced vegetation decreases evaporative cooling; waste heat from vehicles and buildings all contribute to higher urban temperatures","Urban areas have more greenhouse gases","Urban areas are at lower altitude",1,"The urban heat island effect results from: dark impervious surfaces absorbing more solar radiation; reduced vegetation (less evapotranspiration cooling); waste heat from transport and buildings; and reduced wind speed between buildings. Together these raise urban temperatures by 1-3°C above rural areas."],
["A student analyses data showing that global average sea level has risen 20 cm since 1900 and the rate is accelerating. Which of the following correctly identifies the two main causes?","Increased rainfall and river flow","Thermal expansion of seawater as it warms, and melting of land-based ice (glaciers and ice sheets)","Increased ocean salinity","Tectonic uplift of ocean floors",1,"Sea level rise has two main causes: (1) thermal expansion — warmer water occupies more volume; (2) melting of land-based ice (glaciers, Greenland and Antarctic ice sheets) adds water to the ocean. Sea ice melting does not raise sea level (it is already displacing water)."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const domain = i < 10 ? "Physics" : "Earth Science";
  const topics = ['Thermodynamics','Thermodynamics','Thermodynamics','Optics and Light','Optics and Light','Optics and Light','Nuclear and Space','Nuclear and Space','Nuclear and Space','Space and Astronomy','Ecology and Environment','Ecology and Environment','Ecology and Environment','Ecology and Environment','Ecology and Environment','Geology and Climate','Geology and Climate','Geology and Climate','Geology and Climate','Geology and Climate'];
  extra.push({id:`MCQ-EXTRA-Y910-${String(i+1).padStart(3,'0')}`,domain,topic:topics[i]||domain,difficulty:i%2===0?"Medium":"Hard",question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./extra-bank.json', JSON.stringify(extra,null,2));
console.log(`Extra questions: ${extra.length}`);
