const fs = require('fs');
const fin = [];
const q = [
["A student investigates the effect of increasing substrate concentration on the rate of an enzyme-catalysed reaction. The Michaelis constant (Km) is the substrate concentration at half-maximum velocity. A lower Km indicates which of the following?","Lower enzyme affinity for substrate","Higher enzyme affinity for substrate — less substrate is needed to half-saturate the enzyme","Higher maximum velocity","More enzyme is present",1,"Km is the substrate concentration at which reaction rate = Vmax/2. A lower Km means the enzyme reaches half-maximum velocity at lower substrate concentration — indicating higher affinity between enzyme and substrate."],
["A student investigates the effect of a drug that blocks sodium-potassium ATPase pumps in neurons. Which of the following would be the most immediate consequence?","Faster nerve impulse transmission","Inability to restore resting membrane potential after action potentials, leading to failure of nerve signalling","Increased neurotransmitter release","Faster synaptic transmission",1,"The Na⁺/K⁺ ATPase pump restores the resting membrane potential after each action potential by pumping 3 Na⁺ out and 2 K⁺ in. Blocking this pump prevents repolarisation, making neurons unable to fire repeated action potentials."],
["A student investigates the effect of ethylene on fruit ripening. Unripe fruit placed with ripe fruit ripens faster. Which of the following correctly explains this?","Ripe fruit produces oxygen","Ripe fruit releases ethylene gas, which diffuses to unripe fruit and activates ripening enzymes that soften cell walls and convert starch to sugars","Ripe fruit produces heat","Unripe fruit absorbs nutrients from ripe fruit",1,"Ethylene is a gaseous plant hormone that triggers fruit ripening. Ripe fruit produces ethylene, which diffuses through the air to neighbouring unripe fruit, activating cell wall-softening enzymes and starch-to-sugar conversion — explaining why one rotten apple spoils the barrel."],
["A student investigates the effect of auxin concentration on root and shoot growth. Low auxin concentrations promote root growth; high concentrations inhibit it. Which of the following correctly explains the differential sensitivity?","Roots and shoots have different DNA","Root cells are more sensitive to auxin than shoot cells — concentrations that promote shoot elongation inhibit root elongation due to different receptor densities and downstream signalling","Auxin is destroyed in roots","Shoots produce more auxin than roots",1,"Roots and shoots have different sensitivities to auxin. Root cells have more auxin receptors or different downstream signalling, making them respond to much lower concentrations. Concentrations optimal for shoot elongation are supraoptimal for roots, inhibiting their growth."],
["A student investigates the effect of temperature on the rate of transpiration. Rate increases with temperature. Which of the following correctly explains the role of stomata in this relationship?","Stomata close at higher temperatures","Higher temperatures increase the kinetic energy of water molecules and reduce air humidity, steepening the water vapour gradient; stomata remain open during the day allowing water vapour to diffuse out faster","Stomata open wider at lower temperatures","Temperature has no effect on stomatal aperture",1,"Transpiration rate depends on: (1) the water vapour concentration gradient between leaf air spaces and external air; (2) stomatal aperture. Higher temperatures increase evaporation from mesophyll cells and reduce relative humidity of air, steepening the gradient and increasing transpiration through open stomata."],
["A student investigates the effect of pH on the solubility of calcium carbonate. Solubility increases at lower pH. Which of the following correctly explains this?","Lower pH increases calcium ion concentration","Lower pH increases H⁺ concentration; H⁺ reacts with CO3²⁻ ions, removing them from solution and shifting the dissolution equilibrium toward more CaCO3 dissolving","Lower pH decreases water temperature","Lower pH increases carbonate concentration",1,"CaCO3 ⇌ Ca²⁺ + CO3²⁻. At lower pH, H⁺ reacts with CO3²⁻: H⁺ + CO3²⁻ → HCO3⁻. This removes CO3²⁻ from solution, shifting equilibrium right (Le Chatelier's principle), dissolving more CaCO3. This is why acid rain dissolves limestone."],
["A student investigates the reaction of sodium carbonate with hydrochloric acid: Na2CO3 + 2HCl → 2NaCl + H2O + CO2. What volume of CO2 is produced at STP when 5.3 g of Na2CO3 reacts with excess HCl? (Mr Na2CO3 = 106; molar volume at STP = 22.4 L/mol)","1.12 L","2.24 L","0.56 L","4.48 L",0,"Moles Na2CO3 = 5.3/106 = 0.05 mol. From equation, 1 mol Na2CO3 produces 1 mol CO2. So 0.05 mol CO2. Volume = 0.05 × 22.4 = 1.12 L."],
["A student investigates the effect of concentration on the rate of reaction between HCl and CaCO3. They measure the volume of CO2 produced over time. Which of the following correctly describes the shape of the volume-time graph?","A straight line through the origin","A curve that starts steep and levels off as reactants are consumed","A straight horizontal line","A curve that starts flat and becomes steeper",1,"As the reaction proceeds, reactant concentration decreases, slowing the rate. The volume-time graph starts steep (fast initial rate at high concentration) and levels off as reactants are consumed and rate decreases, eventually reaching a plateau when reaction is complete."],
["A student investigates the properties of a buffer solution. Adding 0.01 mol of HCl to 1 L of buffer changes pH by only 0.1 units. Adding the same amount to pure water changes pH by 2 units. Which of the following correctly explains the buffer's resistance to pH change?","Buffers neutralise all acids","The buffer contains a weak acid and its conjugate base; added H⁺ is consumed by the conjugate base (A⁻ + H⁺ → HA), minimising pH change","Buffers have no weak acid","Buffers increase in concentration when acid is added",1,"A buffer (weak acid HA + conjugate base A⁻) resists pH change: added H⁺ is consumed by A⁻ → HA; added OH⁻ is consumed by HA → A⁻ + H₂O. The equilibrium shifts to absorb the added acid or base, minimising pH change."],
["A student investigates the effect of pressure on the rate of a gas-phase reaction. Doubling pressure doubles the rate. Which of the following correctly explains this?","Pressure changes activation energy","Doubling pressure doubles the concentration of gas molecules, increasing collision frequency and therefore reaction rate","Pressure changes temperature","Pressure changes the products",1,"For gases, pressure is proportional to concentration (at constant T and V). Doubling pressure doubles the number of gas molecules per unit volume, doubling collision frequency and reaction rate (for a first-order reaction with respect to that reactant)."],
["A student investigates the motion of a ball rolling down a ramp. The acceleration is constant. Which of the following correctly describes the velocity-time graph?","A horizontal line","A straight line with positive gradient (constant acceleration)","A curve","A line with decreasing gradient",1,"Constant acceleration produces a linear velocity-time graph (straight line with positive gradient). The gradient equals the acceleration. This is consistent with Newton's second law — constant net force on constant mass produces constant acceleration."],
["A student investigates the elastic potential energy stored in a spring. Using E = ½kx², if k = 200 N/m and x = 0.1 m, what is the elastic PE?","1 J","2 J","10 J","0.1 J",0,"E = ½kx² = ½ × 200 × (0.1)² = ½ × 200 × 0.01 = 1 J."],
["A student investigates the relationship between the angle of a ramp and the component of gravity along the ramp. For a mass m on a ramp at angle θ, the component along the ramp is mg sinθ. At 30°, what fraction of the weight acts along the ramp?","0.5","0.866","1.0","0.25",0,"Component along ramp = mg sin30° = mg × 0.5. So 0.5 (50%) of the weight acts along the ramp. The component perpendicular to the ramp = mg cos30° = mg × 0.866."],
["A student investigates the effect of increasing the distance between two parallel plates of a capacitor while keeping charge constant. Voltage increases. Which of the following correctly explains this?","More charge accumulates","Increasing plate separation increases the electric field path length; for constant charge, voltage V = Q/C increases as capacitance C = ε₀A/d decreases with increasing d","Capacitance increases with distance","Charge density increases",1,"Capacitance C = ε₀A/d. Increasing d decreases C. Since Q = CV and Q is constant, V = Q/C increases. The electric field E = V/d remains approximately constant, but voltage increases proportionally with distance."],
["A student investigates the half-life of protactinium-234 using a Geiger counter. The count rate falls from 200 to 25 counts/min. How many half-lives have elapsed?","2","3","4","5",1,"200 → 100 → 50 → 25. Three halvings = 3 half-lives. (200 × (1/2)³ = 200/8 = 25)."],
["A student investigates the effect of increasing ocean temperature on the distribution of marine species. Species are shifting poleward. Which of the following correctly explains this?","Warmer water contains more food","Species are tracking their thermal tolerance range — as oceans warm, species move poleward to remain within their preferred temperature range","Species prefer colder water","Poleward currents are stronger",1,"Climate change is causing species range shifts as organisms track their thermal tolerance zones. Marine species adapted to specific temperature ranges are moving poleward (toward cooler water) as their traditional habitats warm beyond their tolerance limits."],
["A student investigates the effect of nitrogen deposition on soil pH. High nitrogen deposition decreases soil pH. Which of the following correctly explains the ecological consequence?","Lower pH increases plant diversity","Lower pH mobilises toxic aluminium ions from soil minerals, which damage plant roots and reduce nutrient uptake, decreasing plant diversity and productivity","Lower pH increases nitrogen availability","Lower pH has no effect on soil organisms",1,"Soil acidification from nitrogen deposition mobilises Al³⁺ ions from soil minerals. Al³⁺ is toxic to plant roots, inhibiting nutrient uptake and damaging root cells. This reduces plant diversity (acid-sensitive species decline) and productivity, with cascading effects on dependent organisms."],
["A student investigates the effect of habitat fragmentation on wildlife populations. Fragmented habitats support smaller, more isolated populations. Which of the following correctly explains the genetic consequence?","Fragmentation increases genetic diversity","Smaller isolated populations are more susceptible to genetic drift and inbreeding, reducing genetic diversity and increasing the risk of inbreeding depression","Fragmentation has no genetic effects","Isolated populations evolve faster",1,"Habitat fragmentation creates small, isolated populations. Small populations are vulnerable to genetic drift (random allele frequency changes) and inbreeding (mating between relatives). Both reduce genetic diversity, increase the frequency of harmful recessive alleles (inbreeding depression) and reduce adaptive potential."],
["A student investigates the effect of microplastics on soil organisms. Earthworm populations decline in microplastic-contaminated soil. Which of the following correctly explains the ecological consequence?","Fewer earthworms improve soil quality","Earthworms are ecosystem engineers — they aerate soil, mix organic matter and enhance nutrient cycling; their decline reduces soil fertility and plant productivity","Earthworms are not important to soil ecosystems","Microplastics improve drainage",1,"Earthworms are keystone soil organisms. They burrow through soil (improving aeration and drainage), fragment organic matter (accelerating decomposition) and mix soil layers (improving nutrient distribution). Their decline due to microplastic contamination reduces soil fertility and plant productivity."],
["A student investigates the relationship between biodiversity and resilience in grassland ecosystems. More diverse grasslands recover faster after drought. Which of the following correctly explains this?","Diverse grasslands have more water","Greater species diversity provides functional redundancy — if drought-sensitive species decline, drought-tolerant species maintain ecosystem functions, allowing faster recovery","Diverse grasslands have deeper roots only","Resilience is unrelated to biodiversity",1,"Functional redundancy: in diverse ecosystems, multiple species perform similar ecological roles. When one species is stressed or lost, others can compensate. This redundancy buffers the ecosystem against disturbance, maintaining function and enabling faster recovery — a key mechanism linking biodiversity to resilience."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const domains=['Biology','Biology','Biology','Biology','Biology','Chemistry','Chemistry','Chemistry','Chemistry','Chemistry','Physics','Physics','Physics','Physics','Physics','Earth Science','Earth Science','Earth Science','Earth Science','Earth Science'];
  const topics=['Cell Biology','Human Body','Plants and Photosynthesis','Plants and Photosynthesis','Plants and Photosynthesis','Reactions and Energy','Quantitative Chemistry','Reactions and Energy','Reactions and Energy','Reactions and Energy','Forces and Motion','Forces and Motion','Forces and Motion','Electricity and Magnetism','Nuclear and Space','Earth and Climate','Ecology and Environment','Ecology and Environment','Ecology and Environment','Ecology and Environment'];
  fin.push({id:`MCQ-FIN-Y910-${String(i+1).padStart(3,'0')}`,domain:domains[i]||'Science',topic:topics[i]||'Science',difficulty:i%2===0?'Medium':'Hard',question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./fin-bank.json', JSON.stringify(fin,null,2));
console.log(`Fin batch: ${fin.length}`);
