const fs = require('fs');
const phys = [];

const physQ = [
// ── Forces & Motion ───────────────────────────────────────────────────────
["A student drops a ball from rest and measures its velocity every second. The velocity increases by 9.8 m/s each second. Which of the following correctly describes this motion?","Constant velocity","Uniform deceleration","Uniform acceleration due to gravity","Random motion",2,"The ball accelerates uniformly at g = 9.8 m/s² due to gravity. Each second, velocity increases by 9.8 m/s — this is uniform acceleration."],
["A 5 kg object accelerates at 3 m/s². What is the net force acting on it?","1.67 N","8 N","15 N","0.6 N",2,"F = ma = 5 × 3 = 15 N. Newton's second law states that net force equals mass times acceleration."],
["A student pushes a box across a floor at constant velocity. Which of the following correctly describes the forces acting on the box?","Net force is upward","The applied force is greater than friction","Net force is zero — applied force equals friction","There are no forces acting",2,"At constant velocity, acceleration is zero. By Newton's first law, net force must be zero — the applied force exactly balances friction."],
["A car of mass 1200 kg travelling at 20 m/s brakes to a stop in 4 seconds. What is the braking force?","6000 N","4800 N","300 N","240 N",0,"Deceleration = Δv/t = 20/4 = 5 m/s². F = ma = 1200 × 5 = 6000 N."],
["A student investigates the extension of a spring. For loads up to 6 N, extension is proportional to load. Beyond 6 N, the relationship is no longer linear. What does the 6 N point represent?","The breaking point","The elastic limit","The maximum extension","The equilibrium point",1,"The elastic limit (or limit of proportionality) is the point beyond which Hooke's law no longer applies and the spring is permanently deformed."],
["A rocket in space fires its engines. According to Newton's third law, which of the following correctly describes the reaction force?","The rocket pushes forward on the exhaust gases","The exhaust gases push backward on the rocket","The exhaust gases push forward on the rocket","There is no reaction force in space",1,"Newton's third law: for every action there is an equal and opposite reaction. The rocket pushes exhaust gases backward; the exhaust gases push the rocket forward with equal force."],
["A student measures the momentum of a 2 kg ball moving at 5 m/s. What is its momentum?","2.5 kg m/s","7 kg m/s","10 kg m/s","3 kg m/s",2,"Momentum = mass × velocity = 2 × 5 = 10 kg m/s."],
["Two ice skaters push off each other from rest. Skater A (mass 60 kg) moves at 2 m/s. What is the speed of skater B (mass 40 kg)?","2 m/s","3 m/s","1.33 m/s","4 m/s",1,"Conservation of momentum: total momentum before = 0. So 60 × 2 = 40 × v. v = 120/40 = 3 m/s in the opposite direction."],
["A student plots a velocity-time graph for a moving object. The area under the graph represents which quantity?","Acceleration","Force","Distance travelled","Power",2,"The area under a velocity-time graph equals displacement (distance travelled). The gradient of a velocity-time graph equals acceleration."],
["A student investigates stopping distance at different speeds. Doubling the speed increases the braking distance by a factor of four. Which of the following correctly explains this?","Braking force doubles with speed","Kinetic energy is proportional to v², so braking distance is proportional to v²","Friction increases with speed","Mass increases with speed",1,"Kinetic energy = ½mv². Doubling v quadruples KE. Since braking force is constant, the distance needed to dissipate four times the energy is four times greater."],
// ── Energy & Waves ────────────────────────────────────────────────────────
["A 2 kg ball is lifted 5 m above the ground. What is its gravitational potential energy? (g = 10 m/s²)","10 J","25 J","100 J","50 J",2,"GPE = mgh = 2 × 10 × 5 = 100 J."],
["A student releases a pendulum from a height of 0.2 m. What is the maximum speed at the bottom of the swing? (g = 10 m/s², ignore air resistance)","1 m/s","2 m/s","4 m/s","0.5 m/s",1,"Conservation of energy: mgh = ½mv². v = √(2gh) = √(2 × 10 × 0.2) = √4 = 2 m/s."],
["A wave has a frequency of 500 Hz and a wavelength of 0.68 m. What is its speed?","735 m/s","340 m/s","0.00136 m/s","1000 m/s",1,"Wave speed = frequency × wavelength = 500 × 0.68 = 340 m/s (speed of sound in air)."],
["A student investigates the reflection of waves in a ripple tank. The angle of incidence is 35°. What is the angle of reflection?","55°","70°","35°","90°",2,"The law of reflection states that the angle of incidence equals the angle of reflection, both measured from the normal to the surface."],
["Which of the following correctly explains why a straw appears bent when placed in a glass of water?","Light reflects off the water surface","Light refracts (changes speed and direction) as it passes from water to air","The straw actually bends in water","Light is absorbed by water",1,"Light travels more slowly in water than in air. When it crosses the boundary, it changes direction (refracts), making the straw appear bent at the water surface."],
["A student measures the frequency of a sound wave as 440 Hz. What does this mean?","The wave travels 440 m per second","440 complete wave cycles pass a point per second","The wavelength is 440 m","The amplitude is 440 units",1,"Frequency is the number of complete wave cycles per second, measured in Hertz (Hz). 440 Hz means 440 complete cycles per second — the note A in music."],
["A student investigates the electromagnetic spectrum. Which of the following correctly orders waves from longest to shortest wavelength?","Gamma, X-ray, UV, visible, infrared, microwave, radio","Radio, microwave, infrared, visible, UV, X-ray, gamma","Visible, UV, infrared, radio, microwave, X-ray, gamma","Radio, visible, UV, microwave, infrared, X-ray, gamma",1,"The electromagnetic spectrum from longest to shortest wavelength: radio → microwave → infrared → visible → UV → X-ray → gamma ray."],
["A student uses a convex lens to focus sunlight onto a piece of paper. Which property of the lens causes this?","The lens reflects light","The lens refracts parallel rays to converge at the focal point","The lens absorbs UV radiation","The lens diffracts light",1,"A convex (converging) lens refracts parallel rays of light so they converge at the focal point. The concentrated energy at this point can ignite paper."],
["A student investigates total internal reflection using a semicircular glass block. At which angle does total internal reflection first occur?","The angle of refraction","The critical angle","90°","The angle of incidence equals 0°",1,"Total internal reflection occurs when light travels from a denser to a less dense medium and the angle of incidence exceeds the critical angle. At the critical angle, the refracted ray travels along the boundary (90° refraction)."],
["A student measures the speed of sound by timing an echo from a wall 170 m away. The echo returns after 1 second. What is the speed of sound?","85 m/s","170 m/s","340 m/s","680 m/s",2,"Sound travels to the wall and back — total distance = 2 × 170 = 340 m in 1 second. Speed = distance/time = 340/1 = 340 m/s."],
// ── Electricity & Magnetism ───────────────────────────────────────────────
["A student connects a 12 V battery to a resistor and measures a current of 3 A. What is the resistance of the resistor?","36 Ω","4 Ω","0.25 Ω","9 Ω",1,"R = V/I = 12/3 = 4 Ω (Ohm's law: V = IR)."],
["Two resistors of 6 Ω and 3 Ω are connected in parallel. What is the total resistance?","9 Ω","2 Ω","4.5 Ω","18 Ω",1,"1/R_total = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2. R_total = 2 Ω."],
["A student measures the current through a resistor at different voltages and plots a straight line through the origin. What does this indicate?","The resistor does not obey Ohm's law","The resistor obeys Ohm's law — resistance is constant","The resistance increases with voltage","The current decreases with voltage",1,"A straight line through the origin on a V-I graph indicates that V is directly proportional to I — the component obeys Ohm's law and has constant resistance."],
["A 60 W light bulb is left on for 2 hours. How much energy does it use?","120 J","432 000 J","7200 J","3600 J",1,"Energy = power × time = 60 W × (2 × 3600 s) = 60 × 7200 = 432 000 J."],
["A student investigates the magnetic field around a current-carrying wire. Which of the following correctly describes the field?","Straight lines parallel to the wire","Concentric circles around the wire, with direction given by the right-hand rule","Straight lines perpendicular to the wire","No magnetic field is produced",1,"A current-carrying wire produces a magnetic field in concentric circles around the wire. The direction is given by the right-hand rule (thumb points in direction of current, fingers curl in direction of field)."],
["A student builds an electromagnet by wrapping wire around an iron core. Which of the following would increase the strength of the electromagnet?","Decreasing the current","Using a steel core instead of iron","Increasing the number of turns of wire","Decreasing the voltage",2,"Increasing the number of turns increases the magnetic field strength. Iron is preferred over steel as it is a soft magnetic material that is easily magnetised and demagnetised."],
["A transformer has 200 turns on the primary coil and 1000 turns on the secondary coil. If the input voltage is 12 V, what is the output voltage?","2.4 V","60 V","12 V","120 V",1,"Vs/Vp = Ns/Np. Vs = 12 × (1000/200) = 12 × 5 = 60 V. This is a step-up transformer."],
["A student investigates the photoelectric effect. Increasing the intensity of light below the threshold frequency does not cause electron emission. Which of the following best explains this?","Light is a wave and waves cannot eject electrons","Light consists of photons; below the threshold frequency each photon has insufficient energy to eject an electron regardless of intensity","Intensity is not related to energy","Electrons are too heavy to be ejected",1,"The photoelectric effect demonstrates the particle nature of light. Each photon must have sufficient energy (E = hf) to eject an electron. Below the threshold frequency, no individual photon has enough energy, regardless of how many photons (intensity) arrive."],
["A student connects three identical bulbs in series and then in parallel with the same battery. Which arrangement produces brighter bulbs?","Series","Parallel","Both are equally bright","It depends on the battery",1,"In parallel, each bulb receives the full battery voltage. In series, the voltage is shared between bulbs. Higher voltage means more power (P = V²/R), so parallel bulbs are brighter."],
["Which of the following correctly explains how a step-down transformer works?","It uses a chemical reaction to reduce voltage","Alternating current in the primary coil creates a changing magnetic field, which induces a lower voltage in the secondary coil with fewer turns","It converts AC to DC","It stores electrical energy",1,"A transformer works by electromagnetic induction. AC in the primary creates a changing magnetic flux in the iron core, inducing an EMF in the secondary. Fewer turns on the secondary gives a lower output voltage."],
// ── Nuclear Physics & Space ───────────────────────────────────────────────
["A radioactive sample has a half-life of 20 years. What fraction of the original sample remains after 60 years?","1/2","1/4","1/8","1/16",2,"After 60 years = 3 half-lives. Fraction remaining = (1/2)³ = 1/8."],
["A student investigates alpha, beta and gamma radiation using different absorbers. Which of the following correctly matches radiation type to its penetrating power?","Alpha is most penetrating; gamma is least","Gamma is most penetrating; alpha is stopped by a few centimetres of air or a sheet of paper","Beta is most penetrating; alpha is stopped by lead","All three have equal penetrating power",1,"Alpha particles are stopped by a few cm of air or paper. Beta particles are stopped by a few mm of aluminium. Gamma rays require several cm of lead or metres of concrete to significantly reduce intensity."],
["Which of the following correctly describes nuclear fission?","Small nuclei fuse together releasing energy","A large nucleus splits into smaller nuclei, releasing energy and neutrons","A nucleus emits an alpha particle","A nucleus emits a beta particle",1,"Nuclear fission occurs when a large unstable nucleus (e.g. uranium-235) absorbs a neutron and splits into two smaller nuclei, releasing energy and 2-3 neutrons that can trigger further fissions (chain reaction)."],
["A student compares nuclear fission and nuclear fusion. Which of the following is a correct comparison?","Fission joins nuclei; fusion splits them","Both fission and fusion release energy, but fusion requires extremely high temperatures to overcome electrostatic repulsion between nuclei","Fusion is used in current nuclear power stations","Fission produces no radioactive waste",1,"Both processes release energy. Fusion (joining light nuclei) requires extremely high temperatures (~10⁷ K) to overcome the electrostatic repulsion between positively charged nuclei. Current power stations use fission."],
["A student observes that the light from distant galaxies is red-shifted. Which of the following correctly interprets this observation?","Distant galaxies are moving toward us","Distant galaxies are moving away from us, and the universe is expanding","The galaxies are cooling down","The galaxies are rotating faster",1,"Red shift occurs when a light source moves away from the observer — the wavelength is stretched. The greater the red shift, the faster the galaxy is receding. This is evidence for the expanding universe."],
["Which of the following correctly describes the life cycle of a star similar to our Sun?","Nebula → main sequence → red supergiant → supernova → neutron star","Nebula → main sequence → red giant → planetary nebula → white dwarf","Nebula → white dwarf → main sequence → red giant","Nebula → neutron star → main sequence → red giant",1,"A star like the Sun: forms from a nebula → main sequence (hydrogen fusion) → red giant (hydrogen exhausted in core) → planetary nebula (outer layers expelled) → white dwarf (dense remnant)."],
["A student investigates background radiation and measures 30 counts per minute with no source present. What is the most likely source of this background radiation?","Only nuclear power stations","Only cosmic rays","Natural sources including cosmic rays, rocks (radon gas) and building materials, plus small contributions from human activity","Only medical X-rays",2,"Background radiation comes from natural sources (cosmic rays, naturally occurring radioactive isotopes in rocks and soil, radon gas) and artificial sources (nuclear industry, medical uses). Natural sources dominate."],
["Which of the following correctly explains why nuclear fusion releases energy?","The products have more mass than the reactants","The products have less mass than the reactants; the mass difference is converted to energy (E = mc²)","Electrons are released during fusion","The reaction is endothermic",1,"In nuclear fusion, the mass of the products is slightly less than the mass of the reactants. This mass defect is converted to energy according to Einstein's equation E = mc²."],
["A student uses the equation v = H₀d to calculate the recession speed of a galaxy 500 Mpc away, where H₀ = 70 km/s/Mpc. What is the recession speed?","35 000 km/s","7 km/s","500 km/s","70 km/s",0,"v = H₀ × d = 70 × 500 = 35 000 km/s. This is Hubble's law, which relates the recession speed of a galaxy to its distance."],
["Which of the following correctly describes the evidence for the Big Bang theory?","The universe is contracting","The cosmic microwave background radiation and red shift of distant galaxies both support the Big Bang","Only red shift supports the Big Bang","The universe has always existed in its current state",1,"Two key pieces of evidence support the Big Bang: (1) red shift of distant galaxies shows the universe is expanding; (2) the cosmic microwave background radiation is the remnant heat from the Big Bang itself."],
];

physQ.forEach(([q,a,b,c,d,ai,exp],i)=>{
  phys.push({id:`MCQ-PHYS-Y910-${String(i+1).padStart(3,'0')}`,domain:"Physics",topic:["Forces and Motion","Energy and Waves","Electricity and Magnetism","Nuclear and Space"][Math.floor(i/10)%4],difficulty:["Medium","Hard","Medium","Hard"][i%4],question:q,options:[a,b,c,d],answerIndex:ai,explanation:exp});
});

fs.writeFileSync('./phys-bank.json', JSON.stringify(phys, null, 2));
console.log(`Physics questions: ${phys.length}`);
