const fs = require('fs');
const chem2 = [];

const q = [
// ── Rates, Equilibrium & Energetics ──────────────────────────────────────
["A student investigates the reaction between sodium thiosulfate and hydrochloric acid. As concentration of sodium thiosulfate increases, the time for the solution to turn cloudy decreases. Which of the following correctly explains this?","Higher concentration lowers activation energy","Higher concentration increases the frequency of successful collisions between reactant particles","Higher concentration increases temperature","Higher concentration changes the products",1,"Collision theory: higher concentration means more particles per unit volume, increasing collision frequency. More collisions per second means more successful collisions (those exceeding activation energy), increasing reaction rate."],
["A student measures the enthalpy change of a neutralisation reaction using a polystyrene cup calorimeter. The temperature rises by 6.8°C when 50 mL of 1 mol/L HCl reacts with 50 mL of 1 mol/L NaOH. Using Q = mcΔT (c = 4.18 J/g°C, assume density = 1 g/mL), what is the heat released?","284 J","2843 J","568 J","142 J",1,"Q = mcΔT = 100 g × 4.18 J/g°C × 6.8°C = 2842.4 J ≈ 2843 J. The total mass is 100 mL × 1 g/mL = 100 g."],
["A student compares the activation energy of a catalysed and uncatalysed reaction on an energy profile diagram. Which of the following correctly describes the effect of the catalyst?","The catalyst raises the activation energy","The catalyst lowers the activation energy by providing an alternative reaction pathway","The catalyst changes the energy of the reactants","The catalyst changes the energy of the products",1,"A catalyst provides an alternative reaction pathway with lower activation energy. The energies of reactants and products are unchanged — only the energy barrier (activation energy) is reduced, allowing more collisions to be successful."],
["A student investigates the decomposition of hydrogen peroxide: 2H₂O₂ → 2H₂O + O₂. Adding manganese dioxide speeds up the reaction. After the reaction, the manganese dioxide is recovered unchanged. Which of the following correctly describes manganese dioxide in this reaction?","A reactant","A product","A catalyst","An inhibitor",2,"Manganese dioxide is a catalyst — it speeds up the reaction but is not consumed. It is recovered unchanged at the end, confirming it provides an alternative pathway with lower activation energy without being incorporated into products."],
["In the equilibrium N₂(g) + 3H₂(g) ⇌ 2NH₃(g), the forward reaction is exothermic. A student increases the pressure. According to Le Chatelier's principle, which of the following will occur?","Equilibrium shifts left, producing more N₂ and H₂","Equilibrium shifts right, producing more NH₃","Equilibrium position does not change with pressure","The reaction stops",1,"Increasing pressure favours the side with fewer moles of gas. Left side: 1 + 3 = 4 moles; right side: 2 moles. Equilibrium shifts right toward fewer moles (NH₃), reducing pressure."],
["A student investigates the effect of temperature on the equilibrium: A ⇌ B (exothermic forward reaction). Increasing temperature shifts equilibrium to the left. Which of the following correctly explains this?","Increasing temperature always shifts equilibrium right","Le Chatelier's principle: increasing temperature favours the endothermic (reverse) reaction to absorb the added heat","Increasing temperature increases the concentration of A","Increasing temperature has no effect on equilibrium",1,"Le Chatelier's principle: a system at equilibrium responds to oppose changes. Adding heat (increasing temperature) shifts equilibrium toward the endothermic direction (reverse reaction) to absorb the excess heat, reducing the temperature increase."],
["A student calculates the atom economy of a reaction: CH₄ + 2O₂ → CO₂ + 2H₂O. The desired product is CO₂ (Mr = 44). The total Mr of all products = 44 + 36 = 80. What is the atom economy?","55%","45%","80%","44%",0,"Atom economy = (Mr of desired product / total Mr of all products) × 100 = (44/80) × 100 = 55%."],
["Which of the following correctly explains why a higher percentage yield does not necessarily mean a more sustainable process?","Yield and sustainability are always related","A high yield reaction may still produce large amounts of toxic by-products or use non-renewable feedstocks — atom economy and green chemistry principles must also be considered","Sustainability only depends on energy use","Percentage yield only applies to industrial processes",1,"Percentage yield measures how much of the theoretical product is obtained. Atom economy measures how efficiently atoms are incorporated into the desired product. A high-yield reaction with low atom economy wastes resources and produces unwanted by-products."],
// ── Quantitative Chemistry ────────────────────────────────────────────────
["A student reacts 6 g of carbon with excess oxygen: C + O₂ → CO₂. What mass of CO₂ is produced? (Ar: C=12, O=16)","6 g","22 g","44 g","12 g",1,"Moles of C = 6/12 = 0.5 mol. From the equation, 1 mol C produces 1 mol CO₂. So 0.5 mol CO₂ is produced. Mass = 0.5 × 44 = 22 g."],
["A student dissolves 5.85 g of NaCl (Mr = 58.5) in water to make 500 mL of solution. What is the concentration of the solution?","0.1 mol/L","0.2 mol/L","1 mol/L","0.5 mol/L",1,"Moles NaCl = 5.85/58.5 = 0.1 mol. Volume = 500 mL = 0.5 L. Concentration = 0.1/0.5 = 0.2 mol/L."],
["In a reaction, 4.0 g of calcium reacts with excess hydrochloric acid: Ca + 2HCl → CaCl₂ + H₂. What volume of hydrogen gas is produced at STP? (Ar: Ca=40; molar volume at STP = 22.4 L/mol)","2.24 L","4.48 L","22.4 L","1.12 L",0,"Moles Ca = 4.0/40 = 0.1 mol. From equation, 1 mol Ca produces 1 mol H₂. So 0.1 mol H₂ produced. Volume = 0.1 × 22.4 = 2.24 L."],
["A student analyses a compound and finds it contains 40% carbon, 6.67% hydrogen and 53.33% oxygen by mass. The molar mass is 60 g/mol. What is the molecular formula? (Ar: C=12, H=1, O=16)","CH₂O","C₂H₄O₂","C₃H₆O₃","CHO",1,"Empirical formula: C=40/12=3.33, H=6.67/1=6.67, O=53.33/16=3.33. Ratio 1:2:1 → CH₂O (Mr=30). Molecular formula: 60/30=2, so C₂H₄O₂."],
// ── Materials & Electrochemistry ─────────────────────────────────────────
["A student electroplates a steel spoon with silver using silver nitrate solution. Which of the following correctly describes what happens at the cathode?","Silver ions are oxidised and deposited","Silver ions are reduced and deposited as silver metal on the spoon","The spoon dissolves into solution","Oxygen gas is produced",1,"At the cathode (negative electrode), Ag⁺ ions from solution gain electrons (reduction) and are deposited as silver metal on the spoon surface: Ag⁺ + e⁻ → Ag."],
["A student compares the properties of a thermoplastic and a thermosetting polymer. Which of the following correctly describes the difference?","Both can be remoulded when heated","Thermoplastics soften and can be remoulded when heated; thermosetting polymers form permanent cross-links and cannot be remoulded","Thermosetting polymers are always softer","Thermoplastics cannot be recycled",1,"Thermoplastics (e.g. polyethylene) have polymer chains held by weak intermolecular forces that break on heating, allowing remoulding. Thermosetting polymers (e.g. Bakelite) form covalent cross-links during curing, creating a rigid, permanent structure that cannot be remoulded."],
["A student investigates corrosion of iron. Iron rusts faster in salt water than in pure water. Which of the following correctly explains this?","Salt water is more acidic","Salt water contains ions that increase electrical conductivity, accelerating the electrochemical corrosion process","Salt water contains more oxygen","Salt water is denser",1,"Rusting is an electrochemical process. Salt water contains dissolved ions (Na⁺, Cl⁻) that increase electrical conductivity, allowing electrons to flow more easily between anodic and cathodic regions on the iron surface, accelerating the oxidation of iron."],
["Which of the following correctly explains why aluminium does not corrode as readily as iron despite being a more reactive metal?","Aluminium is less reactive than iron","Aluminium forms a thin, adherent oxide layer (Al₂O₃) that protects the surface from further oxidation","Aluminium is coated with zinc","Aluminium does not react with oxygen",1,"Aluminium reacts rapidly with oxygen to form a thin, dense, adherent layer of aluminium oxide (Al₂O₃). This layer is impermeable to oxygen and water, preventing further oxidation — unlike iron oxide (rust), which is porous and flaky."],
// ── Organic Chemistry Extended ────────────────────────────────────────────
["A student reacts ethene with bromine water. The bromine water is decolourised. Which type of reaction has occurred and what is the product?","Substitution; dibromoethane","Addition; 1,2-dibromoethane","Elimination; bromoethene","Combustion; CO₂ and H₂O",1,"Alkenes undergo addition reactions across the C=C double bond. Bromine adds across the double bond: CH₂=CH₂ + Br₂ → CH₂BrCH₂Br (1,2-dibromoethane). The decolourisation of bromine water is the test for unsaturation."],
["A student compares the boiling points of ethanol (78°C) and dimethyl ether (−24°C), which are structural isomers (both C₂H₆O). Which of the following correctly explains the large difference?","Ethanol has a higher molar mass","Ethanol molecules form hydrogen bonds through the –OH group; dimethyl ether cannot form hydrogen bonds as there is no O–H bond","Dimethyl ether has stronger van der Waals forces","Ethanol is more polar overall",1,"Ethanol has an –OH group where the hydrogen is bonded directly to oxygen, enabling hydrogen bonding between molecules. Dimethyl ether (CH₃–O–CH₃) has no O–H bond, so it cannot form hydrogen bonds. Hydrogen bonds are much stronger than van der Waals forces, giving ethanol a much higher boiling point."],
["A student investigates the hydrolysis of an ester using dilute acid. Which of the following correctly describes the products?","An alkene and water","The original alcohol and carboxylic acid","A new ester and water","A polymer and water",1,"Ester hydrolysis (the reverse of esterification) breaks the ester bond using water (with acid or base catalyst), regenerating the original alcohol and carboxylic acid. Acid hydrolysis is reversible; base hydrolysis (saponification) is irreversible."],
["Which of the following correctly explains why long-chain saturated fats are solid at room temperature while short-chain unsaturated fats are liquid?","Saturated fats have more oxygen","Longer saturated chains have greater van der Waals forces and pack closely together; unsaturated fats have C=C double bonds that create kinks, preventing close packing and reducing intermolecular forces","Unsaturated fats have higher molar masses","Saturated fats contain more hydrogen bonds",1,"Saturated fatty acid chains are straight and pack closely, maximising van der Waals forces — solid at room temperature. C=C double bonds in unsaturated fats create kinks that prevent close packing, reducing intermolecular forces — liquid at room temperature."],
["A student tests an unknown organic compound with Fehling's solution and gets a brick-red precipitate. Which functional group is most likely present?","Carboxylic acid (–COOH)","Aldehyde (–CHO)","Alcohol (–OH)","Ketone (C=O)",1,"Fehling's solution is reduced by aldehydes (–CHO) to form a brick-red precipitate of copper(I) oxide. Ketones do not reduce Fehling's solution. This test distinguishes aldehydes from ketones."],
];

q.forEach(([question,a,b,c,d,ai,explanation],i)=>{
  const topics = ['Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Reactions and Energy','Quantitative Chemistry','Quantitative Chemistry','Quantitative Chemistry','Quantitative Chemistry','Electrochemistry','Materials','Corrosion','Corrosion','Organic Chemistry','Organic Chemistry','Organic Chemistry','Organic Chemistry','Organic Chemistry'];
  chem2.push({id:`MCQ-CHEM2-Y910-${String(i+1).padStart(3,'0')}`,domain:"Chemistry",topic:topics[i]||'Chemistry',difficulty:i%2===0?"Medium":"Hard",question,options:[a,b,c,d],answerIndex:ai,explanation});
});

fs.writeFileSync('./chem2-bank.json', JSON.stringify(chem2,null,2));
console.log(`Chem2 questions: ${chem2.length}`);
