const fs = require('fs');
const wb = JSON.parse(fs.readFileSync('./written-banks.json','utf8'));

// Convert AR from string array to object array first
if (typeof wb.AR[0] === 'string') {
  wb.AR = wb.AR.map(task => ({ task, modelAnswer: 'See marking guide.' }));
}

const answers = {
0: "Aim: To investigate the effect of temperature on enzyme activity.\nObservation: Enzyme activity increased steadily as temperature rose, reaching a peak at the optimum temperature (~37°C), after which activity declined sharply.\nExplanation: Rising temperature increases the kinetic energy of enzyme and substrate molecules, raising collision frequency and reaction rate. Above the optimum, the enzyme's tertiary structure is disrupted — hydrogen and ionic bonds maintaining the active site shape break (denaturation) — so substrate molecules can no longer bind effectively.\nConclusion: Enzyme activity peaks at an optimum temperature and falls rapidly above it due to denaturation. This relationship is non-linear and irreversible above the denaturation point.",
1: "Aim: To investigate the effect of light intensity on plant growth rate.\nObservation: Plant growth increased as light intensity increased, but the rate of growth levelled off beyond a certain point, forming a plateau.\nExplanation: At low light intensity, light is the limiting factor for photosynthesis — insufficient ATP and NADPH are produced for the Calvin cycle. As intensity increases, more light energy drives the light-dependent reactions. Once light is no longer limiting, another factor — CO2 concentration, temperature or enzyme concentration — restricts further increase.\nConclusion: Light intensity promotes plant growth only up to the point where another factor becomes limiting. Beyond that threshold, additional light produces no further increase in growth rate.",
2: "Aim: To investigate the effect of reactant concentration on reaction rate.\nObservation: As concentration increased, the reaction rate increased consistently across all trials.\nExplanation: Higher concentration means more reactant particles per unit volume. This increases the frequency of collisions between reacting particles and raises the probability of successful collisions (those with energy ≥ activation energy), so the reaction proceeds more quickly.\nConclusion: Reactant concentration has a direct positive effect on reaction rate. This is consistent with collision theory, which predicts that more particles in a given volume will collide more often, increasing reaction rate.",
3: "Aim: To investigate the relationship between water temperature and dissolved oxygen concentration.\nObservation: As water temperature increased, the concentration of dissolved oxygen decreased in a consistent pattern.\nExplanation: At higher temperatures, water molecules move faster and gas molecules gain sufficient kinetic energy to escape from solution into the atmosphere. This reduces the amount of oxygen that remains dissolved. Henry's law states that gas solubility decreases with increasing temperature.\nConclusion: Water temperature and dissolved oxygen concentration are inversely related. This finding is ecologically important because rising water temperatures due to climate change may reduce oxygen availability for aquatic life, threatening fish and other aerobic organisms.",
4: "Aim: To investigate the effect of adding bulbs in series on the brightness of individual bulbs.\nObservation: Each bulb became progressively dimmer as additional bulbs were added to the series circuit.\nExplanation: In a series circuit, all components share the same current. Adding more bulbs increases the total resistance of the circuit. By Ohm's law (V = IR), increased resistance reduces the current for a fixed voltage. With less current flowing, each bulb receives less power (P = I²R) and produces less light.\nConclusion: Adding bulbs in series reduces the brightness of each bulb because total resistance increases and current decreases. This demonstrates the relationship between resistance, current and power in series circuits.",
5: "Aim: To investigate how sound intensity changes with distance from the source.\nObservation: Sound intensity decreased as the measuring device was moved further from the source, with the decrease becoming less steep at greater distances.\nExplanation: Sound energy spreads outward in all directions from its source. As distance increases, the same amount of energy is distributed over a larger surface area (proportional to 4πr²). This means less energy reaches any given point, so measured intensity falls. The relationship follows an inverse square law — doubling the distance reduces intensity to approximately one quarter.\nConclusion: Sound intensity decreases with distance from the source because energy spreads over an increasing area. This principle applies to all wave phenomena that radiate from a point source.",
6: "Aim: To investigate the effect of temperature on seed germination rate.\nObservation: Germination rate was highest at a moderate temperature (~20-25°C), with lower rates observed at both low and high temperature extremes.\nExplanation: Germination depends on enzyme-controlled biochemical reactions. At low temperatures, enzyme activity is reduced because molecules have less kinetic energy and collide less frequently. At high temperatures, enzymes may denature, disrupting the reactions needed for germination. At the optimum temperature, enzyme activity is maximised.\nConclusion: Seed germination rate is temperature-dependent, with a clear optimum. Temperatures above or below this optimum reduce germination rate, consistent with the effect of temperature on enzyme-controlled reactions.",
7: "Aim: To investigate the pH of three unknown solutions.\nObservation: Solution A (pH 3) is acidic; Solution B (pH 7) is neutral; Solution C (pH 11) is alkaline.\nExplanation: The pH scale measures hydrogen ion concentration: pH = -log[H⁺]. pH 3 indicates [H⁺] = 10⁻³ mol/L — strongly acidic. pH 7 indicates equal H⁺ and OH⁻ concentrations — neutral. pH 11 indicates [H⁺] = 10⁻¹¹ mol/L — strongly alkaline. Each unit represents a tenfold change in [H⁺].\nConclusion: The three solutions span the pH scale from acidic to alkaline. Solution A could be vinegar or lemon juice; B could be pure water; C could be bleach or ammonia solution.",
8: "Aim: To analyse predator-prey population dynamics over time.\nObservation: Predator and prey populations oscillate with predator peaks following prey peaks by approximately 1-2 years.\nExplanation: When prey is abundant, predators have plentiful food, improving survival and reproduction — predator population grows. Increased predation reduces prey numbers. With less food, predator survival declines — predator population falls. Reduced predation allows prey to recover. The time lag occurs because population responses take time — generation time delays the predator response to prey changes.\nConclusion: Predator-prey populations show classic oscillating cycles. The time lag between prey and predator peaks reflects the time required for population growth responses. This demonstrates the interdependence of species in ecosystems.",
9: "Aim: To investigate the effect of fertiliser concentration on crop yield.\nObservation: Yield increased to a maximum then declined at high concentrations.\nExplanation: Moderate fertiliser supplies limiting nutrients (nitrogen, phosphorus, potassium), increasing photosynthesis and growth. At optimal concentration, all nutrient requirements are met. Excess fertiliser increases soil solute concentration, lowering soil water potential below that of root cells — water leaves roots by osmosis (plasmolysis), causing wilting and reduced yield.\nConclusion: An optimal fertiliser concentration exists beyond which yield is reduced due to osmotic stress. This has practical implications for agriculture — over-fertilisation wastes resources and reduces yield.",
10: "Aim: To investigate the relationship between vaccination rate and disease incidence.\nObservation: Countries with higher vaccination rates have significantly lower rates of the target disease.\nExplanation: Vaccination stimulates immune memory without causing disease. High vaccination rates create herd immunity — when a sufficient proportion of the population is immune, transmission chains are broken, protecting unvaccinated individuals. The threshold for herd immunity varies by disease (measles requires ~95% coverage).\nConclusion: The negative correlation between vaccination rate and disease incidence supports vaccine effectiveness. However, correlation does not prove causation — confounding factors such as healthcare quality must be considered. The pattern is consistent across multiple independent datasets, strengthening the causal interpretation.",
11: "Aim: To investigate the effect of pendulum mass on its period.\nObservation: Period remained constant regardless of mass across all trials.\nExplanation: Pendulum period is determined by T = 2π√(L/g), where L is length and g is gravitational acceleration. Mass does not appear in this equation. Gravitational force on a heavier pendulum is greater, but so is its inertia — these effects cancel exactly, leaving period independent of mass.\nConclusion: Mass does not affect pendulum period, consistent with theoretical prediction. This result demonstrates that gravitational acceleration acts equally on all masses — a fundamental principle confirmed by Galileo's experiments.",
12: "Aim: To investigate the effect of soil salt concentration on plant growth.\nObservation: Growth decreased as salt concentration increased.\nExplanation: High salt concentration lowers soil water potential below that of root cells. Water moves out of root cells by osmosis (down the water potential gradient), causing plasmolysis. Dehydrated cells cannot maintain turgor pressure, wilting occurs, and metabolic processes are disrupted. High salt also causes ion toxicity.\nConclusion: Excess soil salinity inhibits plant growth through osmotic stress and ion toxicity. This explains why agricultural land can become unproductive through salinisation from irrigation with mineral-rich water.",
13: "Aim: To investigate the cooling curve of a substance undergoing a phase change.\nObservation: Temperature decreased steadily, then remained constant at 45°C for a period, then continued to decrease.\nExplanation: The flat section at 45°C represents the freezing point of the substance. During this phase change, the substance releases latent heat of fusion at a constant temperature as liquid converts to solid. The energy released during bond formation exactly compensates for heat loss to the surroundings, maintaining constant temperature until all liquid has solidified.\nConclusion: The flat section indicates a phase change at the freezing point. Temperature only continues to fall once all liquid has solidified and no more latent heat is being released.",
14: "Aim: To investigate the relationship between deforestation rate and atmospheric CO2 levels.\nObservation: Areas with higher deforestation rates have higher atmospheric CO2 levels.\nExplanation: Forests store carbon in biomass. When trees are burned or decompose, stored carbon is released as CO2. Deforestation also reduces the number of trees available to absorb CO2 through photosynthesis. Both effects increase atmospheric CO2 concentration.\nConclusion: Deforestation and atmospheric CO2 are positively correlated. This relationship has implications for climate change — protecting and restoring forests is a key strategy for reducing atmospheric CO2. However, correlation does not prove causation; other factors (industrial emissions, geography) may also contribute.",
15: "Aim: To investigate the dispersion of white light through a prism.\nObservation: White light entering the prism produced a continuous spectrum of colours from red to violet on the other side.\nExplanation: White light is composed of all visible wavelengths. When light enters the glass prism, it refracts (changes speed and direction). Different wavelengths travel at different speeds in glass — violet light slows more than red light (higher refractive index for shorter wavelengths). This differential refraction (dispersion) separates the wavelengths, producing a spectrum.\nConclusion: White light is composed of multiple wavelengths that are separated by the prism due to their different refractive indices in glass. This demonstrates that white light is not a single colour but a mixture of all visible wavelengths.",
16: "Aim: To investigate thermal expansion of a metal rod.\nObservation: Rod length increased measurably with temperature in a consistent, approximately linear relationship.\nExplanation: Heating increases the kinetic energy of metal atoms, causing them to vibrate more vigorously and occupy more space. The increased atomic vibration pushes atoms further apart on average, increasing the macroscopic dimensions of the rod. The coefficient of linear thermal expansion (α) describes this relationship: ΔL = αLΔT.\nConclusion: Metals expand when heated due to increased atomic vibration, consistent with thermal expansion theory. This has practical implications for engineering — bridges, railway tracks and pipelines must accommodate thermal expansion through expansion joints.",
17: "Aim: To classify five unknown substances using litmus and universal indicator.\nObservation: Substances turning litmus red and universal indicator orange/red are acidic; blue litmus and green/blue universal indicator indicates neutral to alkaline.\nExplanation: Litmus is a pH indicator that turns red in acid (pH < 7) and blue in alkali (pH > 7). Universal indicator gives a colour corresponding to pH across the full scale. Combining both results allows classification as strongly acidic (pH 1-3), weakly acidic (pH 4-6), neutral (pH 7), weakly alkaline (pH 8-10) or strongly alkaline (pH 11-14).\nConclusion: The two indicators together provide more information than either alone. Universal indicator gives approximate pH; litmus confirms acid/alkali classification. This method is a simple, reliable way to classify unknown solutions.",
18: "Aim: To investigate the relationship between screen time and sleep quality in teenagers.\nObservation: Data shows a positive correlation between screen time and reported sleep problems.\nExplanation: Possible mechanisms include: blue light from screens suppresses melatonin production, delaying sleep onset; mentally stimulating content delays sleep; social media use causes anxiety. However, correlation does not establish causation — reverse causation is possible (poor sleepers may use screens more to pass time); confounding variables (stress, caffeine, exercise) may explain both.\nConclusion: The positive correlation suggests increased screen time is associated with more sleep problems. However, the study design (survey/observational) cannot establish causation. Controlled experimental studies are needed to determine whether screen time directly causes sleep problems.",
19: "Aim: To investigate the effect of CO2 concentration on photosynthesis rate.\nObservation: Rate increased with CO2 concentration then plateaued.\nExplanation: At low CO2, carbon dioxide is the limiting factor for the Calvin cycle — RuBisCO cannot fix sufficient CO2 to maximise ATP and NADPH use. As CO2 increases, the Calvin cycle runs faster. At the plateau, another factor — light intensity, temperature or enzyme concentration — becomes limiting.\nConclusion: CO2 promotes photosynthesis only until another factor limits the rate. This demonstrates the concept of limiting factors — the rate of a biological process is determined by the factor in shortest supply.",
20: "Aim: To investigate whether mass affects free-fall time.\nObservation: All objects fell in approximately equal time regardless of mass.\nExplanation: In free fall, gravitational acceleration g = 9.8 m/s² acts equally on all masses regardless of weight. This is because gravitational force is proportional to mass (F = mg), but so is inertia (F = ma) — the two effects cancel exactly. Air resistance differences for similar-shaped objects are negligible over short distances.\nConclusion: Mass does not affect free-fall time, consistent with Galileo's principle and Newton's laws. This result demonstrates the equivalence of gravitational and inertial mass — a fundamental principle of physics confirmed by Galileo's experiments at the Leaning Tower of Pisa.",
21: "Aim: To investigate the effect of exercise on heart rate.\nObservation: Heart rate increased with exercise intensity and returned to resting rate during recovery.\nExplanation: During exercise, muscles require more oxygen and produce more CO2. Rising CO2 lowers blood pH, detected by chemoreceptors in the medulla oblongata and aortic arch. The medulla signals the sinoatrial node to increase heart rate, delivering more oxygenated blood to muscles and removing CO2 more rapidly.\nConclusion: Heart rate increases proportionally with exercise intensity to meet increased metabolic demands. Recovery time reflects the time needed to clear CO2 and lactic acid and restore homeostasis. This demonstrates the cardiovascular system's role in maintaining homeostasis during exercise.",
22: "Aim: To investigate the relationship between habitat disturbance and species diversity.\nObservation: Species diversity was significantly higher in undisturbed habitats than in disturbed ones.\nExplanation: Disturbance (clearing, pollution, fragmentation) destroys habitat structure, eliminates specialist species requiring specific conditions, and favours generalist species. Undisturbed habitats provide diverse microhabitats, food sources and nesting sites supporting a wider range of species. The intermediate disturbance hypothesis suggests moderate disturbance can maximise diversity, but severe disturbance reduces it.\nConclusion: Habitat disturbance reduces species diversity by eliminating specialist species and simplifying habitat structure. This supports the importance of habitat protection for biodiversity conservation.",
23: "Aim: To investigate the extension of a spring under different loads.\nObservation: Extension was proportional to load up to 6 N (linear relationship), beyond which the relationship became non-linear.\nExplanation: Up to the elastic limit, the spring obeys Hooke's law: F = kx, where k is the spring constant. The spring stores elastic potential energy and returns to its original length when the load is removed. Beyond the elastic limit, the spring is permanently deformed — the coils are stretched beyond their elastic range.\nConclusion: The spring obeys Hooke's law up to the elastic limit. Beyond this point, permanent deformation occurs. The spring constant k = gradient of the linear section = F/x.",
24: "Aim: To investigate the effect of surface area on reaction rate.\nObservation: Powdered calcium carbonate reacted faster than lumps of the same mass.\nExplanation: Smaller particles have greater surface area exposed to the acid. More reactant particles are available for collisions with acid molecules, increasing the frequency of successful collisions per unit time. The total amount of reactant is the same, so the final amount of product is identical — only the rate differs.\nConclusion: Increasing surface area increases reaction rate by increasing collision frequency. This is consistent with collision theory and has practical applications in industrial chemistry, where reactants are often ground to powder to maximise reaction rate.",
};

Object.entries(answers).forEach(([i, ans]) => {
  wb.AR[parseInt(i)].modelAnswer = ans;
});

fs.writeFileSync('./written-banks.json', JSON.stringify(wb, null, 2));
const done = wb.AR.filter(x => x.modelAnswer && x.modelAnswer !== 'See marking guide.').length;
console.log(`AR model answers done: ${done}/147`);
