const fs = require('fs');
const earth = [];

const earthQ = [
// ── Earth Science & Climate ───────────────────────────────────────────────
["A student analyses ice core data and finds that CO2 levels and temperature have risen and fallen together over 800 000 years. Which of the following is the most appropriate conclusion?","CO2 causes temperature change only","Temperature causes CO2 change only","There is a strong correlation between CO2 and temperature over geological time","CO2 and temperature are unrelated",2,"Ice core data shows a strong positive correlation between CO2 and temperature over 800 000 years. While the relationship is complex (each can drive the other), the correlation is robust evidence for the greenhouse effect."],
["Which of the following correctly explains why the ocean absorbs CO2 from the atmosphere?","CO2 is heavier than air and sinks into the ocean","CO2 dissolves in seawater to form carbonic acid, driven by the concentration gradient","The ocean produces CO2","CO2 is absorbed only by marine plants",1,"CO2 dissolves in seawater according to Henry's law, forming carbonic acid (H₂CO₃). The concentration gradient between atmosphere and ocean surface drives net absorption when atmospheric CO2 is higher."],
["A student investigates ocean acidification. As CO2 dissolves in seawater, pH decreases. Which of the following correctly explains the impact on coral reefs?","Lower pH increases calcium carbonate availability for coral","Lower pH dissolves calcium carbonate shells and skeletons, threatening coral and shellfish","Lower pH has no effect on marine organisms","Lower pH increases photosynthesis in coral",1,"Ocean acidification reduces carbonate ion concentration, making it harder for corals and shellfish to build calcium carbonate (CaCO₃) shells and skeletons. Existing structures may also dissolve."],
["Which of the following correctly describes the difference between weather and climate?","Weather is long-term; climate is short-term","Climate is the average weather pattern over a long period (30+ years); weather is day-to-day atmospheric conditions","They are the same thing","Climate only refers to temperature",1,"Weather describes short-term atmospheric conditions (today's rain, tomorrow's temperature). Climate is the statistical average of weather patterns over at least 30 years for a region."],
["A student compares the albedo of fresh snow (0.85) and ocean water (0.06). Which of the following correctly explains the significance of this difference for climate?","Snow absorbs more solar energy than ocean water","Ocean water reflects more solar energy than snow","As ice melts due to warming, darker ocean is exposed, absorbing more energy and accelerating warming — a positive feedback loop","Snow and ocean water have the same effect on climate",2,"The ice-albedo feedback: melting ice exposes darker ocean (lower albedo), which absorbs more solar energy, causing further warming and more melting. This is a positive feedback that amplifies climate change."],
["Which of the following correctly describes the rock cycle?","Rocks are permanently fixed in one form","Rocks are continuously transformed between igneous, sedimentary and metamorphic forms through geological processes","Only igneous rocks can become sedimentary","The rock cycle only operates at plate boundaries",1,"The rock cycle describes the continuous transformation of rocks: magma cools to form igneous rock; weathering and erosion produce sediment that forms sedimentary rock; heat and pressure transform rocks into metamorphic rock; melting restarts the cycle."],
["A student investigates the distribution of earthquakes and volcanoes on a world map. Which of the following correctly describes the pattern?","They are randomly distributed","They are concentrated along tectonic plate boundaries","They only occur in the Southern Hemisphere","They only occur in ocean basins",1,"Earthquakes and volcanoes are concentrated along tectonic plate boundaries where plates converge, diverge or slide past each other. This distribution was key evidence for plate tectonic theory."],
["Which of the following correctly explains how convection currents in the mantle drive plate movement?","The mantle is solid and does not move","Hot mantle material rises, spreads laterally, cools and sinks, dragging tectonic plates with it","Plates are pushed by the rotation of the Earth","Plates float on liquid water beneath the crust",1,"Convection currents in the semi-fluid mantle are driven by heat from Earth's core. Hot material rises at mid-ocean ridges, spreads laterally and cools, sinking at subduction zones. This movement drags tectonic plates."],
["A student compares the age of seafloor rocks at different distances from a mid-ocean ridge. Which of the following correctly describes the pattern?","Rocks are oldest near the ridge","Rocks are youngest near the ridge and get older with distance","All rocks are the same age","Age is unrelated to distance from the ridge",1,"Seafloor spreading produces new oceanic crust at mid-ocean ridges. As new material is added, older crust moves away from the ridge. This produces a pattern of increasing age with distance from the ridge."],
["Which of the following correctly describes the greenhouse effect?","The atmosphere reflects all solar radiation back to space","Greenhouse gases absorb outgoing infrared radiation from Earth's surface and re-emit it, warming the lower atmosphere","The ozone layer traps heat","The greenhouse effect is entirely human-caused",1,"The natural greenhouse effect: solar radiation passes through the atmosphere and warms Earth's surface. The surface emits infrared radiation, which is absorbed by greenhouse gases (CO₂, H₂O, CH₄) and re-emitted in all directions, warming the lower atmosphere."],
// ── Scientific Method & Data Analysis ────────────────────────────────────
["A student investigates the effect of fertiliser concentration on plant growth. They keep temperature, light, water volume and pot size the same for all plants. What are these kept-constant factors called?","Independent variables","Dependent variables","Control variables","Anomalous results",2,"Control variables are factors that are kept constant throughout an experiment to ensure that any change in the dependent variable is caused only by the independent variable."],
["A student repeats an experiment five times and gets results of 23, 24, 25, 23 and 24 cm. Which of the following correctly describes these results?","Accurate but not precise","Precise but not necessarily accurate","Neither precise nor accurate","Both precise and accurate",1,"Precision refers to how close repeated measurements are to each other. These results are clustered closely (23-25 cm), so they are precise. Whether they are accurate depends on the true value, which is not given."],
["A student's results show a clear outlier. Which of the following is the most appropriate action?","Include it in the mean calculation","Ignore it without investigation","Investigate whether it was caused by an error; if so, exclude it from the mean","Report only the outlier",2,"An outlier should be investigated. If it resulted from an identifiable error (equipment fault, recording mistake), it should be excluded from the mean. If no cause is found, it should be reported but may still be excluded."],
["A student plots a scatter graph and draws a line of best fit. The line does not pass through the origin. Which of the following correctly describes what the y-intercept represents?","The gradient of the line","The value of the dependent variable when the independent variable is zero","The maximum value of the data","The anomalous result",1,"The y-intercept is the value of the dependent variable (y-axis) when the independent variable (x-axis) equals zero. It may represent a systematic error or a genuine feature of the relationship."],
["A student finds a positive correlation between two variables. Which of the following is the most appropriate conclusion?","One variable causes the other to change","The two variables are related — as one increases, the other tends to increase — but correlation does not prove causation","The relationship is definitely causal","The variables are unrelated",1,"Correlation shows a statistical relationship between variables but does not establish causation. A third variable (confounding factor) may cause both, or the correlation may be coincidental."],
["A student measures the boiling point of water five times: 99.8, 100.1, 99.9, 100.0 and 100.2°C. The true boiling point is 100°C. Which of the following correctly describes these measurements?","Precise and accurate","Precise but not accurate","Accurate but not precise","Neither precise nor accurate",0,"The measurements are clustered closely together (precise) and their mean (100.0°C) is very close to the true value (accurate). These results are both precise and accurate."],
["A student investigates whether a new fertiliser increases crop yield. They test it on 5 plants. A scientist suggests using 50 plants instead. Which of the following best explains why?","Larger sample size reduces the effect of random variation and makes results more reliable","Larger sample size increases accuracy of individual measurements","Larger sample size changes the independent variable","Larger sample size reduces the need for control variables",0,"A larger sample size reduces the effect of random variation (chance differences between individual plants). Results from 50 plants are more likely to represent the true effect of the fertiliser than results from 5 plants."],
["A student uses a ruler with 1 mm graduations to measure the length of a leaf. Which of the following correctly states the appropriate uncertainty for a single measurement?","±0.001 mm","±0.5 mm","±1 mm","±5 mm",1,"The uncertainty of a measurement made with an analogue instrument is typically ±half the smallest graduation. For a ruler with 1 mm graduations, uncertainty = ±0.5 mm."],
["A student investigates the effect of temperature on enzyme activity. They use a water bath to control temperature. Which of the following correctly identifies the independent variable?","Enzyme activity","Temperature","The type of enzyme","The volume of substrate",1,"The independent variable is the variable deliberately changed by the experimenter. In this investigation, the student changes the temperature to see its effect on enzyme activity."],
["A student calculates the percentage error of a measurement. The true value is 50 cm and the measured value is 48 cm. What is the percentage error?","2%","4%","96%","0.04%",1,"Percentage error = (|measured - true| / true) × 100 = (|48 - 50| / 50) × 100 = (2/50) × 100 = 4%."],
// ── Interdisciplinary Science Reasoning ───────────────────────────────────
["A student investigates the effect of pH on the rate of a chemical reaction catalysed by an enzyme. The rate is highest at pH 7 and decreases at both lower and higher pH values. Which of the following best explains the decrease at high pH?","More H⁺ ions are available at high pH","The enzyme's active site changes shape (denatures) at extreme pH, reducing its ability to bind substrate","The substrate concentration decreases at high pH","The temperature increases at high pH",1,"Extreme pH values disrupt the ionic and hydrogen bonds that maintain the enzyme's tertiary structure. The active site changes shape, reducing the enzyme-substrate complementarity and reaction rate."],
["A student compares the energy content of glucose and fat. Fat contains approximately twice the energy per gram. Which of the following correctly explains this?","Fat molecules contain more water","Fat molecules have a higher proportion of C-H bonds, which release more energy when oxidised","Fat is denser than glucose","Glucose contains nitrogen",1,"Fat (lipid) molecules have a higher ratio of hydrogen to oxygen than carbohydrates. C-H bonds release more energy when oxidised than C-OH bonds, giving fat a higher energy density per gram."],
["A student investigates the effect of light intensity on the rate of photosynthesis and respiration in a plant. At the compensation point, which of the following is true?","Photosynthesis rate exceeds respiration rate","Respiration rate exceeds photosynthesis rate","The rate of photosynthesis equals the rate of respiration","The plant produces no CO₂",2,"The compensation point is the light intensity at which the rate of photosynthesis exactly equals the rate of respiration. Net gas exchange is zero — all CO₂ produced by respiration is used in photosynthesis."],
["A student analyses data showing that a species of bird has a beak size that has increased over 20 years during a period of drought when only large, hard seeds were available. Which of the following correctly explains this observation?","Individual birds grew larger beaks in response to the drought","Birds with larger beaks were better able to crack hard seeds, survived and reproduced more, passing the large-beak alleles to offspring","All birds developed larger beaks through mutation","The drought caused a change in the birds' DNA",1,"This is natural selection in action. Pre-existing variation in beak size meant birds with larger beaks could access food during drought. They survived and reproduced, increasing the frequency of large-beak alleles over generations."],
["A student investigates the solubility of a gas in water at different temperatures. Solubility decreases as temperature increases. Which of the following correctly applies this finding to a real-world context?","Warmer rivers will have more dissolved oxygen, supporting more fish","Warmer rivers will have less dissolved oxygen, potentially harming aquatic life","Temperature has no effect on aquatic ecosystems","Dissolved oxygen increases with temperature",1,"As water temperature rises (e.g. due to climate change or thermal pollution), dissolved oxygen decreases. This can cause hypoxic conditions that stress or kill fish and other aerobic aquatic organisms."],
["A student compares the half-lives of two radioactive isotopes: iodine-131 (half-life 8 days) and carbon-14 (half-life 5730 years). Which of the following correctly explains why iodine-131 is used in medical treatment but not carbon-14?","Carbon-14 is more radioactive","Iodine-131 decays quickly enough to treat disease without exposing the patient to long-term radiation; carbon-14 would remain radioactive for thousands of years","Carbon-14 is too expensive","Iodine-131 emits gamma radiation only",1,"For medical use, a short half-life is desirable — the isotope delivers its therapeutic effect and then decays to safe levels quickly. Carbon-14's 5730-year half-life would expose patients to radiation for an unacceptably long time."],
["A student investigates the effect of increasing CO2 concentration on the rate of photosynthesis. Rate increases then plateaus. Which of the following correctly explains the plateau?","CO2 becomes toxic at high concentrations","Another factor (light intensity or temperature) becomes limiting","The plant runs out of water","CO2 destroys chlorophyll",1,"When CO2 is no longer the limiting factor, another variable (light intensity, temperature or enzyme concentration) limits the rate. Increasing CO2 further has no effect until the new limiting factor is addressed."],
["A student analyses data from a clinical trial of a new drug. The trial uses a double-blind, randomised, placebo-controlled design. Which of the following correctly explains why this design is used?","To reduce the cost of the trial","To eliminate bias from both participants and researchers, and to separate the drug's effect from the placebo effect","To increase the number of participants","To avoid using statistics",1,"Double-blind design prevents both participants and researchers from knowing who receives the drug, eliminating expectation bias. The placebo control separates the drug's pharmacological effect from psychological effects of receiving treatment."],
["A student measures the electrical resistance of a solution of sodium chloride at different concentrations. Resistance decreases as concentration increases. Which of the following correctly explains this?","More water molecules carry charge at higher concentrations","More ions are present at higher concentrations, providing more charge carriers","Salt molecules conduct electricity","Higher concentration increases temperature",1,"Electrical conductivity in ionic solutions depends on the number of ions available to carry charge. Higher NaCl concentration means more Na⁺ and Cl⁻ ions, reducing resistance and increasing conductivity."],
["A student investigates the effect of exercise on blood lactate concentration. Lactate increases sharply above a certain exercise intensity (the lactate threshold). Which of the following correctly explains this?","Aerobic respiration produces lactate","Below the threshold, aerobic respiration meets energy demands; above it, anaerobic respiration supplements energy production, generating lactate faster than it can be cleared","Lactate is produced by the liver during exercise","The heart produces lactate during exercise",1,"At low-moderate intensity, aerobic respiration meets energy demands with no lactate accumulation. Above the lactate threshold, oxygen delivery is insufficient and anaerobic respiration produces lactate faster than the body can remove it."],
["A student compares the efficiency of energy transfer in a food chain: grass → cow → human. Which of the following correctly explains why eating plants directly is more energy-efficient than eating beef?","Plants contain more protein than beef","Each trophic level loses approximately 90% of energy as heat and waste; eating plants skips one energy-losing step","Cows destroy energy","Humans cannot digest beef efficiently",1,"Only ~10% of energy transfers between trophic levels. Eating plants (one transfer) is far more efficient than eating beef (two transfers: plant→cow→human). This is why plant-based diets have a lower environmental footprint."],
];

earthQ.forEach(([q,a,b,c,d,ai,exp],i)=>{
  earth.push({id:`MCQ-EARTH-Y910-${String(i+1).padStart(3,'0')}`,domain:"Earth Science",topic:["Earth and Climate","Scientific Method","Interdisciplinary"][Math.floor(i/10)%3],difficulty:["Medium","Hard","Medium","Hard"][i%4],question:q,options:[a,b,c,d],answerIndex:ai,explanation:exp});
});

fs.writeFileSync('./earth-bank.json', JSON.stringify(earth, null, 2));
console.log(`Earth Science questions: ${earth.length}`);
