const fs = require('fs');

const biology = [];
const chemistry = [];
const physics = [];
const earth = [];

// ── BIOLOGY CELL BIOLOGY ──────────────────────────────────────────────────────
const bioCellQ = [
  ["Which organelle produces ATP?","Nucleus","Mitochondria","Ribosome","Vacuole",1],
  ["What controls entry/exit of substances in a cell?","Cell wall","Nucleus","Cell membrane","Cytoplasm",2],
  ["Which organelle contains DNA?","Ribosome","Nucleus","Golgi","Lysosome",1],
  ["What do ribosomes make?","Lipids","Carbohydrates","Proteins","ATP",2],
  ["Which organelle is only in plant cells?","Lysosome","Mitochondria","Chloroplast","Ribosome",2],
  ["Osmosis moves water from ___ to ___ concentration","low to high","high to low","equal to equal","none",1],
  ["Endocytosis brings large molecules ___ the cell","out of","into","around","through",1],
  ["Cytoplasm is described as","solid","crystalline","gel-like","gaseous",2],
  ["Which organelle modifies and packages proteins?","Rough ER","Smooth ER","Golgi apparatus","Lysosome",2],
  ["Plant cell structural support comes from","Cell membrane","Cell wall","Cytoplasm","Nucleus",1],
  ["Lysosomes contain","DNA","digestive enzymes","chlorophyll","ATP",1],
  ["Prokaryotic cells lack a","ribosome","cell membrane","nucleus","cytoplasm",2],
  ["Rough ER differs from smooth ER by having","more lipids","ribosomes","more DNA","less water",1],
  ["Smallest unit of life is","tissue","organ","cell","organism",2],
  ["Lipid synthesis occurs in","Rough ER","Smooth ER","Golgi","Nucleus",1],
  ["Cell activities are controlled by","cytoplasm","cell membrane","nucleus","mitochondria",2],
  ["Muscle cells have many mitochondria because they need","water","oxygen","energy","glucose",2],
  ["Nuclear membrane controls","protein synthesis","nuclear contents","energy production","waste removal",1],
  ["Chlorophyll gives plants their","red","blue","green","yellow",2],
  ["Active transport moves substances ___ concentration gradient","with","against","along","away from",1],
  ["Which process requires no energy to move substances?","Active transport","Endocytosis","Passive diffusion","Exocytosis",2],
  ["Vacuoles in plant cells mainly store","proteins","lipids","water and nutrients","DNA",2],
  ["Which cell type has no membrane-bound organelles?","Eukaryotic","Prokaryotic","Plant","Animal",1],
  ["The fluid mosaic model describes the","nucleus","cell membrane","cytoplasm","ribosome",1],
  ["Centrioles are involved in","protein synthesis","cell division","photosynthesis","respiration",1],
  ["Which organelle breaks down hydrogen peroxide?","Lysosome","Peroxisome","Golgi","Nucleus",1],
  ["Microtubules form the","cell wall","cytoskeleton","nucleus","ribosome",1],
  ["Plasmolysis occurs when a plant cell loses","DNA","water","proteins","lipids",1],
  ["Turgor pressure in plants is caused by","osmosis","active transport","diffusion","endocytosis",0],
  ["Which molecule makes up the cell membrane bilayer?","Protein","Phospholipid","Carbohydrate","DNA",1],
  ["Exocytosis moves substances","into the cell","out of the cell","within the cell","to the nucleus",1],
  ["Which organelle is the site of aerobic respiration?","Chloroplast","Nucleus","Mitochondria","Ribosome",2],
  ["Chromatin condenses into ___ during cell division","ribosomes","chromosomes","vacuoles","lysosomes",1],
  ["The nucleolus produces","DNA","mRNA","ribosomes","proteins",2],
  ["Tonoplast is the membrane surrounding the","nucleus","chloroplast","vacuole","mitochondria",2],
  ["Which junction allows direct communication between cells?","Tight junction","Gap junction","Desmosome","Plasmodesma",1],
  ["Pinocytosis is the uptake of","solids","liquids","gases","DNA",1],
  ["Which organelle detoxifies drugs in liver cells?","Rough ER","Smooth ER","Golgi","Lysosome",1],
  ["Cristae are folds found in the","nucleus","chloroplast","mitochondria","vacuole",2],
  ["Thylakoids are found in","mitochondria","nucleus","chloroplast","ribosome",2],
  ["Which process produces two identical daughter cells?","Meiosis","Mitosis","Binary fission","Budding",1],
  ["Cell plate forms during plant cell","interphase","mitosis","meiosis","apoptosis",1],
  ["Apoptosis is","cell growth","programmed cell death","cell division","cell repair",1],
  ["Which protein forms channels in the membrane?","Glycolipid","Integral protein","Cholesterol","Phospholipid",1],
  ["Cholesterol in the membrane increases","fluidity","rigidity","permeability","size",0],
  ["Which stage of mitosis do chromosomes align at the equator?","Prophase","Metaphase","Anaphase","Telophase",1],
  ["Sister chromatids separate during","Prophase","Metaphase","Anaphase","Telophase",2],
  ["Nuclear envelope reforms during","Prophase","Metaphase","Anaphase","Telophase",3],
  ["Which organelle is involved in intracellular digestion?","Ribosome","Lysosome","Golgi","Nucleus",1],
  ["Stroma is the fluid-filled space in the","mitochondria","nucleus","chloroplast","vacuole",2],
];

bioCellQ.forEach(([q,a,b,c,d,ai],i)=>{
  biology.push({id:`MCQ-BIO-CELL-${String(i+1).padStart(3,'0')}`,domain:"Biology",topic:"Cell Biology",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── BIOLOGY GENETICS ─────────────────────────────────────────────────────────
const bioGenQ = [
  ["Different forms of a gene are called","chromosomes","alleles","traits","phenotypes",1],
  ["Normal human body cells have ___ chromosomes","23","46","48","92",1],
  ["Traits are determined by","environment only","genes only","genes and environment","random chance",2],
  ["Aa × Aa cross gives ___ recessive offspring","0%","25%","50%","75%",1],
  ["Observable characteristics are called","genotype","phenotype","allele","chromosome",1],
  ["Mendel used ___ plants for his experiments","rose","pea","corn","wheat",1],
  ["Gametes are produced by","mitosis","meiosis","binary fission","budding",1],
  ["A mutation is a change in","protein shape","DNA sequence","cell size","membrane",1],
  ["DNA is mainly located in the","cytoplasm","nucleus","ribosome","mitochondria",1],
  ["Dominant allele is represented by","lowercase","uppercase","number","symbol",1],
  ["Homozygous means","two different alleles","two identical alleles","no alleles","three alleles",1],
  ["Heterozygous means","two identical alleles","two different alleles","no alleles","one allele",1],
  ["RR × WW with incomplete dominance gives","all red","all white","all pink","half red half white",2],
  ["Sex chromosomes in human females are","XY","XX","YY","XO",1],
  ["Sex chromosomes in human males are","XY","XX","YY","XO",0],
  ["Codominance means both alleles are","hidden","expressed equally","recessive","dominant over each other",1],
  ["Which blood type is universal donor?","A","B","AB","O",3],
  ["Which blood type is universal recipient?","A","B","AB","O",2],
  ["Genotype refers to","observable traits","genetic makeup","physical appearance","behaviour",1],
  ["A test cross uses a","homozygous dominant","heterozygous","homozygous recessive","random individual",2],
  ["Linked genes are on the","same chromosome","different chromosomes","mitochondria","ribosomes",0],
  ["Crossing over occurs during","mitosis","meiosis I","meiosis II","interphase",1],
  ["A karyotype shows","gene sequences","chromosome pairs","protein structures","cell organelles",1],
  ["Down syndrome results from trisomy of chromosome","18","21","23","13",1],
  ["Polygenic traits are controlled by","one gene","two genes","multiple genes","no genes",2],
  ["Epigenetics involves changes in","DNA sequence","gene expression","chromosome number","cell size",1],
  ["mRNA carries genetic info from","ribosome to nucleus","nucleus to ribosome","cytoplasm to nucleus","Golgi to nucleus",1],
  ["Translation occurs at the","nucleus","ribosome","Golgi","mitochondria",1],
  ["Transcription produces","protein","mRNA","tRNA","rRNA",1],
  ["A codon consists of ___ nucleotides","2","3","4","5",1],
  ["Stop codons signal","start of translation","end of translation","start of transcription","end of replication",1],
  ["DNA replication is","conservative","semi-conservative","dispersive","random",1],
  ["Helicase unwinds the","ribosome","DNA double helix","mRNA","tRNA",1],
  ["DNA polymerase adds nucleotides in ___ direction","3' to 5'","5' to 3'","both directions","random",1],
  ["Introns are","coding sequences","non-coding sequences","promoters","enhancers",1],
  ["Exons are","non-coding","coding sequences","introns","promoters",1],
  ["CRISPR is used for","cell division","gene editing","protein synthesis","osmosis",1],
  ["Gel electrophoresis separates DNA by","colour","size","shape","charge only",1],
  ["PCR amplifies","proteins","DNA sequences","RNA","lipids",1],
  ["A genome is the complete set of","proteins","DNA in an organism","RNA","chromosomes only",1],
  ["Recessive alleles are expressed when","one copy present","two copies present","dominant present","heterozygous",1],
  ["Punnett squares predict","actual outcomes","probable outcomes","certain outcomes","no outcomes",1],
  ["Carrier of a recessive disease is","affected","unaffected but carries allele","homozygous recessive","homozygous dominant",1],
  ["Haemophilia is an example of","autosomal dominant","autosomal recessive","X-linked recessive","X-linked dominant",2],
  ["Huntington's disease is","autosomal dominant","autosomal recessive","X-linked","mitochondrial",0],
  ["Cystic fibrosis is","autosomal dominant","autosomal recessive","X-linked recessive","Y-linked",1],
  ["Genetic drift is most significant in","large populations","small populations","stable populations","diverse populations",1],
  ["Natural selection acts on","genotype","phenotype","DNA directly","chromosomes",1],
  ["Speciation occurs when populations become","larger","reproductively isolated","more diverse","identical",1],
  ["Analogous structures have","same origin","different origin but same function","same function and origin","no function",1],
];

bioGenQ.forEach(([q,a,b,c,d,ai],i)=>{
  biology.push({id:`MCQ-BIO-GEN-${String(i+1).padStart(3,'0')}`,domain:"Biology",topic:"Genetics",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── BIOLOGY GENETICS ─────────────────────────────────────────────────────────
const bioGeneticsQ = [
  ["Different forms of a gene are called","chromosomes","alleles","traits","phenotypes",1],
  ["Normal human body cells contain how many chromosomes?","23","46","48","92",1],
  ["Traits are determined by","environment only","genes only","both genes and environment","random chance",2],
  ["Aa × Aa cross gives what % recessive phenotype?","0%","25%","50%","75%",1],
  ["Observable characteristics of an organism are its","genotype","phenotype","allele","chromosome",1],
  ["Who studied inheritance in pea plants?","Darwin","Mendel","Watson","Crick",1],
  ["Gametes are produced by","mitosis","meiosis","binary fission","budding",1],
  ["A mutation is","normal gene expression","a change in DNA sequence","chromosome pairing","cell division",1],
  ["Most DNA is located in the","cytoplasm","nucleus","ribosome","mitochondria",1],
  ["RR × WW with incomplete dominance gives","all red","all white","all pink","half red half white",2],
  ["Dominant allele is represented by","lowercase letter","uppercase letter","number","symbol",1],
  ["Homozygous means","two different alleles","two identical alleles","no alleles","three alleles",1],
  ["Heterozygous genotype is","AA","aa","Aa","none",2],
  ["Sex chromosomes in human females are","XY","XX","YY","XO",1],
  ["Sex chromosomes in human males are","XY","XX","YY","XO",0],
  ["Colour blindness is an example of","autosomal dominant","autosomal recessive","X-linked recessive","X-linked dominant",2],
  ["DNA stands for","Deoxyribonucleic acid","Diribonucleic acid","Deoxyribonitric acid","Dinucleic acid",0],
  ["The double helix structure of DNA was discovered by","Mendel and Darwin","Watson and Crick","Hooke and Leeuwenhoek","Pasteur and Koch",1],
  ["Adenine pairs with which base in DNA?","Cytosine","Guanine","Thymine","Uracil",2],
  ["Guanine pairs with which base in DNA?","Adenine","Thymine","Cytosine","Uracil",2],
  ["mRNA carries genetic information from","ribosome to nucleus","nucleus to ribosome","cytoplasm to nucleus","Golgi to nucleus",1],
  ["Translation occurs at the","nucleus","ribosome","Golgi","mitochondria",1],
  ["Transcription produces","protein","mRNA","tRNA","lipid",1],
  ["A codon consists of how many bases?","2","3","4","5",1],
  ["Which RNA brings amino acids to the ribosome?","mRNA","rRNA","tRNA","snRNA",2],
  ["Punnett squares predict","protein structure","inheritance probability","mutation rate","cell division",1],
  ["Polygenic traits are controlled by","one gene","two genes","multiple genes","no genes",2],
  ["Epigenetics involves changes in gene expression without changing","proteins","DNA sequence","RNA","chromosomes",1],
  ["Karyotype shows","protein structure","chromosome arrangement","DNA sequence","RNA sequence",1],
  ["Down syndrome results from trisomy of chromosome","18","21","23","13",1],
  ["Crossing over occurs during","mitosis","meiosis I","meiosis II","interphase",1],
  ["Linked genes are located on the","same chromosome","different chromosomes","mitochondria","ribosome",0],
  ["Genetic drift affects small populations by","increasing diversity","random allele frequency change","natural selection","mutation",1],
  ["Natural selection acts on","genotype","phenotype","DNA sequence","RNA",1],
  ["Which base is found in RNA but not DNA?","Thymine","Adenine","Uracil","Guanine",2],
  ["A frameshift mutation is caused by","substitution","insertion or deletion","duplication","inversion",1],
  ["Gel electrophoresis separates DNA by","colour","size","shape","charge only",1],
  ["PCR amplifies","proteins","DNA","RNA","lipids",1],
  ["CRISPR is used for","protein synthesis","gene editing","cell division","osmosis",1],
  ["Stem cells are described as","differentiated","undifferentiated","dead","mutated",1],
  ["Cloning produces organisms that are","genetically different","genetically identical","mutated","hybrid",1],
  ["Recessive alleles are expressed when","one copy present","two copies present","no copies present","three copies present",1],
  ["Incomplete dominance produces","one parent phenotype","other parent phenotype","blended phenotype","no phenotype",2],
  ["Codominance shows","blended phenotype","both phenotypes simultaneously","neither phenotype","random phenotype",1],
  ["ABO blood groups are an example of","incomplete dominance","codominance","sex linkage","polygenic inheritance",1],
  ["Gregor Mendel's law of segregation states alleles","combine","separate during gamete formation","duplicate","mutate",1],
  ["Law of independent assortment applies to genes on","same chromosome","different chromosomes","mitochondria","plasmids",1],
  ["Carrier of a recessive allele has genotype","AA","aa","Aa","none",2],
  ["Genetic counselling helps families understand","nutrition","inheritance risks","exercise","medication",1],
  ["Which technique sequences the entire genome?","PCR","Gel electrophoresis","Whole genome sequencing","Karyotyping",2],
];

bioGeneticsQ.forEach(([q,a,b,c,d,ai],i)=>{
  biology.push({id:`MCQ-BIO-GEN-${String(i+1).padStart(3,'0')}`,domain:"Biology",topic:"Genetics",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── CHEMISTRY ATOMIC STRUCTURE ───────────────────────────────────────────────
const chemAtomQ = [
  ["What is the charge of a proton?","Positive","Negative","Neutral","Variable",0],
  ["Atomic number is determined by","neutrons","protons","electrons","mass",1],
  ["Nucleus contains","protons and electrons","neutrons and electrons","protons and neutrons","only protons",2],
  ["Electrons are located","in the nucleus","in shells around nucleus","in the cytoplasm","randomly",1],
  ["Isotopes differ in number of","protons","electrons","neutrons","shells",2],
  ["Relative atomic mass accounts for","protons only","isotopes and abundance","electrons only","neutrons only",1],
  ["An ion is formed when an atom","gains or loses electrons","gains neutrons","splits","combines with another atom",0],
  ["A cation has a ___ charge","negative","neutral","positive","variable",2],
  ["An anion has a ___ charge","positive","neutral","negative","variable",2],
  ["The periodic table is arranged by","atomic mass","atomic number","number of neutrons","alphabetical order",1],
  ["Elements in the same group have the same number of","protons","neutrons","valence electrons","isotopes",2],
  ["Noble gases are in group","1","7","0 or 18","2",2],
  ["Alkali metals are in group","1","2","7","0",0],
  ["Halogens are in group","1","2","6","7",3],
  ["Transition metals are found in","groups 1-2","groups 3-12","groups 13-18","period 1",1],
  ["Electronegativity increases across a period from","right to left","left to right","top to bottom","randomly",1],
  ["Atomic radius increases down a group because","fewer shells","more shells","fewer protons","more neutrons",1],
  ["Ionisation energy is the energy to","add an electron","remove an electron","split the nucleus","form a bond",1],
  ["First ionisation energy generally increases across a period","left to right","right to left","top to bottom","bottom to top",0],
  ["Which subatomic particle has negligible mass?","Proton","Neutron","Electron","Nucleus",2],
  ["Mass number equals","protons only","neutrons only","protons plus neutrons","protons minus neutrons",2],
  ["Carbon-12 and Carbon-14 are","allotropes","isotopes","ions","compounds",1],
  ["Electron configuration of sodium (Na, Z=11) is","2,8","2,8,1","2,8,2","2,8,3",1],
  ["Electron configuration of chlorine (Cl, Z=17) is","2,8,6","2,8,7","2,8,8","2,7,8",1],
  ["A full outer shell means the element is","reactive","unreactive","an ion","a metal",1],
  ["Ionic bonds form between","two non-metals","two metals","metal and non-metal","two noble gases",2],
  ["Covalent bonds form between","two metals","metal and non-metal","two non-metals","noble gases",2],
  ["Metallic bonding involves","shared electrons","transferred electrons","delocalised electrons","ionic lattice",2],
  ["Which bond is strongest?","Ionic","Covalent","Metallic","Hydrogen",1],
  ["Water molecule shape is","linear","bent","trigonal planar","tetrahedral",1],
  ["CO2 molecule shape is","bent","linear","trigonal","tetrahedral",1],
  ["Electronegativity difference >1.7 suggests","covalent bond","ionic bond","metallic bond","no bond",1],
  ["Polar covalent bond has","equal sharing","unequal sharing","full transfer","no sharing",1],
  ["Which element has the highest electronegativity?","Oxygen","Chlorine","Fluorine","Nitrogen",2],
  ["Hydrogen bonding occurs between molecules containing H and","C","N O or F","S","P",1],
  ["Van der Waals forces are","strong permanent","weak temporary","ionic","covalent",1],
  ["Allotropes are different","compounds","structural forms of same element","isotopes","ions",1],
  ["Diamond and graphite are allotropes of","silicon","carbon","nitrogen","sulfur",1],
  ["Graphite conducts electricity because of","ionic bonds","delocalised electrons","covalent bonds","hydrogen bonds",1],
  ["Which state of matter has fixed volume but no fixed shape?","Solid","Liquid","Gas","Plasma",1],
  ["Sublimation is","solid to liquid","liquid to gas","solid to gas","gas to solid",2],
  ["Melting point of ionic compounds is generally","very low","moderate","very high","variable",2],
  ["Molecular compounds generally have","high melting points","low melting points","metallic lustre","electrical conductivity",1],
  ["Spectroscopy identifies elements by their","mass","emission spectra","colour","density",1],
  ["Flame tests identify","anions","cations","molecules","isotopes",1],
  ["Lithium flame colour is","yellow","red","crimson","lilac",2],
  ["Sodium flame colour is","yellow","red","green","blue",0],
  ["Potassium flame colour is","yellow","red","lilac","green",2],
  ["Copper flame colour is","yellow","blue-green","red","white",1],
  ["Rutherford's gold foil experiment proved the nucleus is","large and diffuse","small and dense","negative","absent",1],
];

chemAtomQ.forEach(([q,a,b,c,d,ai],i)=>{
  chemistry.push({id:`MCQ-CHEM-ATOM-${String(i+1).padStart(3,'0')}`,domain:"Chemistry",topic:"Atomic Structure",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── CHEMISTRY REACTIONS & ENERGY ─────────────────────────────────────────────
const chemReactQ = [
  ["A chemical reaction always produces","new elements","new substances","new atoms","new protons",1],
  ["Law of conservation of mass states mass is","created","destroyed","conserved","variable",2],
  ["Exothermic reactions release","light only","sound only","energy","mass",2],
  ["Endothermic reactions absorb","mass","energy","protons","electrons",1],
  ["Activation energy is the energy needed to","end a reaction","start a reaction","cool a reaction","balance a reaction",1],
  ["A catalyst increases reaction rate by","adding energy","lowering activation energy","increasing temperature","adding reactants",1],
  ["Catalysts are ___ in a reaction","consumed","produced","unchanged","destroyed",2],
  ["Rate of reaction can be increased by","decreasing temperature","decreasing concentration","increasing surface area","removing catalyst",2],
  ["Collision theory states reactions occur when particles","touch","collide with sufficient energy","are heated","dissolve",1],
  ["pH scale measures","temperature","acidity and alkalinity","pressure","concentration",1],
  ["pH 7 is","acidic","neutral","alkaline","basic",1],
  ["pH below 7 is","neutral","alkaline","acidic","basic",2],
  ["pH above 7 is","acidic","neutral","alkaline","basic",2],
  ["Acids produce ___ ions in water","OH-","H+","Na+","Cl-",1],
  ["Bases produce ___ ions in water","H+","OH-","Na+","Cl-",1],
  ["Neutralisation reaction produces","acid and base","salt and water","gas and water","metal and acid",1],
  ["Oxidation is","gain of electrons","loss of electrons","gain of protons","loss of protons",1],
  ["Reduction is","gain of electrons","loss of electrons","gain of protons","loss of protons",0],
  ["OIL RIG stands for","Oxidation Is Loss Reduction Is Gain","Oxidation Is Gain Reduction Is Loss","Only In Labs","none",0],
  ["Combustion requires","water","oxygen","nitrogen","carbon dioxide",1],
  ["Complete combustion of hydrocarbons produces","CO and H2O","CO2 and H2O","CO2 and H2","C and H2O",1],
  ["Incomplete combustion produces","CO2 and H2O","CO and soot","O2 and H2O","N2 and CO2",1],
  ["Electrolysis uses ___ to decompose compounds","heat","light","electricity","pressure",2],
  ["At the cathode in electrolysis","oxidation occurs","reduction occurs","no reaction","gas forms always",1],
  ["At the anode in electrolysis","oxidation occurs","reduction occurs","no reaction","metal deposits",0],
  ["Rusting requires","water only","oxygen only","water and oxygen","heat",2],
  ["Galvanising prevents rust by coating iron with","copper","tin","zinc","lead",2],
  ["Reactivity series ranks metals by","density","reactivity with water and acid","melting point","colour",1],
  ["Most reactive metal in reactivity series is","gold","iron","potassium","copper",2],
  ["Least reactive metal in reactivity series is","potassium","sodium","gold","iron",2],
  ["Displacement reaction occurs when","less reactive metal displaces more reactive","more reactive metal displaces less reactive","acids react with bases","salts dissolve",1],
  ["Precipitation reaction forms an","gas","insoluble solid","soluble salt","acid",1],
  ["Thermal decomposition breaks compounds using","electricity","water","heat","light",2],
  ["Cracking breaks large hydrocarbons into","larger molecules","smaller molecules","elements","salts",1],
  ["Polymerisation joins","small molecules into large chains","large molecules into small","atoms into ions","ions into atoms",0],
  ["Fermentation converts sugars into","oxygen and water","ethanol and CO2","CO2 and water","glucose and starch",1],
  ["Esterification produces","esters and water","salts and water","acids and bases","alcohols and acids",0],
  ["Saponification produces","esters","soap and glycerol","acids","salts",1],
  ["Le Chatelier's principle states equilibrium shifts to","increase products always","oppose changes applied","increase reactants always","stop the reaction",1],
  ["Haber process produces","sulfuric acid","ammonia","ethanol","chlorine",1],
  ["Haber process conditions include","low temperature high pressure","high temperature high pressure","low temperature low pressure","high temperature low pressure",1],
  ["Contact process produces","ammonia","nitric acid","sulfuric acid","hydrochloric acid",2],
  ["Titration determines","temperature","concentration of a solution","pressure","density",1],
  ["Indicator changes colour at the","start of reaction","equivalence point","end of heating","boiling point",1],
  ["Phenolphthalein is pink in","acid","neutral","alkali","salt",2],
  ["Litmus turns red in","alkali","neutral","acid","salt",2],
  ["Universal indicator shows","one colour only","range of colours for pH","temperature","pressure",1],
  ["Mole is the unit for","mass","amount of substance","volume","pressure",1],
  ["Avogadro's number is approximately","6.02×10²³","6.02×10²²","6.02×10²⁴","6.02×10²⁰",0],
  ["Relative formula mass is the sum of","atomic numbers","relative atomic masses","neutron numbers","electron numbers",1],
];

chemReactQ.forEach(([q,a,b,c,d,ai],i)=>{
  chemistry.push({id:`MCQ-CHEM-REACT-${String(i+1).padStart(3,'0')}`,domain:"Chemistry",topic:"Reactions and Energy",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── PHYSICS FORCES & MOTION ──────────────────────────────────────────────────
const physForcesQ = [
  ["SI unit of force is","Joule","Newton","Watt","Pascal",1],
  ["Newton's first law: object at rest stays at rest unless","pushed by gravity","acted on by unbalanced force","cooled","heated",1],
  ["Newton's second law: F =","mv","ma","m/a","a/m",1],
  ["Newton's third law states forces are","equal and same direction","equal and opposite","unequal and opposite","unequal and same direction",1],
  ["Weight is","mass × gravity","mass / gravity","mass + gravity","mass - gravity",0],
  ["Mass is measured in","Newtons","kilograms","metres","joules",1],
  ["Weight is measured in","kilograms","metres","Newtons","joules",2],
  ["Acceleration is","change in speed","change in velocity / time","distance / time","speed × time",1],
  ["Speed is","distance / time","time / distance","distance × time","force / mass",0],
  ["Velocity differs from speed because it includes","magnitude","direction","mass","energy",1],
  ["Friction acts","in direction of motion","opposite to direction of motion","perpendicular to motion","randomly",1],
  ["Terminal velocity occurs when","acceleration is maximum","drag equals driving force","speed is zero","mass increases",1],
  ["Momentum = ","force × time","mass × velocity","mass × acceleration","force × distance",1],
  ["Law of conservation of momentum applies to","open systems","closed systems","heated systems","charged systems",1],
  ["Impulse =","force × distance","force × time","mass × distance","mass × time",1],
  ["Work done =","force × time","force × distance","mass × velocity","mass × acceleration",1],
  ["Unit of work and energy is","Newton","Watt","Joule","Pascal",2],
  ["Power =","work / time","work × time","force × time","mass × velocity",0],
  ["Unit of power is","Joule","Newton","Watt","Pascal",2],
  ["Kinetic energy =","mgh","½mv²","mv","Fd",1],
  ["Gravitational potential energy =","½mv²","mgh","mv","Fd",1],
  ["On Earth g ≈","9.8 m/s²","9.8 m/s","9.8 N","9.8 J",0],
  ["Hooke's law: F =","ma","kx","mv","mgh",1],
  ["Elastic limit is where","spring returns to original length","spring permanently deforms","spring breaks","spring doubles",1],
  ["Pressure =","force × area","force / area","area / force","mass / area",1],
  ["Unit of pressure is","Newton","Joule","Pascal","Watt",2],
  ["Upthrust equals weight of","object","fluid displaced","container","air above",1],
  ["Archimedes' principle relates to","pressure","upthrust","friction","momentum",1],
  ["Centre of gravity is where","mass is greatest","weight acts","force is applied","pressure is highest",1],
  ["Torque =","force × distance from pivot","force / distance","mass × velocity","pressure × area",0],
  ["Equilibrium means","net force is zero","net force is maximum","acceleration is maximum","velocity is maximum",0],
  ["Resultant force is","sum of all forces","difference of forces","largest force","smallest force",0],
  ["Free body diagram shows","only gravity","all forces on object","velocity only","acceleration only",1],
  ["Scalar quantity has","magnitude and direction","magnitude only","direction only","neither",1],
  ["Vector quantity has","magnitude only","direction only","magnitude and direction","neither",2],
  ["Distance is a ___ quantity","vector","scalar","force","energy",1],
  ["Displacement is a ___ quantity","scalar","vector","force","energy",1],
  ["Speed is a ___ quantity","vector","scalar","force","energy",1],
  ["Velocity is a ___ quantity","scalar","vector","force","energy",1],
  ["Acceleration is a ___ quantity","scalar","vector","force","energy",1],
  ["On a distance-time graph, gradient represents","acceleration","speed","force","energy",1],
  ["On a velocity-time graph, gradient represents","speed","distance","acceleration","force",2],
  ["Area under velocity-time graph represents","acceleration","force","distance","energy",2],
  ["Centripetal force acts","outward from centre","toward centre","tangentially","randomly",1],
  ["Gravitational force between objects depends on","charge","mass and distance","temperature","colour",1],
  ["As distance doubles, gravitational force","doubles","halves","quarters","stays same",2],
  ["Projectile motion combines","two vertical motions","horizontal and vertical motion","two horizontal motions","circular and linear",1],
  ["Air resistance depends on","mass only","speed and surface area","temperature","colour",1],
  ["Drag force increases with","decreasing speed","increasing speed","decreasing area","decreasing density",1],
  ["Stopping distance = ","thinking distance only","braking distance only","thinking + braking distance","speed × time",2],
];

physForcesQ.forEach(([q,a,b,c,d,ai],i)=>{
  physics.push({id:`MCQ-PHYS-FORCE-${String(i+1).padStart(3,'0')}`,domain:"Physics",topic:"Forces and Motion",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── PHYSICS ENERGY & WAVES ───────────────────────────────────────────────────
const physWavesQ = [
  ["Waves transfer","matter","energy","mass","particles",1],
  ["Transverse waves vibrate","parallel to wave direction","perpendicular to wave direction","in circles","randomly",1],
  ["Longitudinal waves vibrate","perpendicular to wave direction","parallel to wave direction","in circles","randomly",1],
  ["Sound is a ___ wave","transverse","longitudinal","electromagnetic","static",1],
  ["Light is a ___ wave","longitudinal","transverse","mechanical","sound",1],
  ["Wave speed =","frequency × wavelength","frequency / wavelength","wavelength / frequency","amplitude × frequency",0],
  ["Frequency is measured in","metres","seconds","Hertz","Newtons",2],
  ["Wavelength is measured in","Hertz","seconds","metres","Newtons",2],
  ["Amplitude is the","distance between peaks","maximum displacement from rest","wave speed","frequency",1],
  ["Reflection is when waves","pass through a surface","bounce off a surface","bend around obstacles","slow down",1],
  ["Refraction is when waves","reflect","change speed and direction at boundary","diffract","absorb",1],
  ["Diffraction is when waves","reflect","refract","spread around obstacles","absorb",2],
  ["Electromagnetic spectrum from lowest to highest frequency","radio gamma visible","radio visible gamma","gamma visible radio","visible radio gamma",1],
  ["Which EM wave has the highest frequency?","Radio","Microwave","Visible light","Gamma ray",3],
  ["Which EM wave has the longest wavelength?","Gamma","X-ray","Visible","Radio",3],
  ["All EM waves travel at ___ in a vacuum","3×10⁸ m/s","3×10⁶ m/s","3×10¹⁰ m/s","3×10⁴ m/s",0],
  ["Infrared radiation is detected as","light","sound","heat","magnetism",2],
  ["Ultraviolet radiation can cause","cooling","skin cancer","hearing loss","magnetism",1],
  ["X-rays are used in","cooking","communication","medical imaging","heating",2],
  ["Gamma rays are used in","cooking","sterilisation and cancer treatment","communication","heating",1],
  ["Microwaves are used in","medical imaging","cooking and communication","sterilisation","X-ray imaging",1],
  ["Radio waves are used in","medical imaging","sterilisation","broadcasting and communication","cooking",2],
  ["Total internal reflection occurs when angle of incidence exceeds","45°","90°","critical angle","0°",2],
  ["Optical fibres use","reflection","refraction","total internal reflection","diffraction",2],
  ["Constructive interference occurs when waves","cancel out","add together","reflect","refract",1],
  ["Destructive interference occurs when waves","add together","cancel out","reflect","refract",1],
  ["Resonance occurs when driving frequency equals","half natural frequency","double natural frequency","natural frequency","zero",2],
  ["Pitch of sound depends on","amplitude","frequency","speed","wavelength only",1],
  ["Loudness of sound depends on","frequency","amplitude","speed","wavelength",1],
  ["Ultrasound frequency is above","20 Hz","200 Hz","2000 Hz","20000 Hz",3],
  ["Ultrasound is used in","X-ray imaging","medical scanning and sonar","broadcasting","cooking",1],
  ["Seismic P-waves are","transverse","longitudinal","electromagnetic","static",1],
  ["Seismic S-waves are","longitudinal","transverse","electromagnetic","static",1],
  ["S-waves cannot travel through","solids","liquids","gases","vacuum",1],
  ["Doppler effect causes change in","amplitude","observed frequency","wave speed","wavelength only",1],
  ["Red shift indicates a galaxy is","stationary","moving toward us","moving away from us","rotating",2],
  ["Big Bang theory is supported by","red shift and CMB","blue shift","constant universe size","no evidence",0],
  ["Nuclear fission splits","small nuclei","large nuclei","electrons","protons",1],
  ["Nuclear fusion joins","large nuclei","small nuclei","electrons","protons",1],
  ["Radioactive decay is","predictable for individual atoms","random for individual atoms","controlled by temperature","controlled by pressure",1],
  ["Alpha particle is","electron","proton","helium nucleus","neutron",2],
  ["Beta particle is","helium nucleus","fast electron","proton","neutron",1],
  ["Gamma ray is","particle","high energy EM radiation","sound wave","electron",1],
  ["Half-life is time for","all atoms to decay","half the atoms to decay","one atom to decay","none to decay",1],
  ["Which radiation is most penetrating?","Alpha","Beta","Gamma","Neutron",2],
  ["Which radiation is least penetrating?","Gamma","Beta","Alpha","Neutron",2],
  ["Alpha radiation is stopped by","thick lead","thin aluminium","paper","nothing",2],
  ["Beta radiation is stopped by","paper","thin aluminium","thick lead","nothing",1],
  ["Gamma radiation is reduced by","paper","aluminium","thick lead or concrete","nothing",2],
  ["Background radiation comes from","only nuclear power stations","natural and artificial sources","only space","only rocks",1],
];

physWavesQ.forEach(([q,a,b,c,d,ai],i)=>{
  physics.push({id:`MCQ-PHYS-WAVE-${String(i+1).padStart(3,'0')}`,domain:"Physics",topic:"Energy and Waves",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── EARTH SCIENCE GEOLOGY & CLIMATE ─────────────────────────────────────────
const earthGeoQ = [
  ["Igneous rock forms from","compressed sediment","cooled magma or lava","heat and pressure","fossils",1],
  ["Sedimentary rock forms from","cooled magma","compressed sediment layers","heat and pressure","volcanic activity",1],
  ["Metamorphic rock forms from","cooled magma","sediment","existing rock changed by heat and pressure","fossils",2],
  ["Granite is an example of","sedimentary","metamorphic","intrusive igneous","extrusive igneous",2],
  ["Basalt is an example of","sedimentary","metamorphic","intrusive igneous","extrusive igneous",3],
  ["Limestone is an example of","igneous","metamorphic","sedimentary","volcanic",2],
  ["Marble is metamorphosed","granite","limestone","basalt","sandstone",1],
  ["Slate is metamorphosed","limestone","granite","mudstone or shale","basalt",2],
  ["The rock cycle describes","water movement","rock transformation over time","atmospheric changes","ocean currents",1],
  ["Tectonic plates move due to","gravity only","convection currents in mantle","ocean tides","wind",1],
  ["Convergent plates","move apart","move toward each other","slide past each other","stay still",1],
  ["Divergent plates","move toward each other","move apart","slide past each other","stay still",1],
  ["Transform boundaries","move apart","move toward each other","slide past each other","collide",2],
  ["Earthquakes occur at","plate centres","plate boundaries","ocean floors only","mountain tops only",1],
  ["Volcanoes commonly occur at","plate centres","convergent and divergent boundaries","transform boundaries only","random locations",1],
  ["Richter scale measures","volcano intensity","earthquake magnitude","tsunami height","wind speed",1],
  ["Epicentre is","focus of earthquake","point on surface above focus","deepest point","plate boundary",1],
  ["Seismograph records","volcanic activity","earthquake waves","ocean currents","wind speed",1],
  ["Pangaea was","an ancient ocean","a supercontinent","a mountain range","an ice sheet",1],
  ["Continental drift was proposed by","Darwin","Wegener","Newton","Einstein",1],
  ["Evidence for continental drift includes","matching coastlines and fossils","ocean tides","wind patterns","rainfall",0],
  ["Mid-ocean ridges form at","convergent boundaries","divergent boundaries","transform boundaries","plate centres",1],
  ["Subduction occurs when","plates move apart","oceanic plate sinks under continental plate","plates slide past","plates collide equally",1],
  ["Greenhouse effect is caused by","ozone layer","greenhouse gases trapping heat","ocean currents","volcanic activity",1],
  ["Main greenhouse gases include","oxygen and nitrogen","CO2 methane and water vapour","argon and helium","ozone and hydrogen",1],
  ["Global warming refers to","cooling of Earth","rise in average global temperature","ozone depletion","acid rain",1],
  ["Ozone layer protects Earth from","infrared radiation","ultraviolet radiation","radio waves","microwaves",1],
  ["Acid rain is caused by","CO2 only","SO2 and NOx dissolving in rain","ozone depletion","greenhouse effect",1],
  ["Carbon cycle involves","only plants","movement of carbon through biosphere atmosphere and geosphere","only animals","only oceans",1],
  ["Photosynthesis removes ___ from atmosphere","oxygen","nitrogen","CO2","argon",2],
  ["Respiration releases ___ into atmosphere","oxygen","nitrogen","CO2","argon",2],
  ["Fossil fuels are formed from","rocks","ancient organic matter","seawater","volcanic ash",1],
  ["Burning fossil fuels releases","oxygen","CO2 and water vapour","nitrogen","argon",1],
  ["Renewable energy sources include","coal and oil","solar wind and hydro","nuclear and coal","gas and oil",1],
  ["Solar energy comes from","Earth's core","nuclear fusion in the Sun","wind","ocean tides",1],
  ["Wind energy is generated by","burning fuel","moving air turning turbines","solar panels","water flow",1],
  ["Hydroelectric power uses","wind","solar","flowing water","nuclear fission",2],
  ["Geothermal energy comes from","Sun","wind","Earth's internal heat","ocean tides",2],
  ["Tidal energy uses","wind","solar","ocean tides","river flow",2],
  ["Deforestation increases atmospheric CO2 because","trees absorb less oxygen","fewer trees absorb CO2","more animals breathe","soil releases gas",1],
  ["Ice cores provide evidence of","ocean temperatures","past atmospheric composition","earthquake history","volcanic activity only",1],
  ["Sea level rise is caused by","increased rainfall","melting ice and thermal expansion","decreased evaporation","ocean currents",1],
  ["Permafrost thawing releases","oxygen","CO2 and methane","nitrogen","argon",1],
  ["Albedo is the","heat absorbed","reflectivity of a surface","greenhouse effect","ozone level",1],
  ["High albedo surfaces","absorb more heat","reflect more light","absorb more UV","emit more radiation",1],
  ["Ocean acidification is caused by","CO2 dissolving in seawater","acid rain","volcanic activity","oil spills",0],
  ["Coral bleaching is caused by","cold water","warm water and acidification","oil spills","overfishing",1],
  ["Stratosphere contains the","ozone layer","troposphere","mesosphere","thermosphere",0],
  ["Weather occurs in the","stratosphere","mesosphere","troposphere","thermosphere",2],
  ["Coriolis effect influences","ocean depth","wind and ocean current direction","earthquake location","volcanic activity",1],
];

earthGeoQ.forEach(([q,a,b,c,d,ai],i)=>{
  earth.push({id:`MCQ-EARTH-GEO-${String(i+1).padStart(3,'0')}`,domain:"Earth Science",topic:"Geology and Climate",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── EARTH SCIENCE ECOLOGY & ENVIRONMENT ─────────────────────────────────────
const earthEcoQ = [
  ["A food chain always starts with a","consumer","producer","decomposer","predator",1],
  ["Energy transfer between trophic levels is approximately","90%","50%","10%","1%",2],
  ["Decomposers break down","living organisms","dead organic matter","rocks","water",1],
  ["Biodiversity refers to","number of individuals","variety of species in an area","total biomass","population size",1],
  ["A habitat is","an organism's role","the place where an organism lives","a food chain","a population",1],
  ["A niche is","an organism's habitat","an organism's role in ecosystem","a food chain","a population",1],
  ["Interspecific competition is between","same species","different species","predator and prey","decomposers",1],
  ["Intraspecific competition is between","different species","same species","predator and prey","decomposers",1],
  ["Predator-prey relationships show","both populations stable","oscillating population cycles","one population always wins","no relationship",1],
  ["Carrying capacity is","maximum population an environment can sustain","minimum population","average population","birth rate",0],
  ["Limiting factors include","food water and space","sunlight only","temperature only","water only",0],
  ["Biomass is","number of organisms","total mass of living material","energy in food","population size",1],
  ["Pyramid of biomass shows","number of organisms","biomass at each trophic level","energy flow","population size",1],
  ["Pyramid of numbers shows","biomass","energy","number of organisms at each level","population growth",2],
  ["Nitrogen cycle involves","only plants","bacteria plants and animals","only bacteria","only animals",1],
  ["Nitrogen fixation converts","N2 to nitrates","nitrates to N2","ammonia to nitrates","nitrates to ammonia",0],
  ["Nitrification converts","N2 to nitrates","ammonia to nitrates","nitrates to N2","nitrates to ammonia",1],
  ["Denitrification converts","N2 to nitrates","ammonia to nitrates","nitrates to N2","ammonia to N2",2],
  ["Water cycle includes","evaporation condensation and precipitation","only evaporation","only precipitation","only condensation",0],
  ["Transpiration is water loss from","animals","plant leaves","soil","rocks",1],
  ["Eutrophication is caused by","excess nutrients in water","lack of nutrients","oil spills","acid rain",0],
  ["Eutrophication leads to","increased biodiversity","algal bloom and oxygen depletion","cleaner water","more fish",1],
  ["Bioaccumulation is","toxins decreasing up food chain","toxins increasing up food chain","nutrients cycling","energy transfer",1],
  ["Biomagnification means","toxins decrease in higher predators","toxins increase in higher predators","nutrients increase","energy increases",1],
  ["DDT is an example of","nutrient","bioaccumulating pesticide","fertiliser","antibiotic",1],
  ["Invasive species","increase biodiversity","outcompete native species","help native species","have no effect",1],
  ["Keystone species","have little ecosystem impact","have disproportionately large ecosystem impact","are always predators","are always plants",1],
  ["Symbiosis is","competition between species","close interaction between two species","predation","decomposition",1],
  ["Mutualism benefits","one species only","neither species","both species","one species harms other",2],
  ["Parasitism benefits","both species","neither species","the parasite at host's expense","the host",2],
  ["Commensalism benefits","both species","one species without affecting other","neither species","the host",1],
  ["Succession is","sudden ecosystem change","gradual change in ecosystem over time","population explosion","extinction",1],
  ["Primary succession starts on","existing soil","bare rock or new land","disturbed land","forest floor",1],
  ["Pioneer species are","large trees","first organisms to colonise bare land","top predators","decomposers only",1],
  ["Climax community is","pioneer community","final stable community in succession","first community","disturbed community",1],
  ["Deforestation reduces","CO2 in atmosphere","biodiversity and increases CO2","rainfall only","soil erosion only",1],
  ["Overgrazing causes","increased soil fertility","soil erosion and desertification","increased biodiversity","more rainfall",1],
  ["Sustainable fishing involves","catching as many fish as possible","catching fish at rate they can replenish","banning all fishing","only catching large fish",1],
  ["Reforestation helps","increase CO2","reduce biodiversity","restore habitats and absorb CO2","increase soil erosion",2],
  ["Endangered species are","extinct","at risk of extinction","thriving","invasive",1],
  ["Extinction is","temporary disappearance","permanent loss of a species","migration","hibernation",1],
  ["Conservation aims to","exploit natural resources","protect and preserve biodiversity","increase pollution","reduce habitats",1],
  ["Ex-situ conservation occurs","in natural habitat","outside natural habitat (zoos seed banks)","in oceans","in atmosphere",1],
  ["In-situ conservation occurs","in zoos","in seed banks","in natural habitat","in laboratories",2],
  ["Indicator species signal","weather changes","environmental health or pollution","earthquake risk","volcanic activity",1],
  ["Lichens are indicators of","water pollution","air quality","soil fertility","temperature",1],
  ["Mayfly larvae indicate","polluted water","clean water","acidic water","salty water",1],
  ["Rat-tailed maggots indicate","clean water","polluted low-oxygen water","cold water","salty water",1],
  ["Quadrat sampling estimates","exact population","population density in an area","species behaviour","migration patterns",1],
  ["Transect sampling records","species at random points","species along a line","species in water","species underground",1],
];

earthEcoQ.forEach(([q,a,b,c,d,ai],i)=>{
  earth.push({id:`MCQ-EARTH-ECO-${String(i+1).padStart(3,'0')}`,domain:"Earth Science",topic:"Ecology and Environment",difficulty:["Easy","Medium","Hard"][i%3],question:q,options:[a,b,c,d],answerIndex:ai,explanation:`Correct answer: ${[a,b,c,d][ai]}`});
});

// ── WRITE OUTPUT ─────────────────────────────────────────────────────────────
const allQuestions = [...biology, ...chemistry, ...physics, ...earth];
console.log(`Total questions: ${allQuestions.length}`);

const ts = `export const mcqBank1400 = ${JSON.stringify(allQuestions, null, 2)};\n`;
fs.writeFileSync('./src/lib/tests/jmss-master-bank.ts', ts);
console.log('Written to src/lib/tests/jmss-master-bank.ts');
